Fix crash on zero init of buffer with no more ref count
gfx-rs/wgpu pull request #1190
Opened 2021-02-03 23:02 UTC by Wumpf

**Description**
Previously, if a buffer would no longer have any reference, the zero init step crashed when trying to unwrap its ref_count.
Working around this issue now by using a temporary ref count if necessary to do the resource transition.

Tbh I think this is a pretty ugly, potentially incorrect, solution, but it _seems_ to work and putting this here makes it easier to discuss how it could be done properly :)

**Testing**
Tested successfully on https://github.com/Wumpf/blub/commit/54a0f4ff13fcd969d87e4469067c6403999f79e2 where this problem would pop up

2021-02-04 15:24 UTC, kvark requested changes

2021-02-04 15:24 UTC, kvark commented on wgpu-core/src/device/queue.rs
> +        let tmp_ref_count = ptr::NonNull::new(Box::into_raw(Box::new(AtomicUsize::new(1))))
oh no, that's definitely not what we want here :)
Here it's too late to handle the deleted buffer. Instead, we should grab a refcount from it where it's used.
So `buffer_memory_init_actions` needs to carry that refcount to us.

2021-02-04 18:47 UTC, Wumpf commented
@kvark Let's pretend we never saw the first version of this PR :). Stuff actually makes sense now I think! But also it doesn't quite work, seems this keeps frames now alive for too long. Getting the following crash:
```
 0: std::panicking::begin_panic_handler
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:437
   2: wgpu::backend::direct::Context::handle_error_fatal<wgpu_core::swap_chain::SwapChainError>
             at C:\Users\andre\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\f891e86\src\backend\direct.rs:129
   3: wgpu::backend::direct::{{impl}}::swap_chain_present
             at C:\Users\andre\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\f891e86\src\backend\direct.rs:1371
   4: core::ptr::drop_in_place<wgpu::SwapChainTexture>
             at C:\Users\andre\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ptr\mod.rs:175
   5: core::mem::drop<wgpu::SwapChainTexture>
             at C:\Users\andre\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\mem\mod.rs:881
   6: blub::render_output::screen::Screen::end_frame
             at .\src\render_output\screen.rs:202
   7: blub::Application::draw
   ```
   
So what I naturally tried is to kill all the `buffer_memory_init_actions` from the command buffers by draining them in `initialize_used_uninitialized_memory`, but that didn't have the desired effect. Won't get to more digging today, but maybe you already know where to look? :)

2021-02-04 18:48 UTC, Wumpf commented
also it's a bit unfortunate that every buffer use in any binding will now bump the ref_count. Well, but it's ofc not really wrong & we can live with that I believe

2021-02-04 18:55 UTC, kvark commented
My apologies, I may have led you to a sub-optimal path. We don't want to do another  `add_ref()` there (although we can!) during recording because all the buffers are already referenced by the command buffer tracker! So we should add the following function to `impl<> ResourceTracker<>`:
```rust
    pub fn get_ref_count(&self, id: Valid<S::Id>) -> Option<&RefCount> {
        let (index, epoch, backend) = id.0.unzip();
        debug_assert_eq!(self.backend, backend);
        self.map.get(&index).map(|e| {
            assert_eq!(e.epoch, epoch);
            &e.ref_count
        })
    }
```
That would allows us to do `let ref_count = cmd_buf.tracker.get_ref_count(my_buffer_id).unwrap()` to then use for the state changes.

2021-02-06 10:11 UTC, Wumpf commented
oh. Yeah that's much better and easier. Thanks for writing it out as working code already. 
So when I tried to wire it up I ran into a relatively obvious borrow checker problem:
```
error[E0502]: cannot borrow `trackers` as mutable because it is also borrowed as immutable
   --> wgpu-core\src\device\queue.rs:568:30
    |
564 |             let buffer_ref_count = trackers
    |                                    -------- immutable borrow occurs here
...
568 |             let transition = trackers.buffers.change_replace(
    |                              ^^^^^^^^ mutable borrow occurs here
569 |                 id::Valid(buffer_id),
570 |                 buffer_ref_count,
    |                 ---------------- immutable borrow later used here
```
Pondering it a bit I decided to put it all into a `change_replace_tracked` method. The good thing about this is that it saves a hashmap lookup (as opposed to doing one lookup for `get_ref_count` and one lookup in `get_or_insert`), bad thing is that it adds an awkward "you know what you're doing?"-api to `ResourceTracker`. You be the judge :)
Tested it with Blub, works.


> already referenced by the command buffer tracker
I find it still unfortunate that the MemoryInitTracker and the the Tracker are separate. Feels like it should be possible to have a universal tracker of sorts.

2021-02-06 22:05 UTC, kvark reviewed
I see what you did here. This is a good way to approach this, better than what I suggested:)

2021-02-06 22:05 UTC, kvark commented on wgpu-core/src/track/mod.rs
> +    fn get<'a>(
How do you feel about making `ref_count: Option<&RefCount>` argument in the existing `get_or_insert`, instead of adding a new method?

2021-02-06 22:12 UTC, kvark commented
@Wumpf actually, hold on. I think I tried that before, and it becomes a little unfortunate that we wrap it in `Some` when we know the check is not needed. Let's just proceed.
bors r+

2021-02-06 22:15 UTC, closed without merging