Add limits for compute storage and max invocations
gfx-rs/wgpu pull request #2268
Opened 2021-12-08 19:38 UTC by kvark

**Connections**
https://github.com/gpuweb/gpuweb/pull/1863
https://github.com/gpuweb/gpuweb/pull/1898

**Description**
Catches up on our limits game.

**Testing**
Not much.

2021-12-08 19:41 UTC, cwfitzgerald requested changes

2021-12-08 19:41 UTC, cwfitzgerald commented on wgpu-info/src/main.rs
> +    println!("\t\tMax Compute Workgroups Per Dimmension:           {}", max_compute_workgroups_per_dimension);
It brought the typo back

2021-12-08 21:28 UTC, a1phyr commented on wgpu-hal/src/metal/mod.rs
> +    mac_varying_components: u32,
Pretty sure this is a typo

2021-12-09 00:40 UTC, kvark commented
whoa, I got 2 reviews!

2021-12-09 02:43 UTC, cwfitzgerald approved these changes

2021-12-09 02:43 UTC, merged