Add DEPTH24UNORM_STENCIL8 feature
gfx-rs/wgpu pull request #2689
Opened 2022-05-23 02:23 UTC by jinleili

WebGPU spec: https://gpuweb.github.io/gpuweb/#depth24unorm-stencil8

**Testing**
Tested on metal vk(--features=vulkan-portability) an dx12 backends

2022-05-29 07:05 UTC, cwfitzgerald requested changes
One nit, otherwise lgtm

2022-05-29 07:05 UTC, cwfitzgerald commented on wgpu-types/src/lib.rs
> +        /// - Metal (Intel Mac with discrete GPU)
```suggestion
        /// - Metal (Macs with intel or amd GPUs)
```

2022-05-29 07:42 UTC, jinleili commented on wgpu-types/src/lib.rs
> +        /// - Metal (Intel Mac with discrete GPU)
Tested on MacBook Pro 2017, only amd GPU supports this feature, so change to "Macs with and GPUs"?

2022-05-30 08:34 UTC, cwfitzgerald commented on wgpu-types/src/lib.rs
> +        /// - Metal (Intel Mac with discrete GPU)
The mac feature tables say this is supported on Intel macs too, which is where I was getting my wording from. So they not actually support it?

2022-05-30 09:07 UTC, jinleili commented on wgpu-types/src/lib.rs
> +        /// - Metal (Intel Mac with discrete GPU)
This additional text is marked in the feature tables:
> Support for this pixel format varies by device. Query the depth24Stencil8PixelFormatSupported property of MTLDevice to determine support. 

And `depth24Stencil8PixelFormatSupported` property is only available on [macOS](https://developer.apple.com/documentation/metal/mtldevice/1433371-depth24stencil8pixelformatsuppor)

<img width="1186" alt="截屏2022-05-30 16 57 43" src="https://user-images.githubusercontent.com/1001342/170956581-1b5660ca-981d-466b-bb5f-748137788171.png">

2022-05-30 19:29 UTC, cwfitzgerald commented on wgpu-types/src/lib.rs
> +        /// - Metal (Intel Mac with discrete GPU)
Woah, I totally missed that footnote!

2022-05-30 19:29 UTC, cwfitzgerald approved these changes

2022-05-30 19:29 UTC, merged