Track depth and stencil writability separately.
gfx-rs/wgpu pull request #2693
Opened 2022-05-25 03:14 UTC by jimblandy

Put some plumbing in place to accomodate the latest definition of `GPURenderBundleEncoderDescriptor` in the WebGPU spec, which now has separate `depthReadOnly` and `stencilReadOnly` members.

Rename `RenderPassDepthStencilAttachment::is_read_only` to `depth_stencil_read_only`, and don't skip validation steps due to early returns.

2022-05-25 03:15 UTC, jimblandy commented
![image](https://user-images.githubusercontent.com/751272/170172295-fc139599-3971-4e20-a3e9-6faa8851f7b7.png)

2022-06-04 01:16 UTC, cwfitzgerald requested changes
Some nit level stuff, otherwise LGTM

2022-06-04 01:16 UTC, cwfitzgerald commented on wgpu-core/src/command/render.rs
> +    /// Determine if the depth and stencil aspects of this attachment are read-only.
I would add a note either in the function name or the documentation that this also validates things.

2022-06-04 01:16 UTC, cwfitzgerald commented on wgpu-core/src/command/render.rs
> +    },
```suggestion
    #[error("render bundle has incompatible read-only flags: bundle has flags depth = {bundle_depth} and stencil = {bundle_stencil}, while the pass has flags depth = {pass_depth} and stencil = {pass_stencil}. Read-only renderpasses are only compatible with read-only bundles for that aspect.")]
    IncompatibleBundleRods {
        pass_depth: bool,
        pass_stencil: bool,
        bundle_depth: bool,
        bundle_stencil: bool,
    },
```

Just spelling things out a bit more to make sure it's clear what's going on

2022-06-07 06:02 UTC, cwfitzgerald approved these changes
LGTM

2022-06-07 06:02 UTC, merged