Add a vulkan workaround for large buffers.
gfx-rs/wgpu pull request #2796
Opened 2022-06-21 11:24 UTC by nical

**Description**

Some drivers run into fairly risky integer overflows with buffer sizes and buffer range parameters that don't fit in a 32 bits integer. Mesa/lavapipe is one of them.

This PR adds a driver workaround flag which, when set, limits buffer allocation sizes to what fits an i32.

For some context about mesa, it basically boils down to internal commands passing buffer ranges and sizes via `pipe_box`, see https://github.com/mesa3d/mesa/blob/81d6ae31d6f18d6fd2894a8b6dfe4323eea797f9/src/gallium/include/pipe/p_state.h#L529

I am not sure how to be more precise about enabling the workaround on linux. I suspect that it does not affect the nvidia proprietary driver, Iet me know if I can improve this.

Also I have no doubt that plenty of other drivers make the same mistake. If you want to be on the safe side, I don't think it would be unreasonable to set this workaround on all android devices (these tend to have more limited available memory anyway).

**Testing**

None.

2022-06-21 12:21 UTC, nical commented
Added [an entry](https://github.com/gfx-rs/wgpu/wiki/Known-Driver-Issues#mesa--vulkan) in the wiki.

2022-06-21 16:25 UTC, cwfitzgerald requested changes

2022-06-21 16:25 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/adapter.rs
> +        let is_mesa = cfg!(linux);
Lets say `(linux || android) && !nvidia` and you can identify nvidia by the PCI vendor ID. If it isn't in auxil::db, add it.

2022-06-21 16:25 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/device.rs
> +            return Err(crate::DeviceError::OutOfMemory);
We should still reduce the maximum buffer size limit to 2GB so that we don't need this check here and the user is aware of the hard limit

2022-06-22 14:17 UTC, cwfitzgerald requested changes
One nit, otherwise LGTM

2022-06-22 14:17 UTC, cwfitzgerald commented on wgpu-hal/src/dx11/adapter.rs
> +            max_buffer_size: std::u32::MAX as u64,
Let's use the newer style `u32::MAX` here (and elsewhere)

2022-06-22 16:31 UTC, cwfitzgerald approved these changes
Thanks!

2022-06-22 16:31 UTC, merged