[wgpu-hal] Initial Vulkan ray query and acceleration structure support
gfx-rs/wgpu pull request #3020
Opened 2022-09-12 21:29 UTC by expenses

**Checklist**

- [ ] Run `cargo clippy`.
- [ ] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**

#1040 

**Description**

Still a work in progress, but I can ray-trace instanced triangles now:

![20220912_23h26m53s_grim](https://user-images.githubusercontent.com/13566135/189761855-bee87a48-676c-4c99-992f-d1a03570c0fb.png)

Needs a cleanup and support for acceleration structure updates.

**Testing**
_Explain how this change is tested._

2022-09-15 10:10 UTC, expenses commented
Besides documentation and dummy implementations for the other backends, I think this is ready for review.

2022-10-12 20:46 UTC, cwfitzgerald requested changes
This is really great work - have no massive comments. tbh I don't fully understand RT apis as I haven't used them, but from what I know about them, this design seems sane and low overhead.

2022-10-12 20:46 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/command.rs
> +        let range = &[range][..];
What on earth?

2022-10-12 20:46 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/device.rs
> +                } - 1,
Let's pull the if statement into a variable.

2022-10-12 20:46 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/device.rs
> +                    // todo: Dereference the struct to get around lifetime issues. Safe as long as we never resize
If we need to do this, let's add an assertion that we always have room on push.

2022-10-12 20:46 UTC, cwfitzgerald commented on wgpu-hal/examples/ray-traced-triangle/main.rs
> +                    device.get_acceleration_structure_device_address(&blas)
This is the kind of thing we'd hide at the wgpu-core level?

2022-10-12 20:46 UTC, cwfitzgerald commented on wgpu-hal/src/lib.rs
> +        const TOP_LEVEL_ACCELERATION_STRUCTURE_INPUT = 1 << 12;
These probably need to be added to either INCLUSIVE or EXCLUSIVE in some way?

2022-12-08 10:27 UTC, expenses commented
This PR is currently on-pause because I don't have the time to work on it along with everything else I'm doing. I don't think it'll take much to get it to a mergeable state and if someone else wants to work on that then I'm happy to review their changes.

2022-12-17 21:40 UTC, seabassjh commented
@cwfitzgerald is there a list of TODOs left on this before being mergeable?  I'd like to pick this up

2022-12-17 22:34 UTC, cwfitzgerald commented
@seabassjh love to have this be picked up - the main ones are the comments on the PR

2022-12-17 22:37 UTC, expenses commented
> @cwfitzgerald is there a list of TODOs left on this before being mergeable? I'd like to pick this up

I imagine there's some work to be done to resolve https://github.com/gfx-rs/wgpu/pull/3044 etc as well

2023-02-02 02:53 UTC, daniel-keitel commented
I would like to help out.
@seabassjh have you continued work on this PR?
I have already made most of the requested changes, but I don't know how to contribute since it is @expenses PR.

2023-02-02 12:51 UTC, expenses commented
@daniel-keitel if you link me your changes I can review them and merge them into this branch

2023-02-20 05:56 UTC, daniel-keitel commented
@expenses I created a pull request on your fork.

2023-02-20 12:28 UTC, expenses commented
Hi @daniel-keitel, sorry I missed this. It might be better if you created a new PR on wgpu and then the discussion moved over to there.

2023-02-20 19:22 UTC, cwfitzgerald commented
Closing on favor of 3507

2023-02-20 19:22 UTC, closed without merging