Add `expose-ids` feature
gfx-rs/wgpu pull request #3104
Opened 2022-10-14 00:19 UTC by TheOnlyMrCat

**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
Discussed in matrix

**Description**
Adds the `expose-ids` feature, which allows API users to compare and store the identity of GPU objects through an opaque `Id` type. On native, `Id` wraps an unzipped `wgc::TypedId`; on web, `Id` wraps a manually-generated unique `u64`.

Most types with an `id` field now expose a feature-gated `global_id` method. (Currently, all the impls are unrolled, but perhaps it would be better as a macro?).

**Testing**
Not functionally tested yet, only typechecked

2022-10-14 02:04 UTC, i509VCB commented
Are these changes related to #3051?

2022-10-14 03:16 UTC, TheOnlyMrCat commented on wgpu/src/backend/web.rs
> +    Identified(value, id)
Oh! I didn't know those traits existed. Indexes into an array sounds like those ids would be reused on deallocation (and that's what the example code in [the `wasm-bindgen` guide](https://rustwasm.github.io/docs/wasm-bindgen/contributing/design/js-objects-in-rust.html#long-lived-js-objects) looks like it's doing), and I don't think that's appropriate for this use-case.

2022-10-14 04:04 UTC, cwfitzgerald commented
@i509VCB this particular use case is for unique identification of various resources for use in a cache, they need to be globally unique, not just unique-at-any-one-time.

2022-10-14 04:26 UTC, i509VCB commented on wgpu/src/backend/web.rs
> +    Identified(value, id)
If the requirement is unique, wouldn't the wgpu-core tracker reusing old IDs cause a conflict?

2022-10-14 04:31 UTC, TheOnlyMrCat commented on wgpu/src/backend/web.rs
> +    Identified(value, id)
It reuses freed indices, but also keeps track of the "epoch" of those indices. Reusing them still creates a unique id.

2022-10-14 14:22 UTC, ErichDonGubler commented on wgpu/src/backend/web.rs
> +    Identified(value, id)
@TheOnlyMrCat: Ah, so, they're [generational indices](https://lucassardois.medium.com/generational-indices-guide-8e3c5f7fd594)?

2022-11-02 21:59 UTC, cwfitzgerald requested changes
Looks great outside of a small comment

2022-11-02 21:59 UTC, cwfitzgerald commented on wgpu/src/backend/web.rs
> +use std::sync::atomic::{self, AtomicU64};
For cfg stuff, lets just fully qualify

2022-11-02 22:00 UTC, cwfitzgerald commented
Sorry for the long delay in reviewing

2022-11-03 19:39 UTC, TheOnlyMrCat commented on wgpu/src/backend/web.rs
> +use std::sync::atomic::{self, AtomicU64};
Done!

2022-11-04 19:28 UTC, cwfitzgerald approved these changes
Thanks!

2022-11-04 19:28 UTC, merged