Improve compute shader validation error message
gfx-rs/wgpu pull request #3139
Opened 2022-10-25 20:18 UTC by haraldreingruber

**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
Potential improvement for #2985 

**Description**
The previous error message was easily misunderstood, as it didn't say explicitly that each dimension and the total number must be below the bounds.

For example, instead of:

    shader entry point current workgroup size [8, 8, 8] must be less or equal to [256, 256, 64] of total 256

after applying this PR the error is:

    shader entry point current workgroup size [8, 8, 8] of total 512 must be less or equal to [256, 256, 64] and of total 256

Thanks to @mwalczyk for the original improvement idea 🙏

**Testing**
In `shader.wgsl` of the `hello-compute` example, I've changed the `@workgroup_size(1)` to `@workgroup_size(8, 8, 8)`

2022-10-26 20:35 UTC, cwfitzgerald commented on wgpu-core/src/validation.rs
> +        "shader entry point current workgroup size {current:?} of total {current_total} must be less or equal to {limit:?} and of total {total}"
```suggestion
        "shader entry point's workgroup size {current:?} ({current_total} total invocations) must be less or equal to the per-dimension limits {limit:?} and the total invocation limit {total}"
```

2022-10-26 20:38 UTC, cwfitzgerald requested changes
Thank you! Suggested some alternative wording to help make the error message even more clear.

2022-10-26 20:38 UTC, cwfitzgerald commented on CHANGELOG.md
> +- Improve compute shader validation error message
Don't forget to credit yourself and the PR

2022-10-29 20:42 UTC, haraldreingruber commented on wgpu-core/src/validation.rs
> +        "shader entry point current workgroup size {current:?} of total {current_total} must be less or equal to {limit:?} and of total {total}"
Thanks for the great improvement!

2022-10-29 21:48 UTC, cwfitzgerald approved these changes
Thanks!

2022-10-29 21:49 UTC, merged