allow gles float textures to be multisampled if available
gfx-rs/wgpu pull request #3183
Opened 2022-11-07 14:52 UTC by Wumpf

**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
n/a

**Description**
Couldn't find any restrictions on render target use for enabled float textures on GLES. It seems MSAA use works just fine iff the respective float extensions are enabled.

**Testing**
Tested rendering to a RGBA32f and RGBA16f target on WebGl. Did not check on resolve

2022-11-09 20:46 UTC, cwfitzgerald requested changes

2022-11-09 20:46 UTC, cwfitzgerald commented on wgpu-hal/src/gles/adapter.rs
> +                | Tfc::MULTISAMPLE
This needs adjustment now that the x2 and x8 PR has merged.

2022-11-23 19:21 UTC, Wumpf commented
@cwfitzgerald _bump_ :)

2022-11-23 21:10 UTC, cwfitzgerald approved these changes
Party

2022-11-23 21:10 UTC, merged