vk: eliminate duplicate values in SurfaceCapabilities' formats
gfx-rs/wgpu pull request #3227
Opened 2022-11-22 07:12 UTC by jinleili

**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Description**

`Vec<vk::SurfaceFormatKHR>` obtained by `get_physical_device_surface_formats` contains all supported color spaces and matching formats. Typically, a format appears in multiple color spaces. So currently in the vk backend, `get_supported_formats` will return duplicate `TextureFormat`'s : 
```sh
get_supported_formats: [Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, Bgra8UnormSrgb, 
Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, 
Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm, Bgra8Unorm, Rgba16Float, Rgb10a2Unorm]
```

Since `TextureFormat` does not derive `Ord` tait,   cannot directly call `sort_xx()` and then `dedup()`, a HashSet is used to help detect uniqueness.

**Testing**
Tested locally

2022-11-23 22:15 UTC, cwfitzgerald requested changes

2022-11-23 22:15 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/adapter.rs
> +        let mut uniques = std::collections::HashSet::new();
This is a kinda weird pattern, could you add a comment that explains what's going on.

2022-11-26 04:18 UTC, cwfitzgerald requested changes
I realize this solution is actually wrong, you need to filter out the formats that have a differing color space than we want to use (see https://github.com/gfx-rs/wgpu/blob/master/wgpu-hal/src/vulkan/device.rs#L542-L548). It's possible for a format to only be supported with a different color space than we want, and would cause UB on surface creation.

2022-11-26 05:26 UTC, jinleili commented
This commit also wrong, I'll recommit later.

2022-11-26 07:00 UTC, cwfitzgerald approved these changes
Nit then G2G

2022-11-26 08:37 UTC, merged

2025-09-14 21:55 UTC, MarijnS95 commented
Note that this PR was found to regress 10-bit (and 16-bit non-SFLOAT...) UNORM/SNORM formats that can now no longer be used with non-linear sRGB. Despite the code linked from @cwfitzgerald (false location turned back into a permalink: https://github.com/gfx-rs/wgpu/blob/f41a1c294bf09c4ab7e523f6c9aff5119044a097/wgpu-hal/src/vulkan/device.rs#L542-L548) only selecting extended scRGB for fp16 texture/surface format and the regular non-linear sRGB for everything else.

I've moved those back to the correct match arm in https://github.com/gfx-rs/wgpu/pull/8226.