Document when types are not WebGPU types.
gfx-rs/wgpu pull request #3235
Opened 2022-11-25 00:37 UTC by kpreid

**Checklist**

- [X] Run `cargo clippy`.
- [X] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] ~~Add change to CHANGELOG.md. See simple instructions inside file.~~ Skipping this

**Connections**
This is a probably-less-interesting side branch from #2653 where I added documentation linking to the WebGPU specification to many types.

**Description**
This change documents types that *don't* correspond to the WebGPU specification, so readers can know they are unique to `wgpu`.

I also changed the wording in `BufferSlice` to be more consistent with other documentation.

**Testing**
Only documentation was changed. I manually examined the rustdoc output.

2022-11-26 02:28 UTC, cwfitzgerald commented
The only thing I worry about is that people might interpret this as them being native features, not just that they're unique to wgpu.

2022-11-26 02:40 UTC, kpreid commented
Hmm. For that concern, what do you think of something like

> This type is unique to the Rust API of `wgpu`. In the WebGPU specification, {explain the corresponding thing} instead.

The idea being to emphasize that this is a “Rust bindings” thing.

2022-11-26 02:43 UTC, cwfitzgerald commented
That looks great

2022-11-30 23:11 UTC, cwfitzgerald requested changes
For above change.

2022-12-01 02:25 UTC, kpreid commented
Done. For example, `Operations`' documentation now contains

> This type is unique to the Rust API of `wgpu`. In the WebGPU specification, separate `loadOp` and `storeOp` fields are used instead.

2022-12-01 02:28 UTC, cwfitzgerald approved these changes

2022-12-01 02:30 UTC, merged