Add `SHADERINT_16` feature to allow 16bit ints in Vulkan shaders
gfx-rs/wgpu pull request #3401
Opened 2023-01-19 00:36 UTC by Elabajaba

**Checklist**

- [x] Run `cargo clippy`.
- [ ] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
Stops Vulkan Validation errors for FSR2 when using https://github.com/JMS55/fsr2_wgpu (currently very much a WIP).

**Description**
This just enables the Vulkan `shader_int16` device feature if the feature is requested. I copied how it seems to be done for `SHADER_FLOAT64`.

According to [the docs](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceFeatures.html), this isn't an extension and is part of vulkan 1.0 `VkPhysicalDeviceFeatures`. ~~I don't know if anything doesn't support this feature, so I'm wondering if it should be enabled by default?~~ Did some more digging on https://vulkan.gpuinfo.org/ and it isn't nearly as universal as I thought.

**Testing**
Tested using bevy+fsr2, it stopped the validation errors about 16bit ints.

2023-01-19 04:12 UTC, crowlKats requested changes
don't forget to update `deserialize_features` in deno_webgpu/src/lib.rs, and update the `GPUFeatureName` enum in deno_webgpu/src/02_idl_types.js

2023-01-19 14:04 UTC, teoxoy commented
Wanted to mention that I filed https://github.com/gfx-rs/wgpu/issues/3406; not a blocker for this PR but something to put on our radar.

2023-01-20 01:53 UTC, Elabajaba commented
> don't forget to update `deserialize_features` in deno_webgpu/src/lib.rs, and update the `GPUFeatureName` enum in deno_webgpu/src/02_idl_types.js

Does the `GPUFeatureName` enum in deno_wgpu/webgpu.idl also have to be updated?

2023-01-20 13:10 UTC, crowlKats commented
> Does deno_webgpu want what are potentially native only features?

yes; if my memory serves right, the spec states that the implementer can extend the standard set of features. we just allow all features that wgpu has, because why not.

2023-01-20 22:07 UTC, Elabajaba commented
I think this should be done now.

2023-01-21 02:59 UTC, crowlKats commented
thanks!

2023-01-21 03:00 UTC, crowlKats reviewed
Deno part looks good to me.

2023-02-01 23:12 UTC, cwfitzgerald requested changes

2023-02-01 23:12 UTC, cwfitzgerald commented on wgpu-types/src/lib.rs
> +        /// Allows shaders to acquire the INT16 ability
```suggestion
        /// Allows shaders to use i16. Not currently supported in naga, only available through spirv-passthrough.```

2023-02-02 01:52 UTC, cwfitzgerald approved these changes

2023-02-02 02:00 UTC, merged