Support stencil-only views and copying to/from combined depth-stencil textures
gfx-rs/wgpu pull request #3436
Opened 2023-01-30 13:59 UTC by teoxoy

General changes:

- break down `describe` into `block_dimensions`, `required_features`, `guaranteed_format_features`, `sample_type` and `block_size`
- `sample_type` and `block_size` now take an optional `TextureAspect`

To enable copying to/from combined depth-stencil textures:
- [validation] copy aspect must refer to a single aspect of format
- [validation] update `validate_linear_texture_data` according to the WebGPU spec
- [validation] require missing `DEPTH_TEXTURE_AND_BUFFER_COPIES` downlevel flag for `queue_write_texture` and `command_encoder_copy_buffer_to_texture`
- [metal] set the right `MTLBlitOption` for texture/buffer copies
- [dx12] use the aspect specific texture format for the copy

To create stencil-only views from combined depth-stencil textures:
- [metal] set the right format `X24_Stencil8`/`X32_Stencil8` for the view and `MTLTextureUsage::PixelFormatView` for the texture
- [gles] set the right `DEPTH_STENCIL_TEXTURE_MODE` to either `DEPTH_COMPONENT` or `STENCIL_INDEX`
- [dx12] set the right formats `DXGI_FORMAT_X32_TYPELESS_G8X24_UINT` and `DXGI_FORMAT_X24_TYPELESS_G8_UINT`

2023-02-01 22:39 UTC, cwfitzgerald requested changes
This is amazing stuff - my only main ask is if there could be a test for it - with this amount of code it's hard to judge if it's actually correct

2023-02-01 22:39 UTC, cwfitzgerald commented on CHANGELOG.md
> +#### General
We should also make a major changes note about the api of `describe()` changing.

2023-02-10 17:59 UTC, teoxoy commented
I created a `ReadbackBuffers` abstraction which allows us to copy textures to buffers regardless if they support `COPY_SRC` and updated `clear_texture` and `zero_init_texture_after_discard` to use it.

It should test depth view creation indirectly since it's needed for the copy via shader and to test stencil view creation, there is some commented out code to do so.

One thing worth noting is that once we get the CTS up and running, it should also test copying to/from combined depth-stencil textures and creation of stencil-only views.

2023-02-11 00:27 UTC, teoxoy commented
WARP is failing with...

```
[2023-02-11T00:11:10Z ERROR wgpu_hal::auxil::dxgi::result] Map buffer failed: 0x887A0005
[2023-02-11T00:11:10Z ERROR wgpu_core::device::life] Mapping failed Device(Lost)
```

My Nvidia dGPU and Intel iGPU run the test without issues.

2023-02-11 00:44 UTC, teoxoy commented
The `clear_texture` GLES implementation is also failing with "texture was not fully cleared".

2023-02-14 20:42 UTC, teoxoy commented
Should be good to go now.

2023-02-15 21:20 UTC, cwfitzgerald approved these changes
Absolutely stunning work all over, as always!

2023-02-15 21:20 UTC, merged