Fix macro to allow disabling `dx12` feature.
gfx-rs/wgpu pull request #3590
Opened 2023-03-14 20:00 UTC by toastmod

**Checklist**

- [x] Run `cargo clippy`.
- [ ] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [x] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
N/A

**Description**
Couldn't compile when disabling `dx12` feature from core in `wgpu/Cargo.toml`. Fixed by adding:
```rust
#[cfg(all(target_os = "windows", feature = "dx12"))]
```
My only concerns are if the functions I affected are also supposed to be used with `dx11`? Also might need some guidance on fixing the docs deployment test (if that was my fault).

**Testing**
Compiled without `dx12` feature in `wgpu/Cargo.toml`

2023-03-14 20:28 UTC, toastmod commented
I was able to compile and use wgpu without dx12 using these changes but I realize I should probably add this conditional macro over the `wgpu::Backends::DX12` enum.

2023-03-15 17:31 UTC, teoxoy requested changes
Thank you for the PR!

Just a nit: we seem to be using the style of guard that I suggested everywhere else.

2023-03-15 17:31 UTC, teoxoy commented on wgpu/src/backend/direct.rs
> +    #[cfg(all(target_os = "windows", feature = "dx12"))]
```suggestion
    #[cfg(all(feature = "dx12", windows))]
```

2023-03-15 17:31 UTC, teoxoy commented on wgpu/src/backend/direct.rs
> +    #[cfg(all(target_os = "windows", feature = "dx12"))]
```suggestion
    #[cfg(all(feature = "dx12", windows))]
```

2023-03-15 17:31 UTC, teoxoy commented on wgpu/src/lib.rs
> +    #[cfg(all(target_os = "windows", feature = "dx12"))]
```suggestion
    #[cfg(all(feature = "dx12", windows))]
```

2023-03-15 17:31 UTC, teoxoy commented on wgpu/src/lib.rs
> +    #[cfg(all(target_os = "windows", feature = "dx12"))]
```suggestion
    #[cfg(all(feature = "dx12", windows))]
```

2023-03-15 17:48 UTC, teoxoy approved these changes

2023-03-15 17:48 UTC, merged