Add `BGRA8UNORM_STORAGE` extension
gfx-rs/wgpu pull request #3634
Opened 2023-04-02 07:57 UTC by jinleili

**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
https://github.com/gfx-rs/wgpu/issues/3359

**Testing**
Tested locally on metal, vulkan(--features=vulkan-portability) and dx12 backends:
```rust
fn required_features() -> wgpu::Features {
    // wgpu::Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES
    // OR
    wgpu::Features::BGRA8UNORM_STORAGE
}

// ...

let a_texture = device.create_texture(&wgpu::TextureDescriptor {
    format: wgpu::TextureFormat::Bgra8Unorm,
    usage: wgpu::TextureUsages::STORAGE_BINDING,
    ...,
});

let test_tv = a_texture.create_view(&wgpu::TextureViewDescriptor {
    format: Some(wgpu::TextureFormat::Bgra8Unorm),
    ..Default::default()
});
```

2023-04-04 13:11 UTC, teoxoy requested changes
Thanks for the PR!

I think we should wait for naga to add support for the texel format before we merge this so that we can test it.

2023-04-17 04:23 UTC, jinleili commented on wgpu-hal/src/vulkan/adapter.rs
> +            vk::FormatFeatureFlags::STORAGE_IMAGE,
I'm sorry, I don't know how to do the check of `VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT `. Check for `FORMAT_FEATURE_2` requires obtaining `FormatProperties3` first, but no relevant method was found in `ash`.

2023-04-17 14:43 UTC, teoxoy commented on wgpu-hal/src/vulkan/adapter.rs
> +            vk::FormatFeatureFlags::STORAGE_IMAGE,
Isn't it this structure: https://docs.rs/ash/latest/ash/vk/struct.FormatProperties3.html ?

2023-04-17 21:30 UTC, jinleili commented on wgpu-hal/src/vulkan/adapter.rs
> +            vk::FormatFeatureFlags::STORAGE_IMAGE,
Yes, but no way to get it is provided, only`get_physical_device_format_properties` and `get_physical_device_format_properties` to get `FormatProperties` `FormatProperties2`.

2023-04-18 18:12 UTC, teoxoy commented on wgpu-hal/src/vulkan/adapter.rs
> +            vk::FormatFeatureFlags::STORAGE_IMAGE,
Hmm, how I think this should work is we call `get_physical_device_format_properties2` and pass it a `FormatProperties2` with a `FormatProperties3` in it's `pNext` chain.

This is quite convoluted as it requires extensions or specific vulkan versions.

`VK_KHR_get_physical_device_properties2` or VK1.1 for the query function and [`FormatProperties2`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFormatProperties2.html) structure +
`VK_KHR_format_feature_flags2` or VK1.3 for [`FormatProperties3`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFormatProperties3.html)

2023-09-14 20:54 UTC, cwfitzgerald commented
Hey this got lost in the PR stack, could you rebase this?

With naga not supporting it yet, how about we land all the infrastructure, but we keep the feature disabled.

2023-09-17 06:54 UTC, jinleili commented
@cwfitzgerald Already rebased, but I'm unsure how to keep the feature disabled.

2023-09-18 14:56 UTC, cwfitzgerald commented
Probably through wgpu-core removing the feature after it queries the features from the device. Can remove it and link back to the naga issue.

2023-09-27 15:40 UTC, teoxoy commented
There is still an unresolved discussion about the Vulkan impl.

2023-10-03 20:10 UTC, cwfitzgerald requested changes
Dismissing review request due to the above issue.

2023-10-10 14:31 UTC, nical commented
Heads up, I'm continuing the work on this branch: https://github.com/nical/wgpu/tree/bgra8unorm-storage 
I'll propose change to this PR or open a new one soon (currently writing a test and hoping it'll work).

2023-10-10 14:51 UTC, jinleili commented
I'm sorry I didn't deal with it for so long, since @nical is already done, it's more appropriate to open a new PR

2023-10-10 14:51 UTC, closed without merging