Implement `Features::RG11B10UFLOAT_RENDERABLE`
gfx-rs/wgpu pull request #3701
Opened 2023-04-18 05:16 UTC by jinleili

**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.

**Connections**
https://github.com/gfx-rs/wgpu/pull/3689
https://github.com/gfx-rs/wgpu/issues/3268

**Testing**
Tested locally

2023-04-18 06:44 UTC, crowlKats reviewed
Deno part LGTM

2023-04-18 17:01 UTC, teoxoy requested changes
Besides the comment it looks great! Thanks!

2023-04-18 17:01 UTC, teoxoy commented on wgpu/src/backend/web.rs
> +        format.guaranteed_format_features(wgt::Features::empty())
I think we should pass the actual adapter features here or else validation will fail even if the feature is actually supported.

2023-04-18 17:08 UTC, cwfitzgerald reviewed
After comment is addressed secondary g2g :)

2023-04-19 08:52 UTC, teoxoy approved these changes
Good stuff!

2023-04-19 08:53 UTC, teoxoy commented
@jinleili would you like to also reference this PR and your username in the existing changelog entry?

2023-04-19 09:00 UTC, jinleili commented
> @jinleili would you like to also reference this PR and your username in the existing changelog entry?

I prefer not to reference my username in the changelog. Thanks.

2023-04-19 11:34 UTC, merged