Fix multiview rendering
gfx-rs/wgpu pull request #3779
Opened 2023-05-17 07:09 UTC by MalekiRe

**Checklist**

- [ x] Run `cargo clippy`.
- [ ] Run `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
https://github.com/gfx-rs/wgpu/issues/3778

**Description**
WGPU Multiview works again by disabling some validation of TextureViewDimension and ResolvedArrayLayerCount

**Testing**
Running WGPU with a multiview enabled and trying it with multiple views.

2023-05-17 07:19 UTC, MalekiRe commented
@cwfitzgerald This is a PR to do the fix for the thing in the issue

2023-05-17 07:23 UTC, Wumpf approved these changes
lgtm!

2023-05-17 19:19 UTC, teoxoy requested changes, later dismissed
Thanks for the PR! Besides the comment it looks good!

2023-05-17 19:19 UTC, teoxoy commented on wgpu-core/src/device/mod.rs
> +                && !(self.features.contains(wgt::Features::MULTIVIEW)){
I think this should still check that the view dimension is `D2Array` if the feature is available instead of allowing all through.

2023-05-17 22:21 UTC, MalekiRe commented
@teoxoy Made the change

2023-05-17 23:53 UTC, MalekiRe commented
Do not merge this yet! I messed up the logic with the 2DTextureView to be inverted with the fix

2023-05-17 23:57 UTC, MalekiRe commented
Fixed, feel free to do checks, resolve the issue and merge

2023-05-19 03:48 UTC, cwfitzgerald approved these changes

2023-05-19 03:56 UTC, teoxoy approved these changes

2023-05-19 04:03 UTC, merged