Update max_bindings_per_bind_group from 640 to 1000 to reflect spec
gfx-rs/wgpu pull request #3942
Opened 2023-07-19 16:38 UTC by nical

**Checklist**

- [x] Run `cargo clippy`.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**

Spec: https://gpuweb.github.io/gpuweb/#dom-supported-limits-maxbindingsperbindgroup
Changed around mid April https://github.com/gpuweb/gpuweb/pull/4050

**Description**

This PR update `max_bindings_per_bind_group` from 640 to 1000 to reflect changes that happened in the spec since it was introduced.

**Testing**

This was caught by the WebGPU CTS in Firefox.

2023-07-19 18:28 UTC, ErichDonGubler requested changes
I hadn't realized that this PR was up. I'll close #3943, which duplicates this work.

We should also update `wgpu_types::Limits` and its documentation. You can crib those changes from #3943, if you want.

2023-07-19 18:29 UTC, ErichDonGubler commented on CHANGELOG.md
> -- Validate that `descriptor.usage` is not empty in `create_buffer` by @nical in [https://github.com/gfx-rs/wgpu/pull/#3928](3928)
nitpick: It'd be nicer for history if:

1. This fix of your previous `CHANGELOG` message were a separate commit.
2. The addition of the `CHANGELOG` entry for this PR were folded into the commit making the change.

Perhaps you were assuming that we'd squash? 🤔

2023-07-19 18:58 UTC, cwfitzgerald commented on CHANGELOG.md
> -- Validate that `descriptor.usage` is not empty in `create_buffer` by @nical in [https://github.com/gfx-rs/wgpu/pull/#3928](3928)
Wgpu always squashes, barring exceptional circumstances with fully independent commits where we rebase

2023-07-19 20:25 UTC, ErichDonGubler commented on CHANGELOG.md
> -- Validate that `descriptor.usage` is not empty in `create_buffer` by @nical in [https://github.com/gfx-rs/wgpu/pull/#3928](3928)
> fully independent commits

That's my goal with this particular feedback. 🙂

2023-07-19 22:41 UTC, ErichDonGubler approved these changes
LGTM! Sorry for the overlap with #3943. 😅

2023-07-19 22:42 UTC, ErichDonGubler commented on wgpu-types/src/lib.rs
> -            max_bindings_per_bind_group: 640,
Oh, shoot, this is something that #3943 missed. Thanks for catching this!

2023-07-20 08:35 UTC, nical commented
> LGTM! Sorry for the overlap with #3943. sweat_smile

No worries, I rebased this one on top of it to add the missing constant update in wgpu_types.

2023-07-20 14:02 UTC, cwfitzgerald approved these changes

2023-07-20 14:03 UTC, merged