Drop texture `clear_view`s in surface_texture_discard
gfx-rs/wgpu pull request #4057
Opened 2023-08-15 03:44 UTC by rajveermalviya

Fixes #4056

**Checklist**

- [x] Run `cargo clippy`.
- [x] Run `cargo clippy --target wasm32-unknown-unknown` if applicable.
- [ ] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
#4056 

**Description**
The texture `clear_view`s weren't destroyed in `surface_texture_discard` and that resulted in dangling `VkImageView`s.

**Testing**
Tested locally (on Linux) with repro mentioned in #4056

2023-08-15 04:13 UTC, rajveermalviya commented
This does fix the vulkan validation errors but still there is a weird behaviour, with the repro in #4056 if frame skip is triggered more than 3 times (not necessarily consecutive triggers): `get_current_texture` starts returning `SurfaceError::Timeout` unless the surface is reconfigured.

2023-08-15 04:26 UTC, cwfitzgerald commented
That's because discard isn't implemented:

https://github.com/gfx-rs/wgpu/blob/50cfc541aace5c94c14fc390dda6d54dda5468db/wgpu-hal/src/vulkan/instance.rs#L912

2023-08-15 04:30 UTC, cwfitzgerald commented
More specifically, I'm not sure there's a meaningful way to implement discard - we likely need to keep the image around at the core level and reuse it next time acquire is called.

2023-08-15 04:38 UTC, rajveermalviya commented
Hmm, in that case let's see how much I can grep.

2023-08-15 04:59 UTC, cwfitzgerald commented
We can leave that to a follow up

2023-08-16 16:26 UTC, cwfitzgerald requested changes

2023-08-16 16:26 UTC, cwfitzgerald commented on wgpu-core/src/present.rs
> +                if let resource::TextureClearMode::RenderPass { clear_views, .. } =
I think this would be better as a method on `TextureClearMode`

2023-08-18 18:55 UTC, rajveermalviya commented
> We can leave that to a follow up if that would be easier

Yeah, lets do that

2023-08-18 18:55 UTC, rajveermalviya commented on wgpu-core/src/present.rs
> +                if let resource::TextureClearMode::RenderPass { clear_views, .. } =
ack

2023-08-30 21:58 UTC, cwfitzgerald approved these changes
Noice

2023-08-30 21:58 UTC, merged