wgpu-core: Only produce StageError::InputNotConsumed on DX11/DX12
gfx-rs/wgpu pull request #4116
Opened 2023-09-05 01:43 UTC by Aaron1011

**Checklist**

- [X] Run `cargo clippy`.
- [X] Run `cargo clippy --target wasm32-unknown-unknown` if applicable.
- [X] Add change to CHANGELOG.md. See simple instructions inside file.

**Connections**
* https://github.com/gfx-rs/naga/issues/1945

**Description**

This error only exists due to an issue with naga's HLSL support: 
The WGPU spec itself allows vertex shader outputs that are not consumed by the fragment shader.

Until the issue is fixed, we can allow unconsumed outputs on all platforms other than DX11/DX12.

**Testing**
Run a program with an unconsumed shader output on a non-DX backend, and note the lack of error.

2023-09-05 17:50 UTC, cwfitzgerald commented
This is a pretty big portability hazard. If we wanted to do this, we would need to surface it as a feature that users can enable, knowing they are opting into behavior that is not portable to D3D. I would personally prefer if this was just fixed in naga, but a feature would be an acceptable interim solution.

2023-09-12 08:57 UTC, nical commented
Marked the PR as draft to reflect that Connor requested some changes to be made before it can be merged.

2023-09-14 13:06 UTC, nical requested changes

2023-09-14 13:06 UTC, nical commented on wgpu-hal/src/gles/adapter.rs
> +        features.set(wgt::Features::SHADER_EARLY_DEPTH_TEST, true);
Looks like you meant to use `SHADER_UNUSED_VERTEX_OUTPUT` here.

2023-09-20 14:09 UTC, nical approved these changes

2023-09-20 14:10 UTC, nical commented
Looks ready once the merge conflict in  wgpu-types/src/lib.rs is resolved.

2023-09-21 00:19 UTC, Aaron1011 commented
I fixed the merge conflict - I had to pick a different id for the feature

2023-09-21 01:02 UTC, merged

2023-10-09 21:55 UTC, torokati44 commented
Would it be possible to get this backported to the v0.17 branch, please? And perhaps get a new release with it in somewhat soon-ish?
We're in a similar situation as https://github.com/gfx-rs/wgpu/pull/3817#issuecomment-1676370084.

2023-10-10 10:14 UTC, torokati44 commented on wgpu-types/src/lib.rs
>          // 54..59 available
Just noticed, this line did not get updated.