Add more lints
gfx-rs/wgpu pull request #4598
Opened 2023-10-27 23:38 UTC by daxpedda

In #4597 I stumbled on a couple of `Surface` where I forgot to apply `'static`, which reminded me of `elided_lifetimes_in_paths`. I used it to make sure I didn't miss any others.

I'm not sure if this is desired at all, but though I would make PR so maintainers can take a look.
Additionally, I could easily add more lints:
- `rust-2018-compatibility`
- `rust-2018-idioms`
- `rust-2021-compatibility`

It pretty simply with `cargo fix`.

Requires #4597, but I'm happy to rebase it to `trunk` if it helps.

2023-10-28 02:04 UTC, kpreid commented
`rust-2018-compatibility` and `rust-2021-compatibility` aren't relevant in code that is already in the 2021 edition.

2023-10-28 10:20 UTC, daxpedda commented
> > I could easily add more lints like …
> 
> `rust-2018-compatibility` and `rust-2021-compatibility` aren't relevant in code that is already in the 2021 edition.

Aye, that makes sense.
I'm wondering why [`absolute-paths-not-starting-with-crate`](https://doc.rust-lang.org/1.73.0/rustc/lints/listing/allowed-by-default.html#absolute-paths-not-starting-with-crate) is in `rust-2018-compatibility` then ... that still seems useful to me in any edition. But it's the only relevant lint I could find.

2023-10-28 15:33 UTC, kpreid commented
> I'm wondering why [absolute-paths-not-starting-with-crate](https://doc.rust-lang.org/1.73.0/rustc/lints/listing/allowed-by-default.html#absolute-paths-not-starting-with-crate) is in rust-2018-compatibility then ... that still seems useful to me in any edition. But it's the only relevant lint I could find.

That one's not enabled because, past the 2015 edition, such paths don't even work; [the semantics were changed in 2018](https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html) such that absolute paths may only refer to named crates, where they could previously refer to items declared in the current crate root. So, that lint only means anything in 2015 edition code.

2023-10-28 16:22 UTC, daxpedda commented
Ah! Thanks @kpreid, much appreciated.

2023-11-16 22:29 UTC, daxpedda commented
Just to clarify: my suggestion in OP now boils down to adding [`rust-2018-idioms`](https://doc.rust-lang.org/1.73.0/rustc/lints/groups.html) only.

2023-11-16 22:47 UTC, cwfitzgerald commented
Yeah adding rust-2018 idioms seems good

2023-11-17 00:48 UTC, cwfitzgerald requested changes
Requesting changes per above.

(Reminder: please re-request a review from me once the changes are addressed to make sure I see it!)

2023-11-17 11:09 UTC, daxpedda commented
Done.

2023-11-17 20:59 UTC, cwfitzgerald approved these changes
We probably should add these to wgpu-core and hal as well, but let's wait till #3626 lands.

2023-11-17 20:59 UTC, merged