[naga wgsl-in] Preserve type names in `alias` declarations.
gfx-rs/wgpu pull request #4733
Opened 2023-11-21 00:57 UTC by jimblandy

Given a WGSL `alias` declaration, create a Naga `Type` with the alias's name, rather than dropping the type name on the floor.

**Checklist**

- [X] Run `cargo fmt`.
- [X] Run `cargo clippy`. If applicable, add:
- [X] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2023-11-21 10:46 UTC, teoxoy requested changes
`alias`es are just sugar for the full type and putting them in the IR will cause issues with type equivalence (`ensure_type_exists` will now return a different type than the one the `alias` is pointing to).

2023-11-21 17:38 UTC, jimblandy commented
> `alias`es are just sugar for the full type and putting them in the IR will cause issues with type equivalence (`ensure_type_exists` will now return a different type than the one the `alias` is pointing to).

We should be using `TypeInner::equivalent` for comparisons, not handle comparison, for this reason.

2023-11-22 14:05 UTC, teoxoy commented
`TypeInner::equivalent` is only needed because we have `TypeInner::ValuePointer`.

The existence of `TypeInner::ValuePointer` is questionable to me; it seems to complicate the code and make things harder to reason about given we already have `TypeInner::Pointer`.

Having the invariant that types are only equal if `Type == Type` is a lot easier to reason about and I thought is the main reason our type arena is a `UniqueArena`.

As an example of why I think we should avoid complicating type equality:

```wgsl
struct A {
    a: f32
}

struct B {
    a: f32
}

fn test(a: A) {}

fn test2(b: B) {
    test(b);
}
```

seems to validate just fine 😅

2023-11-22 17:15 UTC, teoxoy commented
@jimblandy and I talked about this and we decided to go with this PR for now and later remove `TypeInner::ValuePointer`/`TypeInner::equivalent` + achieve the effect this PR will have through a different mechanism.

2023-11-22 17:15 UTC, teoxoy approved these changes

2023-11-22 17:17 UTC, merged