[naga wgsl-in] Experimental 64-bit floating-point literals.
gfx-rs/wgpu pull request #4747
Opened 2023-11-22 04:25 UTC by jimblandy

In the WGSL front end, support an `l` suffix on floating-point literals to yield 64-bit integer literals.

Unless `Capabilities::FLOAT64` is selected, these literals will always be validated out, so it doesn't affect standards compliance.

This PR is questionable. I guess it's nice to have `f64` support to play with, but it's hardly urgent. Who knows whether the spec will ever actually have `f64` support, and if it does, what the syntax will be?

But the truth is, I have ulterior motives for this patch. It's a little circuitous:

- On the abstract type branch, all constructor built-in functions know how to consume abstract values. Calls to scalar constructor built-in functions (say, `f32(5)`) are handled by generating `As` expressions and letting the constant evaluator convert abstract values to concrete values. So `f32(5)` constant-evaluates the AbstractInt `5` to the `f32` `5.0`.
- It happens that the test case `tests/out/wgsl/double-math-functions.frag.wgsl` contains expressions like `f64(1.0)`. It's translated from GLSL, which does have a `double` type.
- Naga should either accept `f64(1.0)` or reject it.
    - If Naga rejects it, then we cannot translate `tests/in/glsl/double-math-functions.frag` to WGSL. The GLSL snapshots aren't really set up to generate other output languages; I don't really want to change that. Fine, maybe we back this test out, it's hardly essential. But let's assume that we want to accept it.
    - If Naga accepts it, then the only reasonable semantics for this expression should be that applying the `f64` constructor built-in function to an AbstractFloat gives you an `f64`.
- `ConstantEvaluator::cast` doesn't happen to support casting to `f64`. Since it returns an error, the WGSL front end assumes that the expression is not constant-evaluatable, and leaves it in the IR as an`AbstractFloat` literal, which the validator then rejects.
- Expanding `ConstantEvaluator::cast` to support casting to `f64` allows the `out/wgsl` file to validate.
- However, it also means that `Literal::F64` values start making it to the WGSL backend, which errors out because **WGSL has no `f64` literal syntax.** Hence the present PR.

So it seems to me we have two options:

- Give WGSL syntax for 64-bit literals, it generate them in `tests/out/wgsl/double-math-functions.frag.wgsl` and then read and validate them.
- Remove `tests/in/glsl/double-math-functions.frag` and forget all this.

**Checklist**

- [X] Run `cargo fmt`.
- [X] Run `cargo clippy`. If applicable, add:
- [X] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2023-11-22 05:22 UTC, jimblandy commented
Point in favor of this PR: It seems like the front and back ends already support an `f64` WGSL type. We just don't have a syntax for literals of that type.

If we do feel that adding experimental `f64` support is okay, then it would probably make sense to pair it with backend support for literals as well. There should then be snapshot tests for the literals too.

2023-11-22 06:22 UTC, cwfitzgerald commented
Speaking from community side, having support for this is one step closer to end-to-end f64 support, something that is asked for a decent amount, particularly from the scientifically minded folks.

2023-11-22 11:46 UTC, teoxoy commented
> - Give WGSL syntax for 64-bit literals, it generate them in `tests/out/wgsl/double-math-functions.frag.wgsl` and then read and validate them.

I'm also in favor of supporting `f64` 👍

2023-11-22 11:46 UTC, teoxoy requested changes

2023-11-22 11:46 UTC, teoxoy commented on naga/src/front/wgsl/parse/number.rs
> +                // might want to use `l` for 64-bit integers as well.
I think we should keep things consistent with `f`/`h` where it's not required to have a decimal point or exponent if the suffix has been specified.

The only way to do that is to disambiguate the syntax by having the suffixes map to a single type.

I like rust's suffixes but those are not consistent with the WGSL spec.

I suggest using `lf` for `f64`.
Then, we can have `li` and `lu` for `i64`/`u64`.

We can also use the same `SK` (`S` = size, `K` = kind) scheme later for 8-bit and 16-bit types (with the only exception being `hf` = `h`).

2023-11-22 18:09 UTC, jimblandy commented
Okay, here's full front and back end support with an `lf` suffix.

2023-11-23 11:17 UTC, teoxoy approved these changes

2023-11-23 11:17 UTC, merged