Eagerly release GPU resources when we lose the device.
gfx-rs/wgpu pull request #4834
Opened 2023-12-05 20:58 UTC by bradwerth

**Connections**
N/A

**Description**
This destroys buffer objects whenever we "lose the device", including at the end of the `device.destroy` process. Destruction of the buffers triggers reclamation of GPU memory, rather than waiting for the garbage collector to drop the buffer. It would be ideal to also destroy texture objects, but `texture.destroy` is not implmented, as noted in a TODO.

**Testing**
This is exercised by any bulk test execution, like the CTS, which relies on `device.destroy` (not waiting for the garbage collector) to free up GPU resources. Bulk test execution will have less failures due to full memory conditions.

**Checklist**

- [X] Run `cargo fmt`.
- [X] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [X] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2023-12-06 20:28 UTC, cwfitzgerald requested changes

2023-12-06 20:28 UTC, cwfitzgerald commented on wgpu-core/src/device/resource.rs
> +        let mut life_lock = self.lock_life();
We shouldn't be holding the life lock across external closure invocations - this could potentially deadlock.

2023-12-08 22:07 UTC, bradwerth commented
Ugh, I botched the rebase/merge and I'm not sure how to recover. I'll resubmit as a new PR.

2023-12-08 22:07 UTC, closed without merging

2023-12-08 22:20 UTC, bradwerth commented
New, non-borked PR is https://github.com/gfx-rs/wgpu/pull/4851.