Update multi-planar texture API
gfx-rs/wgpu pull request #4837
Opened 2023-12-06 13:50 UTC by teoxoy

**Connections**
https://github.com/gfx-rs/wgpu/issues/4825 & https://github.com/gfx-rs/wgpu/pull/4823#issuecomment-1840612949

**Description**
- remove the need to pass the plane formats to `view_formats`
- move plane selection in `TextureAspect`

2023-12-06 14:12 UTC, crowlKats reviewed
no comment

2023-12-06 14:23 UTC, nical approved these changes

2023-12-06 21:07 UTC, cwfitzgerald requested changes
Some small stuff, but looks much better

2023-12-06 21:07 UTC, cwfitzgerald commented on wgpu-types/src/lib.rs
> +            (format, TextureAspect::All) => {
```suggestion
            (format, TextureAspect::All) if !format.is_multi_planar_format() => {
```

Then you can just fallthrough to the None

2023-12-06 21:07 UTC, cwfitzgerald commented on wgpu-types/src/lib.rs
> +            _ => (1, 1),
I think this should be the block size for non-nv12. A user might rely on this value without knowing about the whole block thing.

2023-12-06 21:07 UTC, cwfitzgerald commented on wgpu-types/src/lib.rs
> +                TextureAspect::Plane2 => 2,
Typo? NV12 only has two planes?

2023-12-06 21:14 UTC, teoxoy commented on wgpu-types/src/lib.rs
> +                TextureAspect::Plane2 => 2,
Good catch!

2023-12-07 11:05 UTC, xiaopengli89 commented on wgpu-hal/src/dx12/device.rs
> +                texture.calc_subresource(desc.range.base_mip_level, desc.range.base_array_layer, 0),
The value of plane should be obtained from aspect.

2023-12-07 12:16 UTC, teoxoy commented on wgpu-hal/src/dx12/device.rs
> +                texture.calc_subresource(desc.range.base_mip_level, desc.range.base_array_layer, 0),
`target_base` is only used for resolve (I added a comment on it) which as far as I could find doesn't work with multi-planar nor combined depth-stencil textures.

2023-12-07 13:13 UTC, xiaopengli89 commented on wgpu-hal/src/dx12/device.rs
> +                texture.calc_subresource(desc.range.base_mip_level, desc.range.base_array_layer, 0),
Yeah, since we can now get the plane from the aspect, I think it is better to use the real plane to calculate the subresource.

2023-12-07 13:18 UTC, teoxoy commented on wgpu-hal/src/dx12/device.rs
> +                texture.calc_subresource(desc.range.base_mip_level, desc.range.base_array_layer, 0),
I meant that in this case the plane is irrelevant since you can never resolve into a multi-planar or combined depth-stencil texture.

2023-12-07 19:06 UTC, cwfitzgerald approved these changes

2023-12-07 19:06 UTC, merged