MissingBufferUsageError now has an id prop
gfx-rs/wgpu pull request #5203
Opened 2024-02-05 17:34 UTC by andristarr

**Connections**
https://github.com/gfx-rs/wgpu/issues/5066

**Description**
MissingBufferUsageError now has an id prop which is displayed when its raised

**Testing**

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-02-12 17:10 UTC, andristarr commented
Let me know if you would prefer another approach, i figured the buffer id would be sufficient

2024-02-13 17:26 UTC, nical requested changes
Sorry about the review lag, This one fell under the radar. Just a small change and this is is good to go.

2024-02-13 17:26 UTC, nical commented on wgpu-core/src/validation.rs
> +#[error("Buffer usage is {actual:?} for {id:?} which does not contain required usage {expected:?}")]
Let's rephrase this:

```
"Usage flags {actual:?} for buffer {id:?} do not contain required usage flags {expected:?}"
```

2024-02-13 18:06 UTC, andristarr commented on wgpu-core/src/validation.rs
> +#[error("Buffer usage is {actual:?} for {id:?} which does not contain required usage {expected:?}")]
Done!

2024-02-13 19:15 UTC, nical approved these changes

2024-02-13 19:16 UTC, nical commented
Thanks!

2024-02-14 12:27 UTC, merged