New validation error: struct members with the location attribute...
gfx-rs/wgpu pull request #5223
Opened 2024-02-08 02:55 UTC by ted-dokos

…can only be numeric scalars or numeric vectors.

**Connections**
https://github.com/gfx-rs/wgpu/issues/5184

**Description**
Naga used to allow this case through:
```
struct X { x:f32, }
struct Y { @location(0) x: X }
```
However, this is not valid wgsl. [The wgsl spec](https://www.w3.org/TR/WGSL/#attribute-location) states that location "[Must](https://www.w3.org/TR/WGSL/#shader-creation-error) only be applied to declarations of objects with [numeric scalar](https://www.w3.org/TR/WGSL/#numeric-scalar) or [numeric vector](https://www.w3.org/TR/WGSL/#numeric-vector) type."

**Testing**
Added a new test invalid_member_with_location_attribute. The test attempts to use a struct type for a member with the location attribute. This should error.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [pending] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-02-08 02:57 UTC, ted-dokos commented
Test results were not clean, but appear unrelated to my change:
```
------------
     Summary [ 140.811s] 623 tests run: 621 passed (12 flaky), 2 failed, 0 skipped
   FLAKY 2/3 [   4.927s] wgpu-examples [Executed] [Dx12/AMD Radeon RX 5700 XT/1] srgb-blend-linear
   FLAKY 2/3 [   3.801s] wgpu-examples [Executed] [Dx12/AMD Radeon RX 5700 XT/1] stencil-triangles
   FLAKY 2/3 [   2.777s] wgpu-examples [Executed] [Vulkan/AMD Radeon RX 5700 XT/0] texture-arrays-uniform
   FLAKY 2/3 [   1.319s] wgpu-test::wgpu-test [Executed Failure: ALWAYS] [Dx12/Microsoft Basic Render Driver/2] wgpu_test::buffer::empty_buffer
   FLAKY 2/3 [  10.965s] wgpu-test::wgpu-test [Executed] [Dx12/AMD Radeon RX 5700 XT/1] wgpu_test::clear_texture::clear_texture_uncompressed_gles
   FLAKY 2/3 [  36.677s] wgpu-test::wgpu-test [Executed] [Dx12/AMD Radeon RX 5700 XT/1] wgpu_test::shader::struct_layout::uniform_input
   FLAKY 2/3 [  28.881s] wgpu-test::wgpu-test [Executed] [Dx12/Microsoft Basic Render Driver/2] wgpu_test::shader::struct_layout::storage_input
   FLAKY 2/3 [   0.806s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 5700 XT/3] wgpu_test::device::device_lost_replaced_callback
   FLAKY 2/3 [   1.739s] wgpu-test::wgpu-test [Executed] [Gl/AMD Radeon RX 5700 XT/3] wgpu_test::queue_transfer::queue_write_texture_overflow
  TRY 3 FAIL [   7.847s] wgpu-examples [Executed] [Dx12/Microsoft Basic Render Driver/2] water
  TRY 3 FAIL [   2.239s] wgpu-test::wgpu-test [Executed Failure: BACKEND] [Vulkan/AMD Radeon RX 5700 XT/0] wgpu_test::shader::struct_layout::uniform_input
  ```

2024-02-08 17:24 UTC, teoxoy requested changes

2024-02-08 17:24 UTC, teoxoy commented on naga/src/valid/type.rs
> +                    }
I don't think we need this block as we check this here:

https://github.com/gfx-rs/wgpu/blob/07e59eb6fc7de3f682f1c401b9cf9f0da9ee4b4a/naga/src/valid/interface.rs#L268-L274

2024-04-18 10:58 UTC, teoxoy requested changes
Previous discussion was not resolved.

2024-04-18 15:00 UTC, ted-dokos commented on naga/src/valid/type.rs
> +                    }
Here's why I think we should have it anyway: the following snippet is wrong according to the spec:
```
struct X { x:f32, }
struct Y { @location(0) x: X }
```
But since we haven't written an entry point function using Y yet, the check in interface.rs won't catch this.

I should probably reuse NotIOShareableType, instead of creating my own error. What do you think?

2024-04-18 15:00 UTC, ted-dokos commented on naga/src/valid/type.rs
> +                    }
@teoxoy just checking in on the above. Do you still feel that this is redundant with the check in interface.rs?

2024-04-18 15:00 UTC, ted-dokos commented
I did respond to your comments, but apparently they were saved by GitHub as drafts and not sent.

At the moment I don't have the bandwidth to revisit this, so I will close it out.

2024-04-18 15:01 UTC, closed without merging