Tracker index
gfx-rs/wgpu pull request #5244
Opened 2024-02-12 14:35 UTC by nical

**Connections**

Fixes #5217
Fixes #4912
Required for fixing #5141
An important step towards #5120

**Description**

Before this PR, trackers use the ID's index to manage per-resource information. This gets in the way of a lot of things (see linked issues). This PR adds a per-resource tracker index that is independent from the resource ID. Separating the two concepts lets us handle deduplicated IDs which point to the same resource and is an important step towards removing the IDs in favor of exposing the Arcs.

This PR also lets IDs be recycled as soon as their user-facing handle is dropped, which fixes the de-duplicated resource leaks and will allow Gecko to fix the recycling of handles.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`.
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-02-12 14:40 UTC, nical commented
This PR contains https://github.com/gfx-rs/wgpu/pull/5242

2024-02-20 22:06 UTC, cwfitzgerald requested changes

2024-02-20 22:06 UTC, cwfitzgerald commented on wgpu-core/src/track/mod.rs
> +            query_sets: Arc::new(Mutex::new(TrackerIndexAllocator::new())),
Could we internalize these locks? It would make the call-sites simpler and prevent long holding locks.

2024-02-20 22:06 UTC, cwfitzgerald commented on wgpu-core/src/device/global.rs
> +                .insert(bundle.info.tracker_index(), bundle.clone());
This feels like tracker indices shouldn't go in suspected resources, but I think this is okay, as I believe suspected resources is going away soon?

2024-02-21 10:22 UTC, nical commented on wgpu-core/src/device/global.rs
> +                .insert(bundle.info.tracker_index(), bundle.clone());
I think that they should, or at least the idea is that resource IDs don't go in there anymore so something else has to.

> I believe suspected resources is going away soon?

That would be ideal

2024-02-21 10:44 UTC, nical commented on wgpu-core/src/track/mod.rs
> +            query_sets: Arc::new(Mutex::new(TrackerIndexAllocator::new())),
Done.

2024-02-26 20:08 UTC, cwfitzgerald approved these changes
Woot!

2024-02-26 20:25 UTC, merged