Pipeline constants
gfx-rs/wgpu pull request #5249
Opened 2024-02-14 14:28 UTC by teoxoy

Mainly implements override-expression evaluation for initializers of override declarations.

Tracking meta issue: https://github.com/gfx-rs/wgpu/issues/4484.

2024-03-05 17:35 UTC, jimblandy requested changes
Still reviewing, but I found one thing that (I think?) needs to change.

2024-03-05 17:35 UTC, jimblandy commented on naga/src/valid/mod.rs
> +    override_ids: BitSet,
Since pipeline constant ids can range from 0 to 65535 and aren't generally expected to be contiguous, it seems like this should probably be a `FastHashSet`, since a `BitSet` will expand out to i/8 bytes, for a maximum set member `i`.

2024-03-05 17:35 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                    }
Just checking: this is unrelated to the rest of the commit, right?

Suggestion, for the future's sake:

```
                     LoweredGlobalDecl::Override(handle) => {
                         Typed::Plain(crate::Expression::Override(handle))
                     }
-                    _ => {
+                    LoweredGlobalDecl::Function(_)
+                    | LoweredGlobalDecl::Type(_)
+                    | LoweredGlobalDecl::EntryPoint => {
                         return Err(Error::Unexpected(span, ExpectedToken::Variable));
                     }
                 };
```

2024-03-05 17:35 UTC, jimblandy commented on naga/src/proc/constant_evaluator.rs
> +    /// will be appended to the arena and no error will be returned.
Suggest:

```suggestion
    /// If `expr`'s value cannot be determined at compile time, and `self` is
    /// contributing to some function's expression arena, then append `expr` to
    /// that arena unchanged (and thus unevaluated). Otherwise, `self` must be
    /// contributing to the module's constant expression arena; since `expr`'s
    /// value is not a constant, return an error.
```

2024-03-05 17:35 UTC, jimblandy commented on naga/src/proc/constant_evaluator.rs
> +                Err(_) => Ok(self.append_expr(expr, span, false)),
I don't think this is correct. Division by zero errors, for example, need to be reported, not delayed until runtime.

I think we need to somehow split up `ConstantEvaluatorError` into two categories: errors because the expression cannot be evaluated until runtime, and errors that occurred even though the expression is a proper constant expression. Then we can treat those two differently here.

2024-03-06 10:06 UTC, teoxoy commented on naga/src/front/wgsl/lower/mod.rs
> +                    }
Yeah, this should have ben part of be0c12289a83f79a1d43b0428fa3524e8c5efb3f not 397b6731980dbb06ffb750e97784e1174eb7703d.

2024-03-06 10:10 UTC, teoxoy commented on naga/src/proc/constant_evaluator.rs
> +                Err(_) => Ok(self.append_expr(expr, span, false)),
Good catch! I think this is an existing issue though, I will open an issue.

2024-03-07 15:47 UTC, teoxoy commented on naga/src/proc/constant_evaluator.rs
> +                Err(_) => Ok(self.append_expr(expr, span, false)),
Actually I think be0c12289a83f79a1d43b0428fa3524e8c5efb3f took care of this. We now force evaluation to succeed if the expression was a const-expression. This is how I discovered we were not evaluating bool constructors properly (which I fixed in 33b392467919917a462d10f99f63cb707b8922f7).

2024-03-13 01:14 UTC, jimblandy commented
@teoxoy I pushed some comments - could you see if they're correct?

2024-03-13 12:58 UTC, teoxoy commented
They look great, thank you!

2024-03-13 19:07 UTC, jimblandy approved these changes
Okay, this looks good, let's merge it.

2024-03-13 19:16 UTC, merged

2024-03-13 19:19 UTC, ErichDonGubler commented
FTR: CI was failing because of https://github.com/gfx-rs/wgpu/pull/5341, but that's 👌🏻 okay, already been fixed because it was merged.

2024-03-13 19:42 UTC, jimblandy commented
> FTR: CI was failing because of #5341, but that's 👌🏻 okay, already been fixed because it was merged.

I pushed [a074d82](https://github.com/gfx-rs/wgpu/pull/5249/commits/a074d82966da808d1f6afc331d4b539f4d017faf) to fix that.

Also, note that I've only landed this in `gfx-rs:pipeline-constants`, not `trunk`.