Add multiple render targets example
gfx-rs/wgpu pull request #5297
Opened 2024-02-24 01:24 UTC by kaphula

**Connections**
None (I think).

**Description**
This PR adds new example that demonstrates how to use multiple render targets when you want to render to two or more targets from the fragment shader. 

As far as I know, none of the existing examples demonstrate this, and furthermore, finding information about how to do this with wgpu seems to be way too challenging, or at least it was for me. I had to ask help from multiple people who knew how to do this, and before that I was not even sure if this was possible at all.

**Testing**
I am not sure if this should or can be tested, or if the core feature has already been tested. Suggestions or instructions are welcome on how to implement the required tests.

2024-02-26 20:04 UTC, cwfitzgerald requested changes
Lots of comments, but in general looks good, and would love to have something like this in-tree!

2024-02-26 20:04 UTC, cwfitzgerald commented on wgpu-hal/Cargo.toml
> +version = "0.19.1"
There's definitely something going on, these bumps shouldn't be included

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/shader.wgsl
> +    return vec4<f32>(smp.x, smp.y, smp.z, 1.0);
```suggestion
    return vec4<f32>(smp.x, 1.0);
```

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/shader.wgsl
> +
```suggestion

```

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/screenshot.png
This can actually be autogenerated by the testing infrastructure if you add a test. Take a look at https://github.com/gfx-rs/wgpu/blob/trunk/examples/src/mipmap/mod.rs#L507-L518 for another example of an example test.

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/lib.rs
> +pub mod multiple_render_targets;
This also needs to be added to the examples/Readme.md

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/README.md
> +The program generates a black and white ball-shaped texture from scratch and uses fragment shader to draw it to two
```suggestion
The program generates a black and white ball-shaped texture from scratch and uses the fragment shader to draw it to two
```

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +            let mut img_data = vec![];
```suggestion
            let mut img_data = Vec::with_capacity(width * height);
```

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +            }
Could we expand the names of these variables to be more expressive?

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +        let height = 64;
Lets pull these into constants

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +            &create_halo_texture_data(width, height),
Nit: lets assign this to a variable.

2024-02-26 20:04 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +    event_loop
Take a look at the other examples that are rendering to screen - we should use the `Framework` here, which not only streamlines testing, but means we don't need all this duplicate winit and execution code, and can focus on the wgpu code.

2024-02-27 22:38 UTC, closed without merging

2024-02-27 22:38 UTC, kaphula commented
I'll do another PR from the scratch to see if it fixes those weird commits.