Add multiple render targets example (v2)
gfx-rs/wgpu pull request #5313
Opened 2024-02-27 22:42 UTC by kaphula

**Connections**
None (I think).

**Description**
This PR adds a new example that demonstrates how to use multiple render targets when you want to render to two or more targets from the fragment shader. 

As far as I know, none of the existing examples demonstrate this, and furthermore, finding information about how to do this with wgpu seems to be way too challenging, or at least it was for me. I had to ask help from multiple people who knew how to do this, and before that I was not even sure if this was possible at all.

**Testing**
I am not sure if this should or can be tested, or if the core feature has already been tested. Suggestions or instructions are welcome on how to implement the required tests.

**Dependencies**

This PR depends on https://github.com/gfx-rs/wgpu/pull/5312

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

This is a new version of https://github.com/gfx-rs/wgpu/pull/5297 which had some issues.

2024-03-14 01:20 UTC, cwfitzgerald requested changes
Looking good, some small comments, then probably one more small scale review, and this can land!

2024-03-14 01:20 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +use winit::event::WindowEvent;
Going to be _very_ annoying, and say we probably shouldn't import these names and always qualify with wgpu or the library they're from. It helps readability a ton when looking at a small section of code.

2024-03-14 01:20 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +        }
Let's make this a normal free function, not a nested one.

2024-03-14 01:20 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +fn create_target_textures(
Lets make this a `TextureTarget::new` and move it next to the definition of TextureTargets

2024-03-14 01:20 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +        let (ba, bb) =
```suggestion
        let (bg_a, bg_b) =
```

Or better yet bg_left bg_right.

2024-03-14 06:47 UTC, kaphula commented
@cwfitzgerald Your requested changes are now implemented. Let me know if there is anything else.

2024-03-15 05:29 UTC, kaphula commented
I added another commit to make all the imports direct as I realized that is probably what you meant and not just the wgpu imports.

2024-04-18 21:14 UTC, cwfitzgerald requested changes
A couple issues with the screenshot and such. Additionally in general the code needs a lot more commentary about what's going on and why (adding things like method documentation would go a long way).

Additionally there seems the tests are failing inside the GL backend, we can mark it as failing to not block merging this, but should be filed as a follow up issue.

2024-04-18 21:14 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/README.md
> +![Multi render target](./screenshot.png)
Did you run the tests locally with `cargo xtask test`? The screenshot was never generated

2024-04-18 21:14 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +    // Generated on 1080ti on Vk/Windows
These seem to just be blindly copied from other examples

2024-04-19 17:14 UTC, kaphula commented on examples/src/multiple_render_targets/README.md
> +![Multi render target](./screenshot.png)
The screenshot gets generated just fine for me, although bunch of tests fail on my machine overall. Do you want the generated screenshot to be part of the repository?

2024-04-19 17:15 UTC, kaphula commented on examples/src/multiple_render_targets/mod.rs
> +    // Generated on 1080ti on Vk/Windows
Is that a problem? Can you give me some guidance how the test should be configured for this specific example?

2024-04-19 17:23 UTC, kaphula commented on examples/src/multiple_render_targets/mod.rs
> +    // Generated on 1080ti on Vk/Windows
As for the comments, I am not sure what should be commented better. The readme of the example describes what the example does and how it works. There are also various comments in the code. The render function has inline comments describing what the draw calls of the example do. Should these comments be on the methods instead?

Is the issue with GL failing something related to the internals of wgpu and not this example? If not, is there something I can do about it?

2024-12-17 20:43 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/README.md
> +![Multi render target](./screenshot.png)
Yeah - the fact that the screenshot is generated is how we ensure the screenshot stays up to date with the example

2024-12-17 20:46 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +    // Generated on 1080ti on Vk/Windows
> Is that a problem? Can you give me some guidance on how the test should be configured for this specific example?

Basically the idea is that you'll start with the lowest possible tolerance, then increase it as you find issues on specific gpu/api combinations. In your case, this should be listed as whatever card you ran it on to generate the tolerance. This way we have a record of what device is keeping the limit high, so we can lower it if needed.

2024-12-17 20:46 UTC, cwfitzgerald commented
I don't think I did a very good job of reviewing this the first time around and giving actionable advice, so I'm going to give this another go. It also completely fell through the cracks of reviewing - sorry for all the trouble, we try to be more on top of things than this.

2024-12-17 20:48 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +    // Generated on 1080ti on Vk/Windows
> As for the comments, I am not sure what should be commented better. The readme of the example describes what the example does and how it works. There are also various comments in the code. The render function has inline comments describing what the draw calls of the example do. Should these comments be on the methods instead?

Let me give this another, better look

2024-12-17 22:10 UTC, cwfitzgerald requested changes
Alright, I have a few small comments, but I think this is largely ready to go! I've pushed a commit which fixes compilation issues that have happened in the interim.

Thanks for the patience :)

2024-12-17 22:10 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +            .collect::<Vec<_>>();
I can't tell why this is needed - shouldn't you be able to pass target_states directly?

2024-12-17 22:10 UTC, cwfitzgerald commented on examples/src/multiple_render_targets/mod.rs
> +    b_view: wgpu::TextureView,
I think these could have better names. Maybe `red_target_view`, or something similar. Same change for the locals in TextureTargets::new

2024-12-18 01:24 UTC, cwfitzgerald approved these changes
Very nice!

2024-12-18 01:25 UTC, kaphula commented
Hey, no worries. Better prioritize the library itself over examples first.

I applied your suggested changes. Let me know what you think. Should the changelog addition be moved to next release or do we leave it under `## v0.19.4 (2024-04-17)`?

2024-12-18 04:04 UTC, cwfitzgerald commented
> I applied your suggested changes. Let me know what you think.

Nice!

> Should the changelog addition be moved to next release or do we leave it under ## v0.19.4 (2024-04-17)?

The next release

2024-12-18 04:27 UTC, cwfitzgerald commented
Amazing, lets land this!

2024-12-18 04:41 UTC, merged