[fix bug #5430] index_limit judgment error in drawIndexed(indexCount)
gfx-rs/wgpu pull request #5435
Opened 2024-03-25 18:07 UTC by microaaron

[fix bug #5430] index_limit judgment error in drawIndexed(indexCount)

**Connections**
#5430

**Description**
index_limit judgment error in drawIndexed(indexCount). 
An error should be reported only when last_index > index_limit.

**Testing**
_Explain how this change is tested._
I'm not sure how to test it. Do I need to compile the entire firefox?

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-03-25 18:41 UTC, Wumpf requested changes
as mentioned on the ticket, I think we should really add a regression test on this one

2024-03-25 18:43 UTC, Wumpf commented
> I'm not sure how to test it. Do I need to compile the entire Firefox?

no. For test instructions see the README. Any updates to wgpu will eventually be picked up by Firefox at some point, but wgpu releases independently.

2024-03-25 21:05 UTC, microaaron commented
> no. For test instructions see the README. 

4failed
![捕获4failed](https://github.com/gfx-rs/wgpu/assets/16946786/aed95593-f64a-46cb-b243-444dd10bec3d)

2024-03-25 22:41 UTC, Wumpf commented
there should be more log describing the actual test failures. Not sure if we pass all tests right now on Windows right now, might depend also on installed driver version (we do run them on ci afaik, so that's fine) - this _is_ concerning, but in any case an orthogonal issue. After all, as long as we don't add a unit test that covers this issue this won't change the outcome much.
Don't worry if you're struggling to find how and where to do that, we'll definitely get this fix landed before the next release given that it's fairly critical. Good chance I get to it later this week.

2024-03-25 22:46 UTC, microaaron commented
Thanks a lot.

2024-03-27 11:02 UTC, Wumpf commented
took this over in https://github.com/gfx-rs/wgpu/pull/5441

2024-03-27 11:02 UTC, closed without merging