[naga wgsl-in] Fill out error message for deep nesting.
gfx-rs/wgpu pull request #5486
Opened 2024-04-03 19:58 UTC by jimblandy

In the WGSL front end, clarify error message for deeply nested statements.

@ErichDonGubler I was going to push this as a suggestion to the PR but forgot to. Only take it if you like it.

2024-04-04 18:48 UTC, ErichDonGubler approved these changes
I'm currently working on a few of our Firefox timeline items right now, so I won't be prioritizing this for the next couple of days, but I definitely intend to get back to this!

I'm actually surprised that you wanted to tweak this. Could you help me understand what your goals for revising were?

2024-04-04 18:48 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                message: "Statements nested too deeply".into(),
issue: The capitalized casing, for better or worse, is _not_ consistent with other diagnostics.

```suggestion
                message: "statements nested too deeply".into(),
```

2024-04-04 18:48 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                message: "Statements nested too deeply".into(),
This feedback also applies to the `notes` field.

2024-04-04 18:48 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    format!("The maximum nesting depth of brace-enclosed statements in a function is {limit}."),
issue: This diagnostic takes pains to note that this is related to statements, but that's not true. The limit current works based on opening braces in _any_ parsing rule. Therefore, I think attributing this to statements is misleading.

2024-04-04 18:48 UTC, ErichDonGubler requested changes
oderp, wrong button 😖

2024-09-22 07:52 UTC, cwfitzgerald commented
Boop from triage

2024-09-27 04:55 UTC, jimblandy commented
I don't want to change this any more.

2024-09-27 04:55 UTC, closed without merging