Fix Buffer Mapping Deadlock
gfx-rs/wgpu pull request #5518
Opened 2024-04-11 01:06 UTC by cwfitzgerald

Forward port of #5517

2024-04-14 07:48 UTC, Wumpf requested changes
same as #5517, this should have a changelog note imho

2024-04-15 20:32 UTC, ErichDonGubler approved these changes
Approving from Mozilla's side, for bookkeeping.

2024-04-17 16:11 UTC, Wumpf approved these changes

2024-04-18 00:41 UTC, cwfitzgerald commented
Changelog covered by #5552

2024-04-18 00:41 UTC, merged