Refactor MSL atomic writing
gfx-rs/wgpu pull request #5533
Opened 2024-04-14 19:50 UTC by atlv24

**Connections**
Just stuff I found while writing #5383

**Description**
MSL atomic writing code structure is inconsistent with glsl/hlsl/wgsl

**Testing**
No functional changes

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-04-15 17:58 UTC, teoxoy requested changes

2024-04-15 17:58 UTC, teoxoy commented on naga/src/back/msl/mod.rs
> +            Self::Exchange { compare: Some(_) } => "", //TODO
I think this variant should return `Error::FeatureNotImplemented` itself.

2024-04-18 02:49 UTC, atlv24 commented on naga/src/back/msl/mod.rs
> +            Self::Exchange { compare: Some(_) } => "", //TODO
I don't fully agree but i've made the changes. It required removing `const`, and its not consistent with these other ones anymore:
https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/back/hlsl/conv.rs#L223
https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/back/glsl/mod.rs#L86

2024-04-18 10:22 UTC, teoxoy commented on naga/src/back/msl/mod.rs
> +            Self::Exchange { compare: Some(_) } => "", //TODO
That's fair, I didn't notice those were like that.
Let's just merge this and once we implement that functionality it won't matter anymore.

2024-04-18 10:23 UTC, teoxoy approved these changes

2024-04-18 10:23 UTC, merged