Fix the ordering of id freeing and deleting
gfx-rs/wgpu pull request #5554
Opened 2024-04-18 08:39 UTC by DJMcNab

**Connections**
Fixes https://github.com/gfx-rs/wgpu/issues/5372

**Description**
When creating a resource in parallel with freeing a different resource on another thread, it was possible for the id to be made available before it was removed from storage.

That is, `unregister` was racing with e.g. `prepare().assign_existing()`

**Testing**
I cloned the linked reproduction, and applied this same patch.
The new version doesn't have this crash

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown` N/A
  - [ ] `--target wasm32-unknown-emscripten` N/A
- [x] Run `cargo xtask test` to run tests - no *new* failures
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

I'm not sure about a changelog entry, as this change is fixing a bug which was introduced in the 0.20 cycle

2024-04-18 20:37 UTC, cwfitzgerald requested changes
Looks good, have docs/test comments. Thanks for investigating this!

Is it possible to write a test for this?

2024-04-18 20:37 UTC, cwfitzgerald commented on wgpu-core/src/registry.rs
> +        self.identity.free(id);
Could you add documentation as to why this is in this order and documentation on the usage of assign_existing for why that's correct.

These bugs are super important to document well, as the interactions may be totally non-obvious to the outside (evidenced by us having the bug)

2024-04-18 22:48 UTC, Elabajaba approved these changes
Fix works for me!

2024-04-19 16:59 UTC, cwfitzgerald approved these changes
Good stuff

2024-04-19 16:59 UTC, merged