[core] Properly recycle `Device::temp_suspected`.
gfx-rs/wgpu pull request #5594
Opened 2024-04-24 01:28 UTC by jimblandy

Change the various uses of `Device::temp_suspected` to correctly
recycle its allocations when possible.

In the absence of errors, `Device::temp_suspected` is only used as
temporary storage within particular function calls, and is a field of
`Device` only as a way to recycle its allocations.

However, the code in `Global::queue_submit` that tries to use
`Device::temp_suspected` in this way doesn't quite pull it off.
It unconditionally replaces any prior `ResourceMaps` stored there
with a fresh empty one, clears the prior one, and then drops it,
wasting its allocations.

Rather than discard everything in `temp_selected` on every call to
`Device::maintain`, change `ResourceMaps::extend` to take the source
via `&mut` rather than by value, and have callers only obtain a `&mut`
to `Device::temp_selected`, rather than using `Option::take` to take
ownership of the value.

2024-04-30 16:03 UTC, ErichDonGubler commented
I'll take on review for this.

2024-05-02 19:45 UTC, ErichDonGubler commented
I promised review for yesterday, but it looks like this will be in my queue until Monday. Sorry for the wait! 😖

2024-05-03 19:20 UTC, ErichDonGubler requested changes
This PR conflicts with <https://github.com/gfx-rs/wgpu/pull/5653>, it seems, particularly my thought about [removing `temp_suspected` altogether](https://github.com/gfx-rs/wgpu/pull/5653#discussion_r1589505878). I think this should be closed? 🤔

2024-05-03 20:52 UTC, jimblandy commented
Yes, most of this PR is obviated by #5653, but the change to `Device::untrack` still makes sense.

2024-05-03 21:01 UTC, ErichDonGubler commented
@jimblandy: Weeeell then let's rebase and re-review! 😀

2024-05-03 21:03 UTC, ErichDonGubler approved these changes
Approving contingent on a rebase that we've agreed on,

2024-05-04 04:28 UTC, merged