[wgpu-hal] Upgrade to `glutin` 0.31.3, narrow `libloading` to 0.8
gfx-rs/wgpu pull request #5649
Opened 2024-05-02 18:14 UTC by ErichDonGubler

This eliminates a _ton_ of duplicate dependencies. Woot! Firefox is finally ready for incremental update of `libloading`, so we can make this change without any hassle. 😀

Depends on #5504, to have no dependency on `libloading` 0.7.

2024-05-14 09:58 UTC, cwfitzgerald commented
This can be un-drafted

2024-05-14 20:21 UTC, ErichDonGubler commented
@cwfitzgerald: It seems we need to pick an optional backend feature for `glutin` now (as indicated by CI)? I don't know immediately what the right answer is, tho. 😖

2024-05-15 09:27 UTC, teoxoy commented
They get [automatically enabled](https://github.com/rust-windowing/glutin/blob/052399de0a4a7237b4dc12dd0fcdeb63f1c2af41/glutin/build.rs), the issue is that iOS support [was removed in v0.30](https://github.com/rust-windowing/glutin/blob/052399de0a4a7237b4dc12dd0fcdeb63f1c2af41/CHANGELOG.md?plain=1#L97).

2024-05-15 09:38 UTC, teoxoy commented
What about this? Should we remove it or bump it as well?

https://github.com/gfx-rs/wgpu/blob/77a83fb0dd9f2295f25e99a850b9a031738925c3/Cargo.toml#L154

2024-05-29 17:58 UTC, cwfitzgerald requested changes
For tracking

2024-07-25 12:37 UTC, MarijnS95 commented
@ErichDonGubler what's needed to finish this, port the `raw-gles.rs` example because `glutin` completely removed `winit` from its core and is now a proper wrapper around GL context creation (kind of doing the exact same thing as your `wgl.rs`, `egl.rs` etc)?

I'd love to push this through to further reduce dependencies on `winapi` :)

2024-08-12 13:19 UTC, ErichDonGubler commented
@MarijnS95: Honestly, this just needs somebody to drive it to completion. I'm happy to cede this PR to you, if you have the bandwidth.

2024-08-12 13:21 UTC, MarijnS95 commented
@ErichDonGubler bandwidth is tight, but I've written and worked on my fair share of `glutin` codebases over the years so I might be able to pick this up.

2024-08-18 14:21 UTC, Wumpf commented
https://github.com/gfx-rs/wgpu/pull/5709 highlights that glutin drags in winit right now, making it a holdout for winit 0.27
(dev dependency only still though)

2024-08-27 17:05 UTC, closed without merging