[naga] Implement subgroup quad ops
gfx-rs/wgpu pull request #5684
Opened 2024-05-09 10:21 UTC by valaphee

**Connections**
https://github.com/gfx-rs/wgpu/issues/5555
https://github.com/gfx-rs/wgpu/issues/5670
https://github.com/gpuweb/gpuweb/blob/main/proposals/subgroups.md

**Description**
_Describe what problem this is solving, and how it's solved._

**Testing**
_Explain how this change is tested._

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-05-29 19:23 UTC, cwfitzgerald approved these changes
Approving the (minimal) wgpu side

2024-06-24 14:17 UTC, teoxoy requested changes

2024-06-24 14:17 UTC, teoxoy commented on naga/src/lib.rs
> +    QuadBroadcast(Handle<Expression>),
In the proposal this expression needs to be a constant-expression due to a SPIR-V limitation.

> Before version 1.5, Index must come from a [constant instruction](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#ConstantInstruction).

2024-06-24 14:17 UTC, teoxoy commented on naga/src/back/spv/instructions.rs
> +    pub(super) fn group_non_uniform_quad_broadcast(
This seems to be unused.

2024-09-06 05:06 UTC, JMS55 commented
Any update on this?

2025-01-09 12:06 UTC, teoxoy commented
@valaphee are you still planning to push this forward?

2025-01-11 09:41 UTC, valaphee commented
its a bit outdated, and don't have the time to complete this PR atm

2025-01-13 18:52 UTC, cwfitzgerald commented
Closing for now - please re-open if you (or anyone else) wants to push this forward.

2025-01-13 18:55 UTC, closed without merging