Separate renderpass arc resolve & renderpass consume on end
gfx-rs/wgpu pull request #5794
Opened 2024-06-10 11:39 UTC by Wumpf

**Connections**

* part of #1453
* This is pretty much exactly like a combination of these two PRs, except we're doing it now for render passes!
  * https://github.com/gfx-rs/wgpu/pull/5432
  * https://github.com/gfx-rs/wgpu/pull/5575

**Description**

As before with ComputePass, we now convert all incoming `RenderCommand` first to `ArcRenderCommand` and then consume only those upon pass ending.
Unlike with `ComputePass`, we already had `ArcRenderCommand` around (because of render bundles), I "only" had to fill in the gaps here.

**Testing**
Existing tests pass. Similar to how to compute passes, more are to come for the actual lifetime removal

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-06-10 18:22 UTC, ErichDonGubler commented
I'll take on review for this.

2024-06-23 19:37 UTC, Wumpf commented
@ErichDonGubler bump? :)
Just did a fairly painful rebase after Teo did some great improvements to some error handling and avoidance of arc clone, but naturally it conflicted a lot with this and even more with the follow-up branch I have almost done for a while now.

2024-06-24 16:59 UTC, teoxoy commented
I got some more commits coming in that touch this code so I asked Erich if I can look at this PR to minimize fixing conflicts.

2024-06-24 17:32 UTC, teoxoy requested changes
Left a few comments about the new `DrawKind`. Looks good otherwise!

2024-06-24 17:32 UTC, teoxoy commented on wgpu-core/src/command/bundle.rs
> +                        kind: DrawKind::MultiDrawIndirect,
```suggestion
                        kind: DrawKind::DrawIndirect,
```

since `count` is `None`.

2024-06-24 17:32 UTC, teoxoy commented on wgpu-core/src/command/bundle.rs
> +                        kind: DrawKind::MultiDrawIndirect,
```suggestion
                        kind: DrawKind::DrawIndirect,
```
Same here.

2024-06-24 17:32 UTC, teoxoy commented on wgpu-core/src/command/render.rs
> +                            kind: DrawKind::MultiDrawIndirect,
Here we need to check if count is some or none to assign the draw kind.

2024-06-24 17:32 UTC, teoxoy commented on wgpu-core/src/command/render_command.rs
> +                                    kind: DrawKind::MultiDrawIndirect,
Same here.

2024-06-24 17:43 UTC, Wumpf commented
great catch, thank you!

2024-06-25 07:37 UTC, teoxoy approved these changes

2024-06-25 07:37 UTC, merged