Clean refs to died texture views
gfx-rs/wgpu pull request #5874
Opened 2024-06-25 11:31 UTC by xiaopengli89

**Connections**
Close #5707

**Description**

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-06-25 12:44 UTC, nical requested changes
Nice catch!

Most of the code in life.rs is quite tricky to understand and will hopefully go away in a not-so-distant future. I think that this fix would be easier to understand (and less likely to get accidentally removed along with the resource triaging code) if done just before inserting a view in `Texture::views` in `Global::texture_create_view`.

2024-06-25 14:22 UTC, xiaopengli89 commented
> Nice catch!
> 
> Most of the code in life.rs is quite tricky to understand and will hopefully go away in a not-so-distant future. I think that this fix would be easier to understand (and less likely to get accidentally removed along with the resource triaging code) if done just before inserting a view in `Texture::views` in `Global::texture_create_view`.
> 
> And while you are at it, could you also clean up `Texture::bind_groups` and `Buffer::bind_groups` the same way in `Global::create_bind_group`?

Done.

2024-06-26 08:17 UTC, nical commented
Thanks!

2024-06-26 08:18 UTC, nical approved these changes

2024-06-26 08:18 UTC, merged