Validating sample count based on texture features
gfx-rs/wgpu pull request #5920
Opened 2024-07-07 10:12 UTC by andristarr

**Connections**
#5749 

**Description**
We are validating if the sample count is valid for _any_ texture format.

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-07-07 17:51 UTC, andristarr commented
@ErichDonGubler did you think something along this line?

2024-07-13 14:27 UTC, ErichDonGubler commented
@andristarr: Hey there! Finally getting to this in my personal time. Sorry for the delay. 🙂

> did you think something along this line?

Not quite! You're still checking the features of a single _specified_ format of a single color attachment at a time, with no checking of the depth-stencil attachment. This is redundant with the check immediately below it. The point is to check whether _any_ format could support the multisample count for the render pipeline.

**You will need to iterate over _all_ formats at some point and check whether at least one of them matches.** There are a few (mutually exclusive) approaches that I see for that:

1. Collect all possible sample counts for all texture formats on adapter init. as a `HashSet<u32>`[^1]. Pass this set to a `Device` when created. When creating a `RenderPipeline`, this set gets checked for membership. If the sample count for an attachment is not a member of the set, then reject with a validation error. 
2. Iterate over texture formats to find one that has a potentially matching sample count. If one is found, then proceed with creating the render pipeline. Otherwise, reject with a validation error.
3. Mix (1) and (2) by creating the `HashSet` only when a render pipeline is requested to be built, and check it as with (1).

The only significant difference between these is a trade-off between when work is done, and where that work is stored. **I'd recommend (1), since it should be a pretty small amount of data to add to a device**, while iterating over every texture format sounds pretty compute-intensive to do 3 times with (2). (3) sounds unnecessarily complicated; having variance in the computational load of validation in an API depending on whether you've called it before is a complication I'd rather avoid.

[^1]: We could later (as a separate step) optimize this to be a single-byte bitset, where each bit index corresponds to a power of two. This works because we only support powers of 2 up to 64 (2^8, or 8 bits).

2024-07-13 14:28 UTC, ErichDonGubler requested changes
Requesting changes, as described in my previous comment.

I'm going to convert this back to a draft, since it seems obvious to me that this needs to be reworked.

2024-07-14 11:40 UTC, teoxoy commented
> **You will need to iterate over _all_ formats at some point and check whether at least one of them matches.**

When we previously talked about this I thought the plan was to error if the count is not 1 or 4 if we are in compliance mode (https://github.com/gfx-rs/wgpu/issues/3274) so that we match the spec validation as close as possible.

> Note that we are already validating that multisample counts are compatible with render pipeline attachments, so that the absence of this validation isn't causing us to make invalid requests to wgpu-hal. But adding this validation will certainly improve diagnostics.

Now that I reread the issue, I see the motivation was improving diagnostics but I don't see how adding this validation will improve the diagnostics. The validation error will say "sample count is not valid for any formats" instead of the current "sample count is not valid for format X". The fact that the sample count is not valid for any formats supported by the device doesn't seem relevant in this case since the user supplied a specific format.

> descriptor.[count](https://www.w3.org/TR/webgpu/#dom-gpumultisamplestate-count) must be either 1 or 4.

The reason the validation in the spec is written this way is because all formats in the spec support sample counts of only 1 and 4. Once the spec adds support for the optional sample counts of 2, 8 and 16 (https://github.com/gpuweb/gpuweb/issues/4446) the validation will be changed to what we currently implement.

I suggest we just keep the status quo.

2024-07-18 19:46 UTC, andristarr commented
@ErichDonGubler I am more than happy to do the work laid out by your comment (especially thank you for explaining because I wasn't familiar with the domain!), but I take it @teoxoy 's comment will render this issue obsolete.

Let me know if you want me to do the implementation or just drop the PR.

2024-07-24 17:10 UTC, ErichDonGubler commented
@andristarr: You are right; @teoxoy and I took some time to discuss this, and he's persuaded me that my idea for validation seems too heavyweight for the modest diagnostic improvement. We're now considering <https://github.com/gfx-rs/wgpu/issues/6039> instead, which is not _yet_ implementable. Let's drop this PR.

Sorry for taking your time this way. I think it's an error in our maintainership when somebody (like you) starts work on something that we didn't get consensus on properly, and I apologize for that.

2024-07-24 17:10 UTC, closed without merging