Allow 3D textures to be renderable
gfx-rs/wgpu pull request #6004
Opened 2024-07-20 23:25 UTC by matthew-wong1

**Description**
Hi! The WebGPU spec now allows textures with a 3D dimension to be renderable but the current wgpu implementation only allows for 2D textures to be renderable. I updated the checks to not throw an error if a 3D texture has GPUTextureUsage.RENDER_ATTACHMENT. I couldn't find any open issues or pull requests related to this. Sorry if it might be a work-in-progress or if it was a conscious decision not to enable 3D textures to be renderable yet!

I think the they updated the spec for 3D textures to be renderable around November 2023. 

**Testing**
I ran `cargo xtask test` on an M2 Mac. All tests passed except 3 (the same 3 also failed on the trunk branch of wgpu). 

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-07-21 08:53 UTC, Wumpf requested changes
the change itself is looking good but...
* I think this should be covered by a unit test since there's no way of being sure that our backends actually support this (if any doesn't, we have to emulate this feature by doing copies etc.). I had a quick browse just now and it unforunately doesn't look like there's anything checking on something like that yet.
     * a test creating a renderpass to clear a specific layer of a small volume texture with a "marker color" and then reading back that only that layer has been cleared should be enough
     * bonus points if that test also tests array textures :)
* changelog entry please!

2024-07-21 23:40 UTC, matthew-wong1 commented
Thanks for the feedback! Sorry for overlooking the changelog. 

I've been working on writing the test but I've been a bit slow as I'm still a bit new to Rust and using WebGPU through rust. My understanding is to create a texture view of a particular layer and then pass that into a render pass with a Clear operation, then copy the texture to a buffer and see if that layer is of the color that it was cleared to. 

On another note, I've been weirdly getting an "internal error: entered unreachable code" when creating a texture but am not really sure what the cause is. 
```
use wgpu_test::{gpu_test, GpuTestConfiguration};

const MARKER_COLOR_TO_CHECK: [u8; 4] = [255, 0, 0, 255];
const CLEAR_COLOR: wgpu::Color = wgpu::Color { r: 1.0, g: 0.0, b: 0.0, a: 1.0 };
const SIZE: u32 = 16;
const DEPTH: u32 = 4;
const BYTES_PER_PIXEL: u32 = 4;

#[gpu_test]
static RENDER_3D_TEXTURE: GpuTestConfiguration = GpuTestConfiguration::new().run_async(|ctx| async move {
    let tex = ctx.device.create_texture(&wgpu::TextureDescriptor {
        label: Some("3D texture"),
        size: wgpu::Extent3d {
                width: SIZE,
                height: SIZE,
                depth_or_array_layers: DEPTH
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D3,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT.union(wgpu::TextureUsages::COPY_SRC),
        view_formats: &[],
    });
});
```

Here's the backtrace:
```
thread '<unnamed>' panicked at /Users/matthew/Documents/msc/final_proj/wgpu/wgpu-core/src/device/resource.rs:925:46:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: wgpu_core::device::resource::Device<A>::create_texture
             at /Users/matthew/Documents/msc/final_proj/wgpu/wgpu-core/src/device/resource.rs:925:46
   4: wgpu_core::device::global::<impl wgpu_core::global::Global>::device_create_texture
             at /Users/matthew/Documents/msc/final_proj/wgpu/wgpu-core/src/device/global.rs:473:33
   5: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::device_create_texture
             at /Users/matthew/Documents/msc/final_proj/wgpu/wgpu/src/backend/wgpu_core.rs:1333:27
   6: <T as wgpu::context::DynContext>::device_create_texture
             at /Users/matthew/Documents/msc/final_proj/wgpu/wgpu/src/context.rs:2369:31
   7: wgpu::api::device::Device::create_texture
             at /Users/matthew/Documents/msc/final_proj/wgpu/wgpu/src/api/device.rs:292:13
   8: wgpu_test::render_3d_textures::render_3d_texture_initializer::{{closure}}::{{closure}}
             at ./tests/render_3d_textures.rs:32:15
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/future/future.rs:124:9
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:297:9
  11: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.3.0/src/future.rs:588:42
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  13: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  14: ___rust_try
  15: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  16: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  17: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.3.0/src/future.rs:588:9
  18: wgpu_test::run::execute_test::{{closure}}
             at ./src/run.rs:86:10
  19: wgpu_test::native::NativeTest::from_configuration::{{closure}}
             at ./src/native.rs:56:70
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/future/future.rs:124:9
  21: pollster::block_on
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  22: wgpu_test::native::NativeTest::into_trial::{{closure}}
             at ./src/native.rs:63:13
  23: libtest_mimic::Trial::test::{{closure}}
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libtest-mimic-0.6.1/src/lib.rs:112:54
  24: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  25: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  26: libtest_mimic::run_single::{{closure}}
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libtest-mimic-0.6.1/src/lib.rs:505:43
  27: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  28: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  29: ___rust_try
  30: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  31: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  32: libtest_mimic::run_single
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libtest-mimic-0.6.1/src/lib.rs:505:5
  33: libtest_mimic::run::{{closure}}
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libtest-mimic-0.6.1/src/lib.rs:476:35
  34: <F as threadpool::FnBox>::call_box
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/threadpool-1.8.1/src/lib.rs:95:9
  35: threadpool::spawn_in_pool::{{closure}}
             at /Users/matthew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/threadpool-1.8.1/src/lib.rs:769:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2024-07-21T23:24:44Z ERROR wgpu_test::expectations] Panic: internal error: entered unreachable code
thread '<unnamed>' panicked at tests/src/run.rs:119:9:
tests/tests/render_3d_textures.rs:31:50: test "wgpu_test::render_3d_textures::render_3d_texture" did not behave as expected
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: wgpu_test::run::execute_test::{{closure}}
             at ./src/run.rs:119:9
   3: wgpu_test::native::NativeTest::from_configuration::{{closure}}
             at ./src/native.rs:56:70
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/future/future.rs:124:9
   5: pol [...]

2024-07-22 03:00 UTC, cwfitzgerald commented
> Sorry for overlooking the changelog.

We're pretty bad about it ourselves, so you're in good company 😅

Feel free to come on the matrix to ask any questions if you need help with implementing tbf tests.

2024-07-24 20:40 UTC, matthew-wong1 commented
It seems like the current backend doesn't fully support rendering 3D textures just yet. I probably should've looked a bit closer initially, but based on the WebGPU spec (https://www.w3.org/TR/webgpu/#dom-gpucommandencoder-beginrenderpass) beginning a renderpass with a 3D texture requires a new attribute `colorAttachment.depthSlice` to be included in the renderPassDescriptor. For me, implementing that is a bit out of my depth but I'm happy to help with writing any unit tests along the way. Sorry!

2024-07-24 21:34 UTC, Wumpf commented
Then it's probably best to shelve this for now.
Would you mind creating an issue detailing what needs to be done and what you've learned on the way so far?

2024-07-24 21:34 UTC, closed without merging