[naga] Support pipeline overrides in the WGSL backend
gfx-rs/wgpu pull request #6310
Opened 2024-09-22 22:44 UTC by cbbowen

**Connections**
#4484

**Description**
The WGSL backend currently does not support pipeline overrides (i.e. `override foo: f33`). These are included in the [latest WGSL spec](https://www.w3.org/TR/WGSL/#override-declaration), this PR adds support for them by:
1. Generating appropriate `override` declarations in `wgsl::Writer`.
2. Handling `Override` expressions in `wgsl::Writer`.
3. Handling `Unary` and `Binary` constant expressions in `wgsl::Writer`.

This last step was necessary because the existing "overrides" snapshot test exercises the functionality, but it isn't currently implemented for the WGSL backend.

**Testing**
This first commit in this PR enables the existing "overrides" snapshot tests for the WGSL target which I verified fails. The following commits update the backend such that it passes and generates semantically equivalent WGSL to the input.

Ran:
```
cargo test --all-features
cargo xtask validate wgsl
```

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-09-23 20:27 UTC, cwfitzgerald reviewed
Just to help the naga reviewers: the testing looks good on this PR

2024-09-27 15:00 UTC, ErichDonGubler approved these changes
I feel confident that the behavior intended to be allowed here is correct, but I don't feel confident that we're rejecting improper programs. I'm not very familiar with `override`s to begin with. @jimblandy, could we maybe pair on this, so I can get your thoughts?

2024-10-02 21:00 UTC, ErichDonGubler commented
@jimblandy: I intend to merge this in the next 24 hours, unless you have an objection.

2024-10-02 21:33 UTC, jimblandy requested changes
Rather than adding limited support for some operations to `back::wgsl::writer`, you should just make `write_output_wgsl` in `naga/tests/snapshots.rs` call `naga::back::pipeline_constants::process_overrides`, the way the other `write_output_foo` functions do.

2024-10-02 21:37 UTC, jimblandy requested changes
Going a bit further than my previous comment:

I don't think this PR is the right approach. Naga backends should assume that overrides' values have been provided, and the module has been rewritten so that all overrides appear as constants instead. So rather than the approach taken here, I think the WGSL backend should handle overrides the same way the other backends do:

```rust
        if !module.overrides.is_empty() {
            return Err(Error::Override);
        }
```

As explained in the prior review, it should be the caller's responsibility to call `pipeline_constants::process_overrides` and eliminate all overrides from the module before passing it to the backend.

2024-10-03 02:39 UTC, cbbowen commented
To verify I understand, the intent is that modules with pipeline overrides should not be translated from one language to another? They must instead be substituted with concrete values. That precludes some use cases, including mine, but I can understand not wanting to take on that maintenance burden. If that understanding is correct, I can close this PR.

2024-10-05 19:17 UTC, closed without merging