[naga] Comments parsing
gfx-rs/wgpu pull request #6364
Opened 2024-10-03 15:56 UTC by Vrixyz

**Connections**
None as far as I know.

**Description**
Generating automated documentation à la https://docs.rs is very useful, but currently difficult.

naga lacks information about comments to be too helpful, so this pull requests adds support to parsing those.

Note: I branched off 0.22 because I'm not confident with jumping on the maybe unstable trunk.

**Testing**
Not much for now, I'm compiling a currently private project based on https://github.com/jannik4/shader_docs to attempt to add documentation strings to it.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-10-04 03:28 UTC, jimblandy commented
This doesn't get the comments out of the front end, though, does it?

It seems to me it could be fine to just add a field like:

```rust
    doc_comments: Option<Box<DocComments>>,
```

to `naga::Module`, and then have something like

```rust
struct DocComments {
    types: FastIndexMap<Handle<Type>, Vec<Span>>,
    global_variables: FastIndexMap<Handle<GlobalVariable>, Vec<Span>>,
    ...
}
```

I think it would make sense for Naga to adopt Rust's `///` syntax as a WGSL extension.

2024-10-04 08:02 UTC, Vrixyz commented
> This doesn't get the comments out of the front end, though, does it?

Correct, I'm looking into propagating them to the module now ; my first intuition was to add comments to `naga::TypeInner::Struct` and the likes ; but I fear for performance.

Your idea of a "flat" `DocComments` with an indexmap to Spans is interesting and probably a better idea! Thanks for suggesting. I'll go in that direction.

2025-01-07 22:36 UTC, jimblandy requested changes
Some more comments here.

You'll also need to change `compact::compact` to adjust the type handles, even though only named types can have comments and compaction never removes named types, because compaction may remove anonymous types, and that renumbers the handles.

2025-01-07 22:36 UTC, jimblandy commented on naga/src/lib.rs
> +    pub comments: Comments,
I think this should be an `Option<Box<Comments>>`, so that users who aren't interested in collecting these comments don't need to spend memory on them.

2025-01-07 22:36 UTC, jimblandy commented on naga/src/lib.rs
> +    pub functions: FastIndexMap<String, Vec<String>>,
We usually refer to functions by `Handle<Function>`.

However, for reasons that aren't clear to me, we refer to entry points by index; there's no such thing as a `Handle<EntryPoint>`. So you'll need a separate `FastIndexMap<usize, Vec<String>>` for the entry points.

2025-01-07 22:36 UTC, jimblandy commented on naga/src/front/wgsl/tests.rs
It would be better to add this as a new snapshot test in `naga/tests/in`. You'll need to edit `naga/tests/snapshots.rs` and add the file to the list in `convert_wgsl`.

2025-01-07 22:36 UTC, jimblandy commented on naga/src/lib.rs
> +pub struct Comments {
Please put this above `struct Module`, so that remains the last thing in `lib.rs`.

2025-01-07 22:36 UTC, jimblandy commented on naga/src/valid/handles.rs
> +            ..
Please do not add a `..` here. The reason we're doing this weird whole-struct match thing is exactly to ensure we're not skipping members, and adding `..` would defeat that.

Validation will need to iterate over the keys of the hash tables in `Comments` and ensure that they are all valid handles/indices into their respective arenas, by calling `Self::validate_foo_handle`. This validation could come last.

2025-01-07 22:36 UTC, jimblandy commented on naga/src/front/wgsl/parse/lexer.rs
> +                        let end_position = end_position.0 + 1;
If the comment is terminated by U+0085, U+2028, or U+2029, those characters have multi-byte encodings in UTF-8, so this `... + 1` will produce an invalid character boundary.

2025-01-07 22:48 UTC, jimblandy requested changes

2025-01-07 22:48 UTC, jimblandy commented on naga/src/front/wgsl/parse/lexer.rs
> +                    (Token::Comment(input), &input[input.len() - 1..])
This doesn't look right. Doesn't it just return the last byte of `input` as the following text?

This code is only exercised by `front::wgsl::parse::lexer::test_comments`, which only uses a `//` at the end of the input, so it wouldn't notice if the rest of the text were truncated.

2025-01-08 00:05 UTC, jimblandy requested changes

2025-01-08 00:05 UTC, jimblandy commented on naga/src/front/wgsl/parse/mod.rs
> +        let mut lexer_comments = lexer.clone();
This approach means that we end up re-scanning doc comments unnecessarily. Instead, you should use the `peek` functions to decide when the doc comment ends.

2025-01-08 00:07 UTC, jimblandy commented
> Note: I branched off 0.22 because I'm not confident with jumping on the maybe unstable trunk.

It should be fine to work on `trunk`. This PR should be rebased on that.

2025-01-08 03:33 UTC, jimblandy commented
@Vrixyz Since this isn't passing CI, to make it easier to track stuff I need to review, I'm going to convert this to a draft PR until those issues are sorted out. Feel free to flip it back into non-draft when you're ready.

2025-01-08 10:15 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +        let mut lexer_comments = lexer.clone();
doc comments are actually bypassed because of `start_byte_offset`, which I updated to ignore doc comments.

I updated it to ignore doc comments to avoid side effect breakage, so its behavior is the same as before.

I added a `start_byte_offset_and_aggregate_comment` which is it's counterpart, but aggregates the comments. It is only called when the item encountered can support a doc comment.

while I agree this looks a bit convoluted, scanning comments there would infer to build up a list of comments which we're not sure to use: i.e: In case comments are in the end of the struct, we don't really want to parse them because we wouldn't know where to store them.

We could also only peek next attribute to see if it can support comment, then parse comments, but the end result would be similar. We could avoid a `. clone()`, but a `Lexer.clone()` is quite cheap and the changeset needed to make that work scares me. I'd like to keep it as a follow up.

Let me know if performance analysis could help with the decision.

2025-01-09 08:29 UTC, ThierryBerger commented on naga/src/lib.rs
> +    pub comments: Comments,
I did the change ; we could also add a feature for that ?

2025-01-09 10:27 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +        let mut lexer_comments = lexer.clone();
Moreover, current implementation is wrong because the span is incorrect, cleaning up this feedback should help me fix it :crossed_fingers:

2025-01-09 10:36 UTC, Vrixyz commented
I rebased on trunk, tests are encouraging, there's a major bug I'm investigating still: span are incorrect.

:question: I'm curious about "pushing rules": I imagine parsing should contain a rule for parsing comments ? so we push that rule when checking for comments.

2025-01-09 13:31 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
>          let start = lexer.start_byte_offset();
`start` should be computed before calling `lexer.next();`.

2025-01-10 04:32 UTC, jimblandy commented on naga/src/front/wgsl/parse/mod.rs
> +        let mut lexer_comments = lexer.clone();
The idea is, it should be cleaner to look at the next token to decide when the series of doc comments ends. This is the way the parser hands other kinds of lists that are terminated by something that has meaning beyond simply being a terminator.

I doubt it has much of an observable performance impact. But I feel that --- to a limited extent --- code that does redundant work is more confusing, because the reader will not generally expecting the redundancy. For example, they might be surprised by the way the state is rewound many tokens before the current point of attention. But I concede that arguments based on "what people expect" are hard to judge; if one isn't persuaded, one simply isn't persuaded.

Implementing `peek` by cloning the `Lexer` made more sense when the `Lexer` was nothing more than two `&str` fields. But it's starting to get a little heavier, and I think that implementation might not be ideal any more. Many parsers use a peek operation, but it's usually done by having an `Option<Token>` field somewhere that you just save the next token in.

2025-01-10 09:42 UTC, Vrixyz commented on naga/src/valid/handles.rs
> +                    }
This

2025-01-10 10:15 UTC, Vrixyz commented on naga/src/lib.rs
> +    pub functions: FastIndexMap<String, Vec<String>>,
Thanks, I did the change, that's better this way!

2025-01-10 21:58 UTC, jimblandy commented
> ❓ I'm curious about "pushing rules": I imagine parsing should contain a rule for parsing comments ? so we push that rule when checking for comments.

You mean `Parser::rules`? You shouldn't need to worry about that at all. You should just call `start_byte_offset` and `span_from` directly.

The rule stack is currently being used as a rough approximation to WGSL's [template list discovery](https://gpuweb.github.io/gpuweb/wgsl/#template-list-discovery), which you definitely do not want to get tangled up with, and which shouldn't affect your work at all. And it's used for some sanity checks.

2025-02-20 20:57 UTC, jimblandy commented
I rebased this on trunk (7e42040fa, 2025-2-19).

2025-02-20 21:13 UTC, jimblandy commented on naga/src/front/wgsl/parse/mod.rs
> +        let mut lexer_comments = lexer.clone();
Okay, I think I understand a little better now what the original intention was. Under the assumption that cloning a lexer is cheap, you're simply *noting* where doc comments *would* begin, and then only actually recording them in the module if you later decide that you've started to parses something that can accept doc comments. This makes more sense.

2025-02-20 21:19 UTC, jimblandy commented on naga/src/lib.rs
> +    pub comments: Comments,
Maybe I didn't really say what I meant:

I think users should be able to choose to collect or ignore comments at run time. That is, `naga::front::wgsl::FrontEnd::new` should take an `Options` type, or `FrontEnd` should have a `new_with_comments` constructor - or whatever, something boring but tasteful - and then parsing should return a `Module` whose `comments` field is either populated or not.

2025-02-20 22:08 UTC, jimblandy submitted a review, later dismissed
This is getting there.

- Can we record comments as Spans instead of Strings?

- Users should be able to choose at runtime whether to collect comments or not, as I explain here: https://github.com/gfx-rs/wgpu/pull/6364#discussion_r1964353109

- The CI failures will need to be addressed. I saw some Clippy style concerns.

2025-02-20 22:08 UTC, jimblandy commented on naga/src/lib.rs
> +    }
It's valuable to frequent contributors to keep `Module`'s definition as the last thing in this file. I think once you make comment collection selectable at runtime this is going to change anyway, but if it sticks around let's put it someplace else -  `naga/src/front/mod.rs`, perhaps.

2025-02-20 22:08 UTC, jimblandy commented on naga/src/compact/mod.rs
> +        for comment_type_handle in comment_types.keys().cloned().collect::<Vec<_>>() {
I think in general we should be able to `std::mem::take` the `IndexMap`, and then do an owning iteration (just 'for (key, value) in map { ... }`) and check, adjust, and reinsert the values. This should be simpler than `swap_remove`.

2025-02-21 09:25 UTC, Vrixyz commented on naga/src/compact/mod.rs
> +        for comment_type_handle in comment_types.keys().cloned().collect::<Vec<_>>() {
Thanks! I adressed this in 684e7e46c

2025-02-21 13:30 UTC, Vrixyz commented on naga/src/lib.rs
> +    pub comments: Comments,
Thanks ! I addressed this in 57865be9495fbcfaf0f3969309253b83afdfdb4e ; I'm open to suggestions about the implementation.

I updated a few tests to test both options.

2025-02-21 13:47 UTC, Vrixyz commented on naga/src/lib.rs
> +    }
Ok, I'll trust your judgement here: 953d8fb49741479a7f39922c2e33cd0a4479b5fd

2025-02-21 17:35 UTC, jimblandy commented on naga/src/front/wgsl/parse/mod.rs
> +impl ParserOptions {
This should just be named `Options`; the fact that it's from `naga::front::wgsl` makes it clear that it contains parsing options.

Rather than having a `new` method, `Options` structs should implement `Default`.

2025-02-21 17:56 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +impl ParserOptions {
Good point about prefix being redundant 👍

I can implement default, but it's not const so this was complaining from an existing caller.

2025-02-21 21:06 UTC, Vrixyz commented
>     * Can we record comments as Spans instead of Strings?

I don't think we can or should.

I consider comments quite similare to [`Ident`](https://github.com/Vrixyz/wgpu/blob/d0299b65c3c72d2b18211e31ef02c3c9b738c736/naga/src/front/wgsl/parse/ast.rs#L48), where it could be any values, currently `Ident` is stored with a `name: &str` and a `Span`. Retrieving that `&str` from the original source + `Span` doesn't seem a used practice (and I'm not sure even feasible), so I opted for keeping it consistent.

What I could do is add the `Span` alongside the comment contents. I'm not sure what is the advantage of that though: I had the impression that that span was used mostly for error reporting, which would not occur on comment parsing (?), or mayyybe an internal error around https://github.com/Vrixyz/wgpu/blob/d0299b65c3c72d2b18211e31ef02c3c9b738c736/naga/src/valid/handles.rs#L284.

Another use case for a span for comments would be to make a tool to parse a wgsl then remove comments only, or link to comment source.

Let me know if "adding" that span (opposed to replacing `&str`)  in the comments is needed to make this PR progress.

If I'm wrong, I'm happy to be corrected, thanks again for your diligent reviews!

2025-02-24 16:30 UTC, jimblandy commented
@Vrixyz In Rust, only comments starting with `///` or `/**` are considered to be doc comments, and others are just ordinary comments. The syntax you've chosen doesn't make any distinction between the two. What are your thoughts about Rust's design? Would it be appropriate for WGSL?

2025-02-24 16:51 UTC, Vrixyz commented
> What are your thoughts about Rust's design? Would it be appropriate for WGSL?

@jimblandy personally I'd advocate for mimicking Rust's syntax rules, and I'd be ok with implementing it :+1: (i.e ignore comments not starting by `///` or `/**`).

But I chose to parse every comment because [wgsl spec](https://www.w3.org/TR/WGSL/#comments) doesn't acknowledge "comment docs", as all comments are considering documentation.

That being said, I didn't quite follow my objective, because I didn't succeed in implementing module comments without adding a specific syntax: `//!`, which is similar to rust's syntax.

I made this decision because it made things simpler when working with `naga_oil` when multiple files are stitched together.

2025-02-24 18:07 UTC, jimblandy commented
@Vrixyz Let's go with the Rust syntax. Can we take care of it in this PR?

2025-02-24 18:36 UTC, jimblandy commented
> > ```
> > * Can we record comments as Spans instead of Strings?
> > ```
> 
> I don't think we can or should.

Okay, this is fine. We can revisit this question in the future if necessary.

2025-02-24 18:38 UTC, jimblandy commented on naga/src/front/wgsl/parse/mod.rs
> +impl ParserOptions {
Sometimes we've marked functions as `const` just because Clippy complained, and not because we actually wanted to use that function in a constant context. So if the fix is simply removing `const` from `const fn`s, that's probably fine.

2025-02-25 09:45 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +impl ParserOptions {
Thanks for that information.

I don't think `const` was added without reason here, it goes back to https://github.com/gfx-rs/wgpu/commit/6035b07b786135f65cb4140f99cf67cc0381b4c3#diff-46894d640690ef35dff3deaf0bb5416be6e4d00eaba890e3181628d769f6f413R1735 ; and the commit message has a `Fixes https://github.com/gfx-rs/wgpu/pull/2071: Global item does not support 'const'`.

I'd prefer to keep this PR as close to existing code as possible.

2025-02-25 09:51 UTC, Vrixyz commented
> 386ed0d

I did that in [9cb6d53](https://github.com/gfx-rs/wgpu/pull/6364/commits/9cb6d53334c0eee160feb2b20bf38d55f47fcb0b) 👍

2025-04-11 11:27 UTC, teoxoy requested changes

2025-04-11 11:27 UTC, teoxoy commented on naga/src/front/wgsl/parse/lexer.rs
> +                self.input = rest;
Should it be valid to have these items in-between the doc comment and the item itself? It seems odd to me.

2025-04-11 11:27 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +                .collect();
We don't seem to ever use the return type of `start_byte_offset_and_aggregate_comment`, could you rename it to something like `accumulate_doc_comments` that returns the `Vec<&str>` directly?

2025-04-11 11:27 UTC, teoxoy commented on naga/src/front/wgsl/parse/lexer.rs
> +                        let mut peeker = char_indices.clone().peekable();
We can make `char_indices` `peekable`, avoiding the `clone`.

2025-04-11 11:27 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +            let mut lexer_comments = lexer.clone();
We can then just call `accumulate_doc_comments` here instead.

2025-04-11 11:27 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +                comments.push(lexer.source.index(span));
Doesn't `Token::CommentDocModule(_)` already contain the `&str`?

2025-04-11 11:27 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +            while let (Token::CommentDocModule(_), span) = peek_any_next(&lexer) {
We could add a `next_if` method on the lexer for this, making the code easier to look at.

2025-04-11 11:27 UTC, teoxoy commented on naga/src/front/wgsl/lower/mod.rs
> +                                        f.comments.iter().map(|s| s.to_string()).collect(),
I'm not sure how the doc comments will be consumed but wouldn't it make sense if they didn't contain the `///`, `//!` (and so on) inside? We could then concatenate them so that each item has a single `String` as its doc comment.

2025-04-11 11:29 UTC, teoxoy commented
The overall approach looks good, I mainly left some comments that I think would improve the impl and a one last question about usage.

2025-04-17 13:45 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +            let mut lexer_comments = lexer.clone();
The reason I went this route was because not all items should support comments, so if we try to accumulate on everything, there'd be a `Vec` instantiated to store the result, then we realize we don't need it, so we drop it. I suspect this would impact performance, but I didn't measure it.

2025-04-17 14:19 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +                comments.push(lexer.source.index(span));
Correct! as I'm peeking I can't use it though because the borrow checker is unhappy, I think I have to make a `next_module_comment` function for the lexer.

2025-04-17 14:25 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +            let mut lexer_comments = lexer.clone();
Empty `Vec`s don't allocate so I don't think it should be a problem.

2025-04-17 14:42 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +                comments.push(lexer.source.index(span));
Actually, it's not 100% trivial, changing this would either:

- require a `peek` before, then getting the comment if relevant.
- or use an `accumulate_comments` for module docs, then backtracking to get the last token which resulted in leaving that `accumulate_comments`.
- change `accumulate_comment` implementation to return the last `(token, rest)`.

2025-04-17 14:47 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +            let mut lexer_comments = lexer.clone();
`accumulate_doc_comments` leaves the lexer in a "bad" state though, where it consumes an item "too much" in order to know it's stopped. I could change this behaviour to `peek` before consuming, or return the latest consumed item (which is not a comment) for further parsing :thinking:

2025-04-17 15:27 UTC, Vrixyz commented on naga/src/front/wgsl/parse/lexer.rs
> +                        let mut peeker = char_indices.clone().peekable();
`char_indices` is actually an iterator (from rustlib), so the clone is not expensive. We could make the api more ergonomic but ultimately I think that would lead to the same generated code.

2025-04-17 15:28 UTC, ThierryBerger commented on naga/src/front/wgsl/parse/lexer.rs
> +                self.input = rest;
you're probably right, I thought it wouldn't hurt to not fail, but rust does indeed raise an error if a module comment is at the wrong place. I can do that.

2025-04-17 15:28 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +                .collect();
thanks, done

2025-04-17 15:33 UTC, Vrixyz commented on naga/src/front/wgsl/lower/mod.rs
> +                                        f.comments.iter().map(|s| s.to_string()).collect(),
I have no strong feelings about it, but I took the most "conservative" and unopiniated approach.

Some comments look like 
```rs
////////
// SOME HEADING
////////
```

or sometimes ascii art is in comments, and messing up with what user wrote may be surprising, so I kept it.

Oh and also, there are edge cases between `// comment` and `//comment` which could lead to unwanted space at the beginning, or we should take the most indented... cases add up fast and start to be opinionated quickly.

2025-04-25 10:20 UTC, teoxoy commented on naga/src/front/wgsl/parse/lexer.rs
> +                self.input = rest;
What about `Token::Trivia` (comments) does rust allow those in-between doc comments?

2025-04-25 10:27 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +            let mut lexer_comments = lexer.clone();
`accumulate_doc_item_comments` doesn't set `self.input = rest` when it encounters a token it can't consume and so it won't advance the tokenizer.

2025-04-25 10:28 UTC, teoxoy commented on naga/src/front/wgsl/lower/mod.rs
> +                                        f.comments.iter().map(|s| s.to_string()).collect(),
Ok, we can change this later if needed.

2025-04-25 10:48 UTC, teoxoy commented on naga/src/front/wgsl/parse/lexer.rs
> +                        let mut peeker = char_indices.clone().peekable();
That's fair, I should have mentioned my main concern was about readability as it took me a while to figure out what the code was doing, though I realize making `char_indices` `peekable` doesn't improve the flow much.

2025-04-25 10:48 UTC, teoxoy commented on naga/src/front/wgsl/parse/lexer.rs
> +                        let mut peeker = char_indices.clone().peekable();
Actually, we are already cloning the iterator, we shouldn't need to make it peekable at all, we can just call next on it.

2025-04-25 12:27 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +                comments.push(lexer.source.index(span));
A similar method to `accumulate_doc_item_comments` would work and we wouldn't need to backtrack.

2025-06-05 11:33 UTC, teoxoy commented
I squashed the commits (since there were too many commits to rebase individually), rebased the PR and made some more modifications.

@Vrixyz let me know if the PR looks good, if so I think we can land it

2025-06-05 12:22 UTC, Vrixyz commented on naga/src/front/wgsl/parse/mod.rs
> +        let doc_comments = lexer.accumulate_doc_comments();
This approach is interesting, as we could use it to emit warning when doc comments are encountered when it shouldn't have been: check that `doc_comments` is empty for items that don't support it (separator, word...).

I'd consider this for another PR though, as it will lead to questions about error reporting, etc...

2025-06-05 12:25 UTC, Vrixyz commented
Thanks @teoxoy for championing it! Looks great to me.

2025-06-05 13:11 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +        let doc_comments = lexer.accumulate_doc_comments();
Yeah, it would be nice to warn/error in these cases, through we need to make sure to only do so based on a setting or else this would make naga not spec compliant.

2025-06-05 13:11 UTC, teoxoy commented on naga/src/front/wgsl/parse/mod.rs
> +        let doc_comments = lexer.accumulate_doc_comments();
I guess we could just do it based on `options.parse_doc_comments`.

2025-06-05 13:12 UTC, teoxoy approved these changes

2025-06-05 13:13 UTC, merged

2026-01-09 17:45 UTC, jimblandy commented
@ThierryBerger I'm just curious - what is this math? It appears in a test case for the doc comment parsing in `naga/src/front/wgsl/parse/lexer.rs`:

```
#[test]
fn test_doc_comment_long_character() {
    sub_test_with_and_without_doc_comments(
        "/// π/2
        ///     D(𝐡) = ───────────────────────────────────────────────────
///            παₜα_b((𝐡 ⋅ 𝐭)² / αₜ²) + (𝐡 ⋅ 𝐛)² / α_b² +`
    const a : i32 = 2;",
```

2026-01-09 19:18 UTC, ThierryBerger commented
@jimblandy most likely coming from bevy, such as https://github.com/bevyengine/bevy/blob/main/crates/bevy_pbr/src/render/pbr_lighting.wgsl#L154 ; they are isolated snippets which caused ~~tests~~ lexer to fail at some point where I was probably incorrectly handling characters with multiple bytes.

For the exact meaning of the math I won't be able to explain it but hopefully the context is enough breadcrumbs to follow :)