Idx buf bounds check
gfx-rs/wgpu pull request #6493
Opened 2024-11-04 19:21 UTC by ErichDonGubler

**Connections**

Exercised by `webgpu:api,validation,encoding,cmds,render,setIndexBuffer:offset_and_size_oob:*`, which was disovered to be failing in Firefox in [this `webgpu-backlog1` run on a Windows debug build in `try:bed05e732fb557b6173872c508612399b6bc365e`](https://treeherder.mozilla.org/jobs?repo=try&tier=1%2C2%2C3&author=egubler%40mozilla.com&selectedTaskRun=enQluY6MT36HfWG8-NnjAw.0).

**Description**

`wgpu` implemented OOB checks on `BufferSlice` creation as a panic. However, it _should_ be implemented as a validation check in `wgpu-core`. So _fix it_. 😀

**Testing**

- Exercised by `webgpu:api,validation,encoding,cmds,render,setIndexBuffer:offset_and_size_oob:*` in Firefox.

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-11-05 13:51 UTC, teoxoy requested changes
The validation we are removing (which was recently added in https://github.com/gfx-rs/wgpu/pull/6432) applies in more cases than `RenderPass::set_index_buffer`. It also applied to:
- `set_index_buffer` on the render bundle encoder
- `set_vertex_buffer` on the render pass encoder & render bundle encoder
- `map_async` on the buffer

Looking at the spec as well, having it in these places seems correct.

2024-11-06 10:23 UTC, Wumpf commented
To build upon that: `slice` specifically is a rust artifact and the validation done there is a rusty one just like slice on a vec validates.
Validating to consume a given `BufferSlice` in wgpu-core is another story.

On that note: the fields of `BufferSlice` should probably be just pub (which then again very much puts the spot light on the validation on wgpu-core which is needed for WebGPU compliance anyways). I remember another ticket somewhere that was struggling with this. `BufferSlice` itself is also just a rust artifact - in the WebGPU api this is handled with loose size & offset fields

2024-11-07 13:22 UTC, ErichDonGubler commented
@teoxoy: Ah, right, I need to ensure that there's coverage for those methods, too. Will do that.

- [ ] Do it

2024-11-07 13:23 UTC, ErichDonGubler commented
@Wumpf (CC @teoxoy): This is actually an interesting tension between typical Rust programming and the experience dictated by the WebGPU spec. The spec. specifies that this sort of error is a _validation error_; so, still safe, but we don't get a panic at the site of usage. I think this is for `wgpu` devs. to decide on, and honestly...maybe I should just punt the removal of the panicking for another issue/PR.

2025-11-25 01:54 UTC, ErichDonGubler commented
Made obsolete by #7911 and its ilk.

2025-11-25 01:54 UTC, closed without merging