nada: Add support for GLSL signed/unsigned samplers
gfx-rs/wgpu pull request #6513
Opened 2024-11-10 17:28 UTC by DavidPeicho

**Description**

Add support for `usampler*` and `isampler` for GLSL input. Example of valid input:

```glsl
#version 440 core

layout(set = 0, binding = 0) uniform utexture2D tex;
layout(set = 0, binding = 1) uniform sampler samp;

layout(local_size_x = 8, local_size_y = 8) in;
void
main()
{
  vec4 data = vec4(texture(usampler2D(tex, samp), vec2(0.0, 1.0)));
}
```

**Testing**

Updated the test `samplers.frag`.

**Checklist**

- [X] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [X] Run `cargo clippy`.
- [X] Run `cargo xtask test` to run tests.
- [X] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-11-12 09:47 UTC, DavidPeicho commented on naga/src/front/glsl/builtins.rs
> +    let sampler_info = if name.starts_with("sampler") {
I am not really opinionated about how you prefer to fix it. Could also check for `sampler` on `&name[1..]` instead, and check the first char then.

2024-11-12 11:31 UTC, teoxoy requested changes

2024-11-12 11:31 UTC, teoxoy commented on naga/src/front/glsl/builtins.rs
> +            | "samplerCubeArrayShadow" => {
These don't have integer versions. We should probably match on `sampler_info`.

2024-11-12 17:35 UTC, DavidPeicho commented on naga/src/front/glsl/builtins.rs
> +            | "samplerCubeArrayShadow" => {
Or I guess just move them into the original match over `name`?

2024-11-12 17:36 UTC, teoxoy commented on naga/src/front/glsl/builtins.rs
> +            | "samplerCubeArrayShadow" => {
Sure.

2024-11-13 19:21 UTC, DavidPeicho commented on naga/src/front/glsl/builtins.rs
> +            | "samplerCubeArrayShadow" => {
Done, should we add some failing test check for unsigned/signed shadow samplers or? There are no failing/output error check tests I think for glsl yet

2024-11-15 10:49 UTC, teoxoy approved these changes
Thanks!

2024-11-15 10:49 UTC, merged