Static linking for DXC via mach-dxcompiler
gfx-rs/wgpu pull request #6574
Opened 2024-11-21 03:17 UTC by DouglasDwyer

**Connections**
- [[Experiment]: bundled with dxc (as a feature?)](https://github.com/gfx-rs/wgpu/issues/6499)
- [Make DX12 the Default API on Windows](https://github.com/gfx-rs/wgpu/issues/2719)

**Description**
This PR adds support for statically linking the DXC binaries from [`mach-dxcompiler`](https://github.com/hexops/mach-dxcompiler). The `mach-dxcompiler` repo replaces Microsoft's DXC build system with Zig, which allows for building DXC as a static `.lib` file. I have created an upstream crate called [`mach-dxcompiler-rs`](https://crates.io/crates/mach-dxcompiler-rs) that handles downloading a prebuilt `mach-dxcompiler` binary and linking it into a Rust project (ideally, it would be built from source, but that was too complicated for my purposes - it can be added later if desired).

This PR adds a dependency on `mach-dxcompiler-rs`, gated behind the `mach-dxcompiler-rs` feature flag. When enabled, it allows for specifying `dx12_shader_compiler: Dx12Compiler::MachDxc` in the `InstanceDescriptor`. **This allows for using DXC in WGPU without having to ship any external `.dll`s alongside the main binary.**

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-11-22 14:35 UTC, DouglasDwyer commented
Update on the current state of this PR:

The branch builds and I am able to successfully use static DXC in my own WGPU project on `windows-msvc`. However, the Windows WGPU unit tests don't compile due to a linking error: the `mach-dxcompiler` lib is built with `MT_StaticRelease` whereas another native library referenced by WGPU ([`nv-flip-sys`](https://crates.io/crates/nv-flip-sys)) is built with `MD_DynamicRelease`. In general, I believe that this would be an error for any consumers of WGPU + Mach DXC that also dynamically link MSVCRT from other native libs.

From what I gather, the correct solution here is to offer both an `MD_DynamicRelease` and `MT_StaticRelease` binary for the the `mach-dxcompiler` Windows target. I played with the Zig build system for about four hours yesterday, and was unable to figure out how to emit a `.lib` file that dynamically links MSVCRT. [It looks to me like the choice between static/dynamic CRT is hardcoded in the Zig build system, and is tied directly to whether you are building a `.lib` or `.dll`.](https://github.com/ziglang/zig/blob/f845fa04a0dce3104efe129c73a6ad792b1712b6/src/link/Coff.zig#L2087-L2090)

I will be asking around on the Zig forums (and maybe opening an issue on Zig's GitHub) about this. In the meantime, I will leave this PR open. If anyone has additional guidance or suggestions for how we can push this PR forward, I would be grateful. Otherwise, this PR is stagnant until we find a way to build static libs with `MD_DynamicRelease` using Zig.

2024-11-22 22:21 UTC, DouglasDwyer commented
Well, after a good deal of more foraging, I managed to find the compiler flag that I was looking for: Zig accepts `-fms-runtime-lib=dll` to use the dynamic MSVCRT, just like Clang. With this, I was able to fix the linking issues and update `mach-dxcompiler-rs` to support either static/dynamic MSVCRT. All tests now pass and I am able to build/run WGPU + Mach DX12 in my own project. This PR should be ready for review.

2024-11-24 04:36 UTC, Elabajaba commented
I'm just curious, do you know if `mach-dxcompiler` is keeping up to date with DXC? From what I remember from the original blog post they didn't plan to try to track upstream at the time, but there's been some big features added in shader model 6.8 (workgraphs being the obvious headliner, but `SV_StartVertex/InstanceLocation` is also really nice especially for simplifying GPU driven rendering pipelines.

2024-11-24 14:38 UTC, DouglasDwyer commented
@Elabajaba, that's a great question. The DXC branch that's actually being built is [here](https://github.com/hexops/DirectXShaderCompiler) - it hasn't been updated in about a year, so it doesn't support SM 6.8 at this time. In theory it should be possible to update it to latest, but I took a look and there are merge conflicts with DXC master. I don't know how easy it would be.

2024-11-27 11:28 UTC, teoxoy commented
I saw that [`mach-dxcompiler`](https://github.com/hexops/mach-dxcompiler) signs the blob but I don't know if that works if we pass it `DXC_ARG_SKIP_VALIDATION` (which we currently do). We should probably remove the flag if the `validator` is `None`.

2024-11-27 11:29 UTC, teoxoy commented
Other than that, this looks good to me, @cwfitzgerald what do you think?

2024-11-27 11:30 UTC, teoxoy commented
If we get this in we can probably close https://github.com/gfx-rs/wgpu/issues/4155.

2024-12-01 22:07 UTC, cwfitzgerald requested changes
Broadly looks good, some notes.

2024-12-01 22:07 UTC, cwfitzgerald commented on wgpu/Cargo.toml
> +
Could we move this to its own section for "external libraries" and explain a little more why we might want to use this? I should be able to fully answer why I might care by looking at this.

2024-12-01 22:07 UTC, cwfitzgerald commented on wgpu-types/src/lib.rs
> +    MachDxc,
I would call this StaticDxc, and maybe rename the other one DynamicDxc. The user doesn't much care about where it comes from, just that it's a statically linked version of DXC.

2024-12-01 22:07 UTC, cwfitzgerald commented on wgpu/Cargo.toml
> +
Similarly here, I would recommend naming the feature `static-dxc`.

2024-12-02 03:37 UTC, cwfitzgerald approved these changes
Great stuff, one last nit, then let's land!

2024-12-02 03:37 UTC, cwfitzgerald commented on wgpu/src/util/init.rs
> +            Ok("dxc") => wgt::Dx12Compiler::DynamicDxc {
One last nit, could there be a branch here for "static-dxc" - you can leave this branch as-is.

I think you'll need to update the Readme too.

2024-12-02 04:14 UTC, merged