Add visionos support
gfx-rs/wgpu pull request #6611
Opened 2024-11-25 07:22 UTC by guusw

Add build support for VisionOS by adding the required feature checks. Note that vision is almost identical to iOS, except that the rust team decided to add a unique os feature "visionos"

Alternatives could be to check something like `#[all(target_vendor = "apple", not(target_os = "macos"))]`
to simplify all mobile devices, excluding desktop macos, let me know.

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
  - [x] `--target wasm32-unknown-emscripten`
- [x] Run `cargo xtask test` to run tests.
- [x] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-11-25 09:03 UTC, nical approved these changes

2024-11-25 09:07 UTC, nical commented
A few cosmetic adjustments are needed to pass CI.

2024-11-25 16:02 UTC, ErichDonGubler requested changes
The question of `cargo fmt` notwithstanding (@guusw: I wasn't able to push to this PR; did you check the checkbox to let maintainers edit this PR?), this sounds like a difficult PR to merge because of its dependencies. The OP's suggestions:

> I'm not sure what the preferred solution here would be:
> 
> * Using a patched crate vendored under gfx-rs org git url?
> * Using a vendored copy of objc?

…don't work for publishing to Crates.io (viz., `cargo publish` invocations will be blocked by validation that dependencies are also Crates.io crates). Unless we can get upstream to publish a new version with the PR that this is based on, I think we might have to rebase this on top of #5641, or use the alternative also in the OP: 

> Alternatives could be to check something like `#[all(target_vendor = "apple", not(target_os = "macos"))]`  
> to simplify all mobile devices, excluding desktop macos, let me know.

2024-11-25 17:44 UTC, nical commented
> I think we might have to rebase this on top of https://github.com/gfx-rs/wgpu/pull/5641

It seems to me that getting the `cfg` part to work and using a version of obj-c that supports the VisionOS are orthogonal, so I don't expect a rebase to be needed before merging this.

That said, looks like using `target_vendor = "apple"` might be cleaner than enumerating all of the apple devices to decide when to use metal. In most places we don't appear to differentiate between desktop and mobile.

2024-11-25 17:48 UTC, teoxoy commented
It's worth noting that not all apple OSes support Metal.

2024-11-27 02:11 UTC, crowlKats reviewed
Deno has no opinion on this change and is fine with the cargo.toml addition

2024-11-27 10:16 UTC, nical commented
After some discussions on the matrix chat we concluded that we want to list the targets the way this PR does it. So once the CI errors are fixed, this should be good to land.

2024-12-11 16:50 UTC, jimblandy commented
@guusw Could you look into the CI failures? These are MacOS failures so they do seem relevant.

2024-12-11 16:51 UTC, nical commented
Ping from triage. This PR has some CI failures that have to be fixed before it can be merged (but the approach looks good).

2024-12-17 01:33 UTC, madsmtm reviewed
Up to you of course, but I'd recommend `#[cfg(target_vendor = "apple")]` for all Metal stuff as that also includes tvOS (and any future OS Apple might release), `#[cfg(all(target_vendor = "apple", not(target_os = "macos")))]` for the places where you need to single out UIKit-specific stuff, and `#[cfg(target_os = "ios")]` for truly iOS-specific stuff.

And sure sure, `#[cfg(target_vendor = ...)]` [might be deprecated one day](https://github.com/rust-lang/rust/issues/100343), but not before a suitable alternative such as `#[cfg(target_family = "darwin")]` is introduced.

If you really want, you could add something like the following to explicitly say that things won't compile on watchOS:
```rust
#[cfg(target_os = "watch")]
compile_error!("Metal, and by extension WGPU, does not work on watchOS");
```

2024-12-17 08:39 UTC, teoxoy commented
I don't know what happens if you try to compile wgpu for watchos (it will probably work buy fail at runtime) but given that we already have cfg aliases I don't see why we shouldn't list the ones we explicitly want to support there.

2024-12-17 20:23 UTC, cwfitzgerald commented
With apple's propensity to make new operating systems, I am inclined to just fully bucket it - just so don't have to maintain the list

2025-01-09 18:52 UTC, closed without merging

2025-01-09 18:52 UTC, cwfitzgerald commented
Closing in favor of #6888