Init CustomContext and Dyn_
gfx-rs/wgpu pull request #6658
Opened 2024-12-04 19:50 UTC by sagudev

**Connections**
Based on https://github.com/gfx-rs/wgpu/pull/6619, fixes https://github.com/gfx-rs/wgpu/issues/6330

**Description**
_Describe what problem this is solving, and how it's solved._

**Testing**
TODO: Passing wgpu-core as dyn and dummy

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-12-05 05:52 UTC, sagudev commented
TBH, I have no idea what's wrong with WASM.

2024-12-06 08:47 UTC, sagudev commented on wgpu/src/api/instance.rs
> +    }
This is triggering visibility problems for WASM, but I do not know why.

2024-12-11 07:27 UTC, cwfitzgerald commented
Ping me if this needs looking at or you need help before it is out of draft, going to un-assign myself for bookeeeping

2025-01-08 17:57 UTC, sagudev commented
In https://github.com/gfx-rs/wgpu/pull/6658/commits/79ecded9fa0f5a20fb470e6a9c27caf0fa284a63 I removed InterfaceTypes trait as it's not really needed anymore (this makes writing Custom/Dyn wrappers easier as they do not need to impl traits directly, avoiding a lot of boilerplate), all bounds are actually enforced in `dispatch_types_inner` anyway. The only useful application was making writing macros easier, but I replaced this with `mod interface_types` that has aliases for interface types (there is a lot of this pattern in servo as it was used before associate trait types), but we could also just write more stuff in macro and remove the completely. Does approach like this sounds reasonable @cwfitzgerald? I would be willing to split this into separate PR if it's ok.

2025-01-08 19:44 UTC, cwfitzgerald commented
Hmm... I don't love it as it makes things less structured, but can't see a strong argument against it. Will fully consider it when I review this. You can leave it as part of this PR for now.

2025-01-09 06:47 UTC, sagudev commented
I have alternative approach in https://github.com/sagudev/wgpu/commit/ce582808f273a18d9816d5c6e455ff0975e8b02c which keeps the trait but instead of using interfaces in bounds it uses `Dispatch<Target = dyn Interface>` in bounds (clone of Deref trait, but I did use Deref directly to avoid compiler magic as it makes bounds less explicit esp between Dispatch and DispatchMut). One thing to consider here is that implementations of custom context will need to provide all types, even those that are not needed (ex. if one does not need/use compute pass). Should I switch to this approach @cwfitzgerald?

2025-01-09 15:49 UTC, cwfitzgerald commented
> I have alternative approach in https://github.com/sagudev/wgpu/commit/ce582808f273a18d9816d5c6e455ff0975e8b02c which keeps the trait but instead of using interfaces in bounds it uses Dispatch<Target = dyn Interface> (clone of Deref trait, I avoid Deref to avoid compiler magic as it makes bounds less explicit esp between Dispatch and DispatchMut).

I'm going to leave this up to your own judgement which is cleaner and more parsable, my initial impression is that the mod { type } approach is less infrastructure and less confusing than adding the Dispatch one

2025-01-29 21:21 UTC, sagudev commented
@cwfitzgerald I think this is ready for concept review, it still needs more docs and maybe some polish 💅🏾.

2025-01-29 21:39 UTC, cwfitzgerald commented
Nice! I'm going to take this out of draft for bookkeeping

2025-02-13 01:44 UTC, cwfitzgerald requested changes
Don't love the whole new `type` alias thing, but don't really hate it enough to say no

2025-02-13 01:44 UTC, cwfitzgerald commented on wgpu-custom/Cargo.toml
> +name = "wgpu-custom"
What is the purpose of this crate?

2025-02-13 01:44 UTC, cwfitzgerald commented on wgpu/src/dispatch.rs
>  }
can this syntax be made more terse, now that there's only ever one being done per macro invocation?

2025-02-13 04:50 UTC, sagudev commented on wgpu-custom/Cargo.toml
> +name = "wgpu-custom"
Example how to use custom context.

2025-02-13 14:38 UTC, sagudev commented
> Don't love the whole new `type` alias thing, but don't really hate it enough to say no

I think we could actually inline all types uses into macro invocation (all 3 of them). Would that be better?

2025-02-13 14:46 UTC, sagudev commented on wgpu/src/dispatch.rs
>  }
Yes we can! Done in https://github.com/gfx-rs/wgpu/pull/6658/commits/bd92b353099ed393405ce7a65cec0e0a7085129a

2025-02-15 00:03 UTC, cwfitzgerald commented on wgpu-custom/Cargo.toml
> +name = "wgpu-custom"
Can this be either an example or a test? We don't really want more crates unless there's a strong motivating reason.

2025-02-15 00:04 UTC, cwfitzgerald commented
> I think we could actually inline all types uses into macro invocation 

Hmm, yeah I think that's fine - the whole appeal to me is to make sure things have uniform naming conventions and are all filled out, so having them all in one place seems to do that trick fine.

2025-02-15 06:57 UTC, sagudev commented on wgpu-custom/Cargo.toml
> +name = "wgpu-custom"
This should actually be example crate like those in [examples/standalone](https://github.com/gfx-rs/wgpu/tree/trunk/examples/standalone), but at the time of writing this PR, that didn't exists.

2025-02-15 07:03 UTC, sagudev commented
> > I think we could actually inline all types uses into macro invocation
> 
> Hmm, yeah I think that's fine - the whole appeal to me is to make sure things have uniform naming conventions and are all filled out, so having them all in one place seems to do that trick fine.

I am not sure I understand, should I inline all types uses into macro or keep the `mod`s?

2025-02-15 07:21 UTC, cwfitzgerald commented
Oh sorry was unclear, inline into the macro.

2025-02-15 08:05 UTC, sagudev commented on wgpu-custom/Cargo.toml
> +name = "wgpu-custom"
Done in https://github.com/gfx-rs/wgpu/pull/6658/commits/52d897ea6a84165f66a217675abbc9586fd66b48, I also write a description for crate.

2025-03-03 22:44 UTC, cwfitzgerald requested changes
Some small things, but I think this is good to go after that!

2025-03-03 22:44 UTC, cwfitzgerald commented on examples/custom-backend/Cargo.toml
This should be either be in `standalone` or in `features`, probably `features` - I don't think this needs it needs to be on the top level. Either way it needs to be added to the `example` README

2025-03-03 22:44 UTC, cwfitzgerald commented on wgpu/src/backend/custom.rs
> +        pub(crate) struct $name(Arc<dyn $interface>);
Any reason this couldn't be `Box`?

2025-03-04 10:06 UTC, sagudev commented on wgpu/src/backend/custom.rs
> +        pub(crate) struct $name(Arc<dyn $interface>);
It's to obtain `Eq`,`Hash`,`Cmp` implementations. We cannot use T implementations because traits are not object safe. Will write in comment.

2025-03-04 21:06 UTC, cwfitzgerald approved these changes
I have some futzing I want to do to the examples, but I'll do that post land.

Thanks!

2025-03-04 21:07 UTC, merged

2025-04-17 15:48 UTC, DJMcNab commented
Has this been released? I'm trying to check the changelog for when this got released

2025-04-17 16:33 UTC, sagudev commented
> Has this been released? I'm trying to check the changelog for when this got released

Yes it was, but there are still some rough edges: https://github.com/gfx-rs/wgpu/issues/7533