fix: Read environment variable configs in hello_triangle example
gfx-rs/wgpu pull request #6698
Opened 2024-12-11 01:41 UTC by fryeb

**Connections**
The hello_triangle doesn't support switching backends, leading to confusing errors like this one: https://github.com/gfx-rs/wgpu/issues/4247

**Description**
This adds support for the WGPU_* environment variables to the hello_triangle example, so that backend-specific issues can more quickly be narrowed down and fixes.

**Testing**
I've tested this manually, not sure if there is a better procedure for automatically testing these things

**Checklist**

- [x] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [ ] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown`
  - [ ] `--target wasm32-unknown-emscripten`
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2024-12-11 07:25 UTC, cwfitzgerald requested changes
LGTM, pending accidental .lock changes

(Reminder: please re-request a review from me once the changes are addressed to make sure I see it!)

2024-12-11 07:25 UTC, cwfitzgerald commented on Cargo.lock
Seemed to accidentally include some cargo.lock changes

2024-12-12 22:21 UTC, fryeb commented
I've removed the accidentally-queued lock file stuff. Might be worth adding another utils method for getting the whole instance descriptor, but we'll see. Not worth blocking this quick fix imho

2024-12-12 22:25 UTC, fryeb commented on Cargo.lock
oops! fixed this

2024-12-12 23:16 UTC, fryeb commented
I had a spare couple of minutes so I factored the whole thing into the utilities package, hopefully that makes the examples a little more succinct.

2024-12-12 23:47 UTC, cwfitzgerald approved these changes
Now that's **chefs kiss**

2024-12-13 00:37 UTC, fryeb commented
Apologies for re-requesting again. Just had to fix the clippy error

2024-12-13 00:58 UTC, merged

2024-12-13 00:58 UTC, cwfitzgerald commented
No worries!