Type/Expression Tandem
gfx-rs/wgpu pull request #6806
Opened 2024-12-22 23:12 UTC by kentslaney

**Connections**
Addresses #6788

**Description**
See the issue

**Testing**
It has not been tested yet

**Checklist**

- [ ] Run `cargo fmt`.
- [ ] Run `taplo format`.
- [ ] Run `cargo clippy`. If applicable, add:
- [ ] Run `cargo xtask test` to run tests.
- [ ] Add change to `CHANGELOG.md`. See simple instructions inside file.

2025-01-14 20:22 UTC, jimblandy commented
@kentslaney Why is `Validator::well_ordered_deps` necessary? Doesn't the existing code already check all these handles?

2025-01-14 20:29 UTC, jimblandy requested changes
It seems to me that handle validation shouldn't need to be changed. It's already supposed to be checking that all expressions refer only to other expressions earlier than them in the arena; are we missing some cases? The test this PR adds, `valid::handles::well_ordered_expressions`, passes on trunk, with no other changes to `valid::handles`.

We should not derive `PartialEq` on `Module`. The test should just do this:

```diff
modified   naga/src/compact/mod.rs
@@ -471,5 +471,6 @@ fn type_expression_interdependence() {
     type_needed(&mut module, ty_init);
     let untouched = module.clone();
     compact(&mut module);
-    assert!(module == untouched);
+    assert!(module.types.iter().collect::<Vec<_>>() == untouched.types.iter().collect::<Vec<_>>());
+    assert!(module.global_expressions.iter().collect::<Vec<_>>() == untouched.global_expressions.iter().collect::<Vec<_>>());
 }
```

I'm still trying to understand how the changes to compaction work. I'm marking this as "Request changes", but it's fine to hold off until I actually understand the rest of the PR.

2025-01-14 21:50 UTC, kentslaney commented
What happened with the validation was that I needed something different than cycle-free, but because of how cycle-free was validated, it actually provided the guarantee that I needed.

2025-01-14 23:26 UTC, jimblandy requested changes
I left some detailed comments but they may be moot, because I would like to ask for some deeper changes that will probably make the code I commented on go away anyway.

Specifically, `ExpressionTracer::trace_type` ends up using `TypeTracer::trace_type` to do a recursive traversal of the type arena. But because the type arena is a DAG, it should always be sufficient to make a single pass from end to front; recursion should never be needed. Also, because this recursion doesn't quit early when it sees a type it's already visited, it could take exponential time in the case of types like this:

```
struct A { }
struct B { m: A, n: A }
struct C { m: B, n: B }
struct D { m: C, n: C }
...
```

I mean, the struct's size is itself exponential in the nesting depth, so there are going to be some limits imposed on this, but it's not great for compaction to get caught up in that too.

2025-01-14 23:26 UTC, jimblandy commented on naga/src/compact/expressions.rs
> +    pub types: Option<&'tracer UniqueArena<crate::Type>>,
This needs a comment. Readers are going to want to know why this is an `Option`. It seems like `ExpressionTracer` must be being used in two contexts, one which cares about tracing into types, and one which doesn't - so what are those contexts? If someone is adding new code to the compactor, of course they're going to need to read the code, but give them a head start on figuring out:

- if they are adding new code to `ExpressionTracer`, how they need to handle this being present and absent

- if they are adding new code that uses `ExpressionTracer`, whether they need to fill this in or not.

In principle, if there were no comments at all, certainly people could just put in the time to do a full traversal of the code and understand everything. But comments are an opportunity to help a reader prune pieces out of that traversal.

This field probably belongs later in the struct, alongside related fields.

2025-01-14 23:26 UTC, jimblandy commented on naga/src/compact/expressions.rs
> +        fn handle2type(x: &mut TypeTracer, y: Handle<crate::Type>) {
We don't need long names like `handle_of_type_which_might_be_used_to_investigate_...`, but `x` and `y` are too short. You're basically telling the reader to look up the definition themselves every time they see a use. Give them a hand.

This function has a side effect, but its name sounds like it's a conversion function, which will slow readers down. It should be named something like `traverse_and_mark_used` or `deep` something-or-other. It doesn't need to be a full description of what it does (maybe `traverse_and_mark_used` is too long, in that sense), but once the reader has gotten the gist of it, the name should be an easy reminder, "Oh, yeah, that thing that does a deep traversal into types and marks all the types it uses."

In general, the function of a name is to help readers prune the traversal that they're doing of the code, and avoid (re-)investigating the name's definition. They can't really be *descriptive*, because that makes them too long, but they should be *evocative*, so that the reader's memory is jogged, and they can distinguish it from other similar things.

2025-01-14 23:35 UTC, jimblandy commented
> What happened with the validation was that I needed something different than cycle-free, but, because of how cycle-free was validated, it actually provided the guarantee that I needed.

Yes, this is a fair point - we validate not only that the arenas are cycle-free, but that handles only refer to earlier handles, which is a stronger condition.

2025-01-14 23:50 UTC, jimblandy commented
@kentslaney Hmm. I'd been assuming that there must be some analogue of the tactic we use in `Validator::validate_module_handles` that we could use in the compactor, that handles everything in a single pass. But as I'm thinking about it, I'm not sure there is a way after all. It may be the case that we need the deep traversal into types. But the way it may visit the same type many times gets worrisome.

I was thinking, oh, if the type is already marked as used, then you can stop the recursion there. But types could be marked as used even if we haven't looked into which expressions they use, so the flag indicating that the type is used doesn't imply that we don't need to traverse it.

2025-01-15 00:14 UTC, kentslaney commented
Oh, I actually did mean to stop the recursion if the type is already marked as used. Shouldn't step 1 ensure that any types marked as used has the corresponding expressions marked as used?

2025-01-15 00:27 UTC, kentslaney commented
For some reason I had it in my head that because the type arena was merging things that meant you could have out of order dependencies which made things more complicated. I think you're right that this could be simpler.

2025-01-15 02:29 UTC, jimblandy commented
> For some reason I had it in my head that because the type arena was merging things that meant you could have out of order dependencies which made things more complicated. I think you're right that this could be simpler since the current version assumes types are an unordered set.

Yeah, that should never happen, because we don't mutate types. They can only ever refer to stuff that was already in the arenas when they were created.

I *think* if you made a pass over the type arena from front to back and accumulated a map of the highest-indexed expression referred to by the types up to a given handle, then you could traverse types and expressions from back to front, using that map to decide how many expressions to process, and you'd always know that when you reached an expression marked unused, it was really, really never used, no matter what else you find in the types arena.

That sounds a lot more delicate than just recursing into types, if we could trust the types "used" bits to tell us when to stop traversing.

2025-01-16 21:51 UTC, kentslaney commented
> I _think_ if you made a pass over the type arena from front to back and accumulated a map of the highest-indexed expression referred to by the types up to a given handle, then you could traverse types and expressions from back to front, using that map to decide how many expressions to process, and you'd always know that when you reached an expression marked unused, it was really, really never used, no matter what else you find in the types arena.
> 
> That sounds a lot more delicate than just recursing into types, if we could trust the types "used" bits to tell us when to stop traversing.

I implemented this in #6934. I actually think your solution is a simpler implementation, but it's up to you. (The diff is easiest to view without whitespace changes.)

2025-01-23 03:43 UTC, kentslaney commented
Obsolete because of #6934

2025-01-23 03:43 UTC, closed without merging