Use Update After Bind Descriptors for Bind Groups With Binding Arrays
gfx-rs/wgpu pull request #6815
Opened 2024-12-23 07:42 UTC by cwfitzgerald

Enabled by #6811, needs to be merged after it.

Closes #6737

2024-12-24 00:33 UTC, cwfitzgerald commented
This needs more validation.

2025-01-21 00:32 UTC, cwfitzgerald commented
This PR is a bit of a mess, but I think it's broadly correct and the following PRs will further refine feature specifics. Specifically, we're moving towards two features for bindless, not many. One for "Baseline Bindless" which gets you non-uniform indexing of Storage Textures, Storage Buffers, and Sampled Textures. Then one feature for non-uniform indexing of uniform buffers, if people end up wanting that.

2025-01-24 04:52 UTC, magcius commented on wgpu-hal/src/vulkan/adapter.rs
> -        features.set(F::SHADER_PRIMITIVE_INDEX, self.core.geometry_shader != 0);
Is it intentional that support for SHADER_PRIMITIVE_INDEX appears dropped here?

2025-01-24 05:16 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/adapter.rs
> -        features.set(F::SHADER_PRIMITIVE_INDEX, self.core.geometry_shader != 0);
Nope, good catch

2025-01-25 16:24 UTC, Wumpf requested changes
I'm a bit confused: The new split out `UNIFORM_BUFFER_INDEXING` feature is never set, thus we never pass the new capability to naga, therefore it should now always reject uniform buffer indexing as its analyzer already correctly distinguishes that now to emit the (new) naga capability as required.

2025-01-25 16:24 UTC, Wumpf commented on wgpu-hal/src/vulkan/adapter.rs
>          }
I might be missing something, but I can't see anywhere where this would set `F::UNIFORM_BUFFER_INDEXING`. According to the comment block that would be a separate feature that needs to be checked

2025-01-25 16:24 UTC, Wumpf commented on wgpu-hal/src/metal/adapter.rs
> +                | F::STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING
similar to vulkan, shouldn't the `F::UNIFORM_BUFFER_INDEXING` be set somewhere here as well? In wgpu-types you specified `with MSL 2.0+ on macOS 10.13+` as the condition

2025-01-25 16:24 UTC, Wumpf commented on deno_webgpu/lib.rs
> +    if features.contains(wgpu_types::Features::STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING) {
missing the new feature, it's not exposed here

2025-01-25 16:24 UTC, Wumpf commented on deno_webgpu/lib.rs
> +            wgpu_types::Features::STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING,
as above, new feature is missing here

2025-02-15 04:40 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/adapter.rs
>          }
Yeah this is a thing I just forgot to mention entirely. Currently it's impossible to use this new feature. The validation added in #6811 mean that such a bind group will always get rejected. I'm going to update the feature description and make an issue to properly implement it.

2025-02-15 05:17 UTC, cwfitzgerald commented on wgpu-hal/src/vulkan/adapter.rs
>          }
Updated the docs.

2025-02-15 11:35 UTC, Wumpf approved these changes

2025-02-15 17:02 UTC, merged