[naga] Builtin function database, for automatic conversions
gfx-rs/wgpu pull request #6833
Opened 2024-12-27 21:22 UTC by jimblandy

Work in progress for #6443.

2025-03-15 21:03 UTC, jimblandy commented
Rebased on #7344.

2025-03-23 00:11 UTC, jimblandy commented
Okay, all the `MathFunction` functions are implemented. We should cover the other categories in the IR too, but I think this is a good start.

There are some test failures to address.

2025-03-23 04:58 UTC, jimblandy commented on naga/src/proc/builtins/list.rs
> +    rules: Arc<Vec<Rule>>,
I can't see why this shouldn't be `Rc`.

2025-03-23 19:35 UTC, jimblandy commented
Okay, there's only one test failure remaining now:

```
thread 'snapshots::convert_snapshots_wgsl' panicked at naga/tests/snapshots.rs:801:23:
error: failed to convert expression to a concrete type: Subexpression(s) are not constant
  ┌─ /home/jimb/rust/wgpu/naga/tests/in/wgsl/cross.wgsl:3:13
  │
3 │     let a = cross(vec3(0., 1., 2.), vec3(0., 1., 2.));
  │             ^^^^^ this expression has type vec3<{AbstractFloat}>
  │
  = note: the expression should have been converted to have f32 scalar type
```

As far as I can see, `vec3<{AbstractFloat}>` is the correct type for that `cross` call to return. So I think this might be a different Naga bug. We'll have to get that fixed before we can land this.

2025-03-23 19:39 UTC, jimblandy commented on naga/src/proc/mod.rs
> +mod builtins;
Should this be named `overloads`? It's more about overload sets than builtin functions, specifically.

2025-03-24 03:32 UTC, jimblandy commented
> As far as I can see, `vec3<{AbstractFloat}>` is the correct type for that `cross` call to return. So I think this might be a different Naga bug. We'll have to get that fixed before we can land this.

The issue here is that `cross` is one of the operations not implemented by the constant evaluator.

On `trunk`, Naga concretizes all arguments to builtin functions, so the arguments to `cross` are `vec3<f32>`, so its return type is `vec3<f32>`, so the `let`'s initializer is a concrete type. All is well.

With this PR, Naga does not concretize arguments to builtin functions, so the arguments to `cross` are `vec3<{AbstractFloat}>`, so its return type is `vec3<{AbstractFloat}>` too. The `let` statement asks for its initializer to be concretized, but concretization isn't a run-time conversion - abstract types cannot exist at runtime - but is rather part of constant evaluation, that needs to know the actual value. Since the `cross` call has been left unevaluated as an `Expression::Math`, concretization fails.

Indeed, removing AbstractFloat from the set of scalars that `cross` accepts makes the problem go away.

2025-03-24 05:15 UTC, jimblandy commented
Okay, so I tried implementing `cross` in #7404, but then the tests just die on `ldexp`, in the same way.

I don't think it makes sense to gate this PR on having full coverage for `MathFunction` in the constant evaluator. What we can do instead is have `MathFunction::overloads` lie and claim that those functions don't operate on abstract types. This will cause abstract values to undergo automatic conversion (probably to `f32` scalars), which is not right but usable.

The trick will be ensuring that we don't forget to update the overloads when we do actually add support for these functions to the constant evaluator.

2025-03-24 06:18 UTC, jimblandy commented
There is one remaining issue: WGSL says that, if an argument is not a constant expression, then no overloads that accept abstract types are allowed. This PR's code in the validator doesn't implement that rule yet. `OverloadSet::concrete_only` is supposed to make this work, but it's not hooked up.

2025-03-24 06:29 UTC, jimblandy commented
There's another problem I realized: this PR's changes to the validator don't check that enough arguments were passed. 

The WGSL front end does happen to check this, but the code is only correct when all overloads take the same number of arguments. This happens to be true now, but it's not a promised characteristic of an overload set, and when we expand this to handle texture operations, it won't be true.

There was no test coverage for this case - but we know that our coverage for error-checking is weak.

2025-03-24 06:37 UTC, jimblandy commented
> The trick will be ensuring that we don't forget to update the overloads when we do actually add support for these functions to the constant evaluator.

I think I've arranged this by using bad names for the constant used by functions that have had their wings clipped in this way, whose documentation mentions #7405.

2025-03-24 20:46 UTC, jimblandy commented
Okay, this has new docs and some renamings to better match the current code.

2025-03-24 21:55 UTC, jimblandy commented
It turns out we don't need `OverloadSet::concrete_only` for any overloads we currently support, and in some cases it would be hard to get the information we need (typifier doesn't know about constness), so I've just commented to explain why we're not worrying about it, declared victory, and moved on.

2025-03-24 22:08 UTC, jimblandy commented
It turns out the WGSL front end was already checking call arity in a way that is correct for the current set of overloads, so there were no changes there. I've fixed the validator and added tests that build a Naga module directly, to get past the WGSL front end. I left the typifier alone, since that doesn't check arity in general.

2025-03-26 14:35 UTC, ErichDonGubler commented on naga/src/common/diagnostic_display.rs
> +/// As discussed in #7268, diagnostic output ought to depend on the
nitpick: Referring to #7268 for _history_ seems…not important for the reader? We're telling them what this thing is and how to use it; giving them an history of its design—especially one that hasn't been written—is a reading and maintenance cost without strong benefit. If users are curious what motivated changes, then our Git history should help them do that.

I think it can be valuable to tell them where to go to track development of this trait, and that would justify the link. We'd need to present it differently, though, for that to make sense.

2025-03-26 14:35 UTC, ErichDonGubler commented on naga/src/common/diagnostic_display.rs
> +pub struct DiagnosticDisplay<T>(pub T);
issue: y `pub` tho

2025-03-26 14:35 UTC, ErichDonGubler commented on naga/src/common/diagnostic_display.rs
> +        }
issue(non-blocking): It seems wrong to predicate usage of WGSL-only formatting on whether compile-time features are enabled, as opposed to tracking the language (even with only a single-variant `enum`). This works because we're not using this across more than the WGSL front-end yet, but…this seems like a footgun waiting to fire.

2025-03-26 14:35 UTC, ErichDonGubler commented on naga/src/common/diagnostic_debug.rs
> +pub struct DiagnosticDebug<T>(pub T);
thought: I think it's unfortunate that these `Diagnostic*` traits have poor discoverability for users who don't know they need it, but I can't immediately think of a better way to work around that and still fulfill requirements for needing to abstract over the exact shape of data for context and thing-to-print.

2025-03-26 14:35 UTC, ErichDonGubler commented on naga/src/common/diagnostic_debug.rs
thought: I'm not sure that it's worth having separate files for these, but I'm willing to see how this plays out in practice. It feels weird to have these two files share such a similar use case but not at least have a common module parent.

2025-03-26 14:35 UTC, ErichDonGubler commented on naga/src/common/diagnostic_display.rs
> +        }
I think I'll try attacking this as follow-up work, since I'd prefer this PR ship and we have one less (major) 
concern for a Firefox 139 Beta release.

2025-03-26 19:25 UTC, jimblandy commented on naga/src/common/diagnostic_display.rs
> +pub struct DiagnosticDisplay<T>(pub T);
Naga's IR types are part of its public interface. I think anyone working with Naga would like to be able to format types and related things in logging and diagnostics.

I've made the modules `naga::common::diagnostic_display` and `diagnostic_debug` private, though.

2025-03-26 19:37 UTC, jimblandy commented on naga/src/common/diagnostic_display.rs
> +        }
The idea was to put off the design of language selection until we could actually use it. Writing a single-variant enum would "force us to think through" language-sensitivity in the absence of any actual varying behavior that could be observed or tested, and in the absence of multiple internal users. That sounds like a waste of time.

Certainly anything that adds fields to `DiagnosticDisplay` will break any code that creates it, so it will be easy to find all the uses that need to be updated. This is what I was trying to get at in the doc comment.

"Footgun", to me, means "something likely to cause bugs". Suppose someone is implementing language-sensitive diagnostics. If they are not using `DiagnosticDisplay` for their output, then it doesn't affect them. If they are, then they cannot get the behavior they want without fixing this. So either it goes harmlessly unnoticed or it gets fixed.

2025-03-26 19:42 UTC, jimblandy commented on naga/src/common/diagnostic_debug.rs
> +pub struct DiagnosticDebug<T>(pub T);
We could add `as_diagnostic_display` and `as_diagnostic_debug` methods to the IR types that construct these:

```rust
log::debug!("My type: {:?}", type_inner.as_diagnostic_debug(type_arena));
```

Then it would show up in the docs for `TypeInner`.

2025-03-26 19:46 UTC, jimblandy commented on naga/src/common/diagnostic_debug.rs
I'm not sure what you mean - `diagnostic_display.rs` and `diagnostic_debug.rs` do have a common module parent: `naga::common`.

The Rust standard library has pretty small modules, and the effect seems nice. I think it's helpful because it makes it more apparent what the module's main burden depends on. In this case, we can see that the two wrapper types are basically independent.

2025-03-26 19:54 UTC, ErichDonGubler commented
Ah, I forgot my obligatory Conventional Commits disclaimer. 😅

---

<sub>I used [Conventional Comments](https://conventionalcomments.org/) in this review! I hope they help with clarity and tone. 🙂</sub>

2025-03-26 19:56 UTC, ErichDonGubler reviewed
Sigh, my previous comments came out earlier than I intended, and they were originally written more as notes for myself than the presentation I wanted for the PR author. Sorry about that!

Adding s'more feedback here; just getting to the core part of this PR now.

2025-03-26 19:56 UTC, ErichDonGubler commented on naga/src/common/diagnostic_display.rs
> +        ))?;
thought: It's unfortunate that `TryToWgsl` forces an allocation here, when it shouldn't be necessary. Perhaps we should also change `TryToWgsl` to move current implementations to a `Formatter`-ish API that can back the current APIs a la `Display` to `ToString`, minus maybe the separation of traits?

2025-03-26 19:56 UTC, ErichDonGubler commented on naga/src/proc/type_methods.rs
> +    pub fn scalar_for_conversions(
thought: It's so hard to name things like this, and I don't think we need to block on finding a perfect name. I was wondering, though, if we could provide a better contrast for the use cases distinguishing this from `scalar`; perhaps just describing why `scalar` is useful in its entry, since I couldn't immediately tell?

I had thought `scalar_for_conversions` would still be useful in contexts `scalar` would be, but I'm fuzzy on why we'd want to omit `Array` types in `scalar`'s case.

2025-03-26 19:56 UTC, ErichDonGubler commented on naga/tests/validation.rs
> +                arg3: (arity >= 4).then_some(ex_zero),
question: Is this arity checking a bugfix that could be separated out from the main commit?

2025-03-26 19:58 UTC, ErichDonGubler commented on naga/src/common/diagnostic_debug.rs
> +pub struct DiagnosticDebug<T>(pub T);
That sounds nice! 😀

2025-03-26 19:59 UTC, jimblandy commented on naga/src/common/diagnostic_display.rs
> +        }
I think the ideal you're aiming for here is something like, a good API is one that doesn't need to change: it is clean enough to serve in almost any reasonable use case, so although future development will add new uses, the initial API will suffice. Thus, the enum should be present in the first design, so that the only change in the API will be adding more supported languages, which should be non-breaking.

The problem with this ideal is that nobody can actually get APIs right the first time. The Rust standard library doesn't even aim for that: you're not even *allowed* to add stuff to `std` without letting people live with it and suffer for a while first. The WGSL committee only gets away with the kind of design it does because there's practically nothing novel in WGSL, we're just rehashing (at least) four existing designs. Every time we standardize something ahead of what people are already using, we take a big risk.

So trying to design the language sensitivity in advance of having more than one language we can produce seems like a bad move. The best we can do is make sure the rest of Naga gets compile-time errors when we change this API.

2025-03-26 20:07 UTC, ErichDonGubler commented on naga/src/common/diagnostic_display.rs
> +        }
> I think the ideal you're aiming for here is something like, a good API is one that doesn't need to change: it is clean enough to serve in almost any reasonable use case, so although future development will add new uses, the initial API will suffice. Thus, the enum should be present in the first design, so that the only change in the API will be adding more supported languages, which should be non-breaking.

Only sort of. I don't really feel pretty in WGPU to ship APIs that never break; we ship a major version every few weeks still, so 🤷🏻‍♂️ whatevs!

My main reason for mentioning a concrete implementation direction is that I can already see where such an `enum` might be used, and have written some local changes to practice using it. I did this out of (timeboxed) interest for the (follow-up) problem, and wanted to suggest something I felt was workable to get consensus in a place that made sense to me at the time.

2025-03-26 20:07 UTC, ErichDonGubler commented on naga/src/common/diagnostic_display.rs
> +        }
When I saw this code and its use sites, I figured you were doing this out of pragmatism—wanting to only take on the scope necessary to solve this problem. So, when you say:

> "Footgun", to me, means "something likely to cause bugs". Suppose someone is implementing language-sensitive diagnostics. If they are not using `DiagnosticDisplay` for their output, then it doesn't affect them. If they are, then they cannot get the behavior they want at all without fixing this. So either it goes harmlessly unnoticed or it gets fixed.

…I don't disagree with the definition of that specific term, and think we both had the same perception of this code otherwise. If you'd prefer the term "compiler booby trap" or another term to distinguish, I'd be interested in having a noun distinct from the sense you're disclaiming here.

2025-03-26 20:13 UTC, jimblandy commented on naga/src/common/diagnostic_display.rs
> +        ))?;
Yeah, I feel exactly the same way; I went back and forth on this a lot. I thought about building everything around `Formatter`, but:

- A `Formatter`-based implementation makes it impossible to get a `&'static str` even for things like `Interpolation` which are fine with it.

- `Formatter` fundamentally does not support errors during formatting; the documentation for `core::fmt` says:

    > That is, a formatting implementation must and may only return an error if the passed-in [Formatter](https://doc.rust-lang.org/std/fmt/struct.Formatter.html) returns an error. This is because, contrary to what the function signature might suggest, string formatting is an infallible operation.

    This makes it an awkward fit for Naga IR types that can express things that have no WGSL representation, like `Scalar`. Since the backend uses it, and that definitely wants never to emit non-WGSL, I felt like these traits should always basically force users to say how they wanted to deal with non-WGSL IR, either through their implementation of `TypeContext` methods, or by calling `blah_for_diagnostics`, or by getting a `None` from `try_to_wgsl`.

(This is the kind of feedback I was expecting to get on #7344, I was sure you were going to ding me for the `ToWgsl` / `TryToWgsl` / `Formatter` chaos!)

2025-03-26 21:35 UTC, jimblandy commented on naga/src/proc/type_methods.rs
> +    pub fn scalar_for_conversions(
Yeah, this is ugly. I wasn't happy about this either.

There are, scattered around the code base:
- around 20 uses of `TypeInner::scalar`,
- around 60 uses of `TypeInner::scalar_kind`, and
- around 10 uses of `TypeInner::scalar_width`,

where the latter two functions inherit `scalar`'s array-ignoring behavior, scattered around the code base. From what I could see, most of those were indeed trying to deal with scalars and vectors only. So changing the function's behavior to match its name, and consider arrays as well, seemed risky. There's also the wrinkle that handling `Array` requires a type arena, and I didn't relish the idea of piping a type arena to 90 calls that obvious don't need it right now.

I considered renaming that method `scalar_or_vector_scalar`, but with such widespread use that seemed inappropriately punitive. I couldn't think of any word from mathematics that meant "vector or scalar". "Linear" is close, and the function does support `Matrix`, so, `scalar_for_linear`?

In the end I left it alone. I think every code base has a few items like this, where they're not really ideally named but they're so widely used that people just learn the specific meaning and it doesn't really cause a problem. Not ideal, but I'm not sure it's really causing that much trouble.

I'm also not sure that the `scalar_for_conversions` definition, which covers `Array`, deserves the simpler name `scalar`, either. That is definitely the definition that corresponds to the WGSL specification's "Conversion Rank" table, but that requires that `Atomic` types be excluded. Is *that* expected behavior for a function named `scalar`? Is there anyone who could even use a definition that included `Atomic`?

So maybe there is nothing that should be named `scalar`, and everything should have more complicated names.

In principle, though, I would love for the more restricted function to have the more restricted-sounding name.

2025-03-26 21:46 UTC, jimblandy commented on naga/tests/validation.rs
> +                arg3: (arity >= 4).then_some(ex_zero),
It's not a bugfix. I just realized that the arity checking for `MathFunction` wasn't working quite as I'd expected (although it was working), and decided to have this test exercise that aspect of the validator.

It's a little tricky to test the validator at the moment: the WGSL front end does so much validation already that there are many interestingly invalid `Module`s that we cannot produce by parsing WGSL. But the validator is still on the hook to reject them. The tests in this file get around that by building `Module` values from scratch. Since I wanted to exercise the validator's arity checking, I decided to expand this test.

2025-03-26 21:57 UTC, jimblandy commented on naga/src/common/diagnostic_display.rs
> +        }
So, as the person implementing the language-sensitive behavior, don't you want an obvious mandate to break the API anyway? And if you do, then it seems to me that any guesses I could make at this point would just be in your way. My intent was to *encourage* the person implementing that behavior to be free to do whatever works best, by not laying down any foundation that they'd feel required to build upon.

2025-03-26 21:58 UTC, jimblandy commented on naga/src/common/diagnostic_debug.rs
> +pub struct DiagnosticDebug<T>(pub T);
Okay, I'll do this.

2025-03-27 00:46 UTC, jimblandy commented
@ErichDonGubler I've pushed a new commit that adds `for_debug` methods, to make `DiagnosticDebug` more discoverable. We could do the same for `DiagnosticDisplay`, but I thought I'd push the commit and see what you thought.

I named the method `for_debug`, rather than `as_debug`, because the Rust API style guide specifically says that `as_foo` should be used for borrowing conversions, and for tiny `Copy` types like `Scalar` the references are unnecessarily awkward. I'm open to feedback.

2025-03-27 01:10 UTC, andyleiserson reviewed
This looks pretty good to me. Maybe it would be worth adding some tests from [the bugs we're expecting this to fix](https://bugzilla.mozilla.org/buglist.cgi?query_format=advanced&o1=substring&f1=see_also&v1=https%3A%2F%2Fgithub.com%2Fgfx-rs%2Fwgpu%2Fissues%2F6443&component=Graphics%3A%20WebGPU&list_id=17488908)? I think `pow`, `min`/`max`, and `clamp` with a mix of abstract and concrete arguments are common offenders.

2025-03-27 01:10 UTC, andyleiserson commented on naga/src/front/wgsl/lower/mod.rs
> +                        if next_remaining_overloads.is_empty() {
This seems like something that might be worth extracting into a separate function, both on the general principle of doing so when possible, but in particular in this case because we might want to reuse it for other classes of functions besides math. (I originally wrote this about the diagnostic reporting. But it actually might make sense for all of the overload resolution.)

2025-03-27 01:10 UTC, andyleiserson commented on naga/src/front/wgsl/lower/mod.rs
> +                                // would ever be allowed there.
The comment makes it sound like `allowed` should be computed from `fun_overloads`, instead of `remaining_overloads`. Also, how can `TooManyArguments` arise here, after having checked `max_arguments` above?

2025-03-27 01:10 UTC, andyleiserson commented on naga/tests/wgsl_errors.rs
> +  = note: allowed type: vec3<f64>
I'm not sure why these came out in this order, and it doesn't seem particularly important that they're not sorted, but if they're coming from a hashmap or something where the order might be non-deterministic, that seems undesirable.

Edit: I guess from the order in `float_scalars()`, so that's fine.

2025-03-27 01:10 UTC, andyleiserson commented on naga/src/proc/type_methods.rs
> +    pub fn scalar_for_conversions(
What is the case where we need to convert a leaf scalar within an array? I tried commenting out the line that handles arrays in this function, and didn't get any test failures. I guess one case is `const`/`let`/`var` declarations, but that's driven top-down and is already (mostly, modulo #7367) working without `scalar_for_conversions`. (I don't think it uses `scalar`.)

Semi-related, there is a note in the PR description about returning `TypeResolution::Value`s from function database processing. Is it a problem that `TypeResolution::Value` is not allowed to contain structs or arrays?

2025-03-27 01:10 UTC, andyleiserson commented on naga/src/proc/overloads/mod.rs
> +            Mf::InsertBits => lists::insert_bits().into(),
I get that `lists.rs` is maybe intended to associate with the `List` variant, but it does seem like there's some convenience value in having all the rules in one file, if it's not too difficult to arrange.

2025-03-27 01:10 UTC, andyleiserson commented on naga/src/proc/overloads/regular.rs
> +///   type is the leaf scalar type of the argument type.
```suggestion
/// - `regular!(1, VECN<FLOAT> -> Scalar)`: An overload set whose rules take one
///   argument that is a vector of floats, and whose return
///   type is the leaf scalar type of the argument type.
```

2025-03-27 02:21 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                        if next_remaining_overloads.is_empty() {
Yes - I've been working on this as a follow-up. I think we should be able to get a pretty general "resolve overloads" and "apply conversions for this overload" utility functions out of it, which seem re-usable.

2025-03-27 02:22 UTC, jimblandy commented on naga/tests/wgsl_errors.rs
> +  = note: allowed type: vec3<f64>
Yes, and this is generally the order of least conversion rank. I don't know if it is great to expose that - the ordering looks weird - but in any case it's not non-deterministic.

2025-03-27 02:26 UTC, jimblandy commented on naga/src/proc/overloads/mod.rs
> +            Mf::InsertBits => lists::insert_bits().into(),
I'm not thrilled about broadening the scope of all those little utility functions. But we have a few options here; I'll play with things and see what comes up.

2025-03-27 02:38 UTC, jimblandy commented
Hmm, somehow these didn't get registered as comments that I could reply to. I wonder what GitHub is thinking...

> What is the case where we need to convert a leaf scalar within an array? I tried commenting out the line that handles arrays in this function, and didn't get any test failures. I guess one case is const/let/var declarations, but that's driven top-down and is already (mostly, modulo https://github.com/gfx-rs/wgpu/pull/7367) working without scalar_for_conversions. (I don't think it uses scalar.)

Following WGSL, in Naga IR `array<T,N>` automatically converts to `array<S,N>` if `T` automatically converts to `S`. However, I think this case never arises with builtin functions, since I don't think there are any that accept arrays as arguments. The exception is `arrayLength`, which Naga handles as its own expression type.

> Semi-related, there is a note in the PR description about returning TypeResolution::Values from function database processing. Is it a problem that TypeResolution::Value is not allowed to contain structs or arrays?

In general, `TypeResolution`s are only meaningful with respect to some type arena. So `TypeResolution::Handle` can represent a struct, and arrays can be represented either as a `TypeResolution::Handle` holding a handle to an array type, or as a `TypeResolution::Value(TypeInner::Array)`.

It turned out that having overload resolution deal with looking up struct types for things like `modf`'s return value caused a lot of trouble, which is why `Conclusion` lets it say what it means without worrying about whether the type actually exists in an arena. Letting the caller deal with it was much cleaner.

2025-03-27 02:43 UTC, jimblandy commented on naga/src/proc/type_methods.rs
> +    pub fn scalar_for_conversions(
(Ahh, here's where that comment came from. Duplicating my reply...)

> What is the case where we need to convert a leaf scalar within an array? I tried commenting out the line that handles arrays in this function, and didn't get any test failures. I guess one case is const/let/var declarations, but that's driven top-down and is already (mostly, modulo https://github.com/gfx-rs/wgpu/pull/7367) working without scalar_for_conversions. (I don't think it uses scalar.)

Following WGSL, in Naga IR `array<T,N>` automatically converts to `array<S,N>` if `T` automatically converts to `S`. However, I think this case never arises with builtin functions, since I don't think there are any that accept arrays as arguments. The exception is `arrayLength`, which Naga handles as its own `Expression` variant.

> Semi-related, there is a note in the PR description about returning TypeResolution::Values from function database processing. Is it a problem that TypeResolution::Value is not allowed to contain structs or arrays?

In general, `TypeResolution`s are only meaningful with respect to some type arena. So `TypeResolution` can represent a struct as a `TypeResolution::Handle` holding a handle to a struct type in the arena, and arrays can be represented either as a `TypeResolution::Handle` holding a handle to an array type, or as a `TypeResolution::Value(TypeInner::Array)`.

It turned out that having overload resolution deal with looking up struct types for things like `modf`'s return value caused a lot of trouble, which is why `Conclusion` lets it say what it means without worrying about whether the type actually exists in an arena. Letting the caller deal with it was much cleaner.

2025-03-27 03:09 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                        if next_remaining_overloads.is_empty() {
I've published this refactoring as #7442.

2025-03-28 10:58 UTC, ErichDonGubler requested changes
Mostly LGTM, though there are a litany of issues and question I have.  That's expected; this PR suffers from being _really freaking big_ and needing a proportionate amount of review time. I hope to work with you to resolve them together quickly—maybe pairing in a call?

I'm also going to finalize the scope of my review, despite not being exhaustive. What I've ensured is that:

- …new code is coherent with the WGSL standard and the existing codebase.
- …new diagnostics are clear enough to help users make the right changes to their WGSL.
- …the overall approach seems sound. That it does!

My single big concern is about how we're imposing WGSL's builtin signatures in other langauges, but maybe this isn't new. See the discussion I made for more details.

What I _haven't_ covered is:

- …in-depth review of logic matching overloads sets to argument types.
- …review of the actual overload sets written per math function to check that they match the spec.

I intend to drive the discussions relevant to the scope I _have_ covered to completion. For the remainder, the opportunity cost with further review doesn't seem worth it. The scope I'm not planning on covering in my review should be pretty easy to diagnose and fix. I don't see my review catching those bugs without _significantly_ more time and effort. At the same time, this PR has a very high demand on Mozilla's end, being a high priority for most of the two and a half years I've worked on WGPU.

I strongly suspect that the most effective way to learn more about any latent issues we may have is to pit it against WebGPU CTS and users' code ASAP, and follow up fast. There is also reason to suspect that there won't be many broad or severe regressions, given:

- We haven't touched any snapshot tests in this PR; they still pass.
- We've been driving this PR's development with making failing examples in Firefox's [`webgpu-apps`](https://bugzilla.mozilla.org/show_bug.cgi?id=webgpu-apps) and [`webgpu-mvp-apps`](https://bugzilla.mozilla.org/show_bug.cgi?id=webgpu-mvp-apps) bug indices pass.

praise: It's been really nice to see the majority of what's being introduced with docs explaining their purpose. It has made it easier to review this code, and validate that it seems to do what it claims. This is...definitely not the norm for contributions to WGPU, historically. 😅

praise: It's nice to have type checking that correlates pretty strongly to the language of the spec. That makes will make it _so_ much easier to inspect for bugs.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/common/wgsl/types.rs
> +
note: The name of this `write_type_rule` helper implies that it writes _type rules_ as the more general concept from the WGSL standard, and not just type rules for functions. However, its written output deals strictly with functions and their calls, _not_ the entire set of types rules that include, i.e., expressions' type rules.

question: Is there a better name we can use for this? Is there a plan to eventually include expressions' type rules as part of this?

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +
style: Newlines between each `Error` variant introduced here is inconsistent with the other variants, even ones with commentary and named fields. Let's be consistent for now, and if it's important enough to change the style, let's do that as a separate commit.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +    WrongArgumentCountForOverloads {
suggestion(non-blocking): This `WrongArgumentCountForOverloads` variant is similar to the `TooManyArguments` variant (though OFC this is at a later stage). Perhaps a rename to `TooManyArgumentsForOverloads` could make this clearer?

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                let message = format!("Too many arguments in this call to to `{function}`");
typo: s/to to/to

```suggestion
                let message = format!("Too many arguments in this call to `{function}`");
```

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    (call_span, "The function is called here".into()),
thought(non-blocking): If you look at errors from `rustc`, the primary span generally tends not to have much content, often omitting a label for the span (for which we would use an empty label here). Case in point for this sort of error; using this source:


```rust
fn asdf(_blarg: u32) {}

fn main() {
    asdf(23, 24);
}
```

…yields this error:

```
error[E0061]: this function takes 1 argument but 2 arguments were supplied
  --> src\main.rs:4:5
   |
 4 |     asdf(23, 24);
   |     ^^^^     -- unexpected argument #2 of type `{integer}`
   |
 note: function defined here
  --> src\main.rs:1:4
   |
 1 | fn asdf(_blarg: u32) {}
   |    ^^^^ -----------
 help: remove the extra argument
   |
 4 -     asdf(23, 24);
 4 +     asdf(23);
   |
```

It doesn't _hurt_ to have that extra information here, but we _could_ streamline the output and present less phatic error messages to the user. 

I think it's interesting to come up with some guidelines we'd like for diagnostics, because everybody working on diagnostics has kind of worked in isolation until now. Would an overall review of diagnostic messaging be interesting for H2 (from Firefox's end)?

☝🏻CC @gfx-rs/wgpu on this, will add to the agenda.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    (arg_span, "This is the first excess argument".into())
thought: `rustc` uses a label that seems much more accessible for a case like this; given this Rust source:

```rust
fn asdf(_blarg: u32) {}

fn main() {
    asdf(23, 24);
}
```

…we get this error:

```
error[E0061]: this function takes 1 argument but 2 arguments were supplied
  --> src\main.rs:4:5
   |
 4 |     asdf(23, 24);
   |     ^^^^     -- unexpected argument #2 of type `{integer}`
   |
 note: function defined here
  --> src\main.rs:1:4
   |
 1 | fn asdf(_blarg: u32) {}
   |    ^^^^ -----------
 help: remove the extra argument
   |
 4 -     asdf(23, 24);
 4 +     asdf(23);
   |
 ```

Note how the excess argument label has the argument index and the type.

If you think the above is interesting, I'm happy to file the issue.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                ],
thought: As follow-up, we _could_ add some help here in the case that removing the argument would be accepted, but that would require further type checking instead of just stopping where the current error is emitted.

If you think the above is interesting, I'm happy to file the issue.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    format!("Because argument #{} has type `{prior_ty}`,", prior_index + 1),
thought: This is an abstract concern, but I wonder if there's a case where pointing at the immediately prior argument will yield incorrect information.

No action items here, just wondering out loud.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    "Inconsistent type passed as argument #{} to `{function}`",
style: We should avoid capitalization on the first word in diagnostic `message`s. Other messages already use lowercase, so the immediate problem here is that capitalization is inconsistent with this PR. Also, I'd prefer to stick with no capitalization anyway, since this convention is part of diagnostic style guidelines in ecosystems we look to for inspiration.

Examples:

* `rustc`'s [Diagnostic Structure](https://rustc-dev-guide.rust-lang.org/diagnostics.html#diagnostic-structure):

	> The text should be matter of fact and avoid capitalization and periods, unless multiple sentences are needed: …

* `clang`s [Diagnostic Wording section](https://clang.llvm.org/docs/InternalsManual.html#diagnostic-wording) in the internals manual:

	> Diagnostics in Clang do not start with a capital letter and do not end with punctuation. …

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    "Inconsistent type passed as argument #{} to `{function}`",
This could reasonably be done as follow-up. If you need it, I can file the issue.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    "Wrong type passed as argument #{} to `{function}`",
note: When tools like LSP clients aggregate over errors, they usually use an error code (if available; it's a less common system to have, at least until a language reaches a certain popularity), or the error message.

note: IME, developers confronted with diagnostics almost always look at the labels first, because it orients them far faster. If the label is helpful and/or the user is experienced, they'll often skip reading the message entirely. Because of this, I've found that one typically gets a better diagnostic experience with succinct general messages, leaving most concrete details to labels. The message's role, then, should be to contain whatever general context helpful when somebody doesn't understand the overall problem; this typically only happens if they read the labels and can't determine what action to take next.

suggestion(non-blocking): In Naga, we've been inconsistent in how we've treated the contents of the error message vs. the contents of the labels. I think this would be a good overall review to do with WGPU maintainership, maybe in H2?

☝🏻CC @gfx-rs/wgpu.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/lower/mod.rs
> +                    if arguments.len() < min_arguments || max_arguments < arguments.len() {
style: `RangeFull::contains` seems like an easier-to-read alternative in the face of a moderately long expression-to-check like `arguments.len()`:

```suggestion
                    if !(min_arguments..=max_argument).contains(&arguments.len()) {
```

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/lower/mod.rs
> +                                // would ever be allowed there.
I was also wanting to know about `TooManyArguments`, since it seems like it shouldn't be needed anymore—maybe `unreachable!(…)` and type simplifications can be applied to `ArgumentContext::{finish,next}` now?

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +    WrongArgumentCountForOverloads {
Context: Part of the reason I suggest this is because of the concern raised about `WrongArgumentCount` maybe never being emitted after this commit, so it's likely that unifying language with that variant isn't useful.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/lower/mod.rs
> +                                    // This is the argument that killed our dreams.
praise: Thanks for the laugh. 😆

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                        "`fn`, `diagnostic`, `enable`, `requires`, `;`) ",
nitpick: Would be nice to have a separate commit for this. Don't go back and fix it now, tho.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                notes.extend(allowed.iter().map(|ty| format!("allowed type: {ty}")));
thought: This is the sort of code in which I feel a `lazy_format::lazy_format!(…)` would be nice to have. Avoiding intermediate allocations that way would be nice.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +            Error::WrongArgumentType {
issue: I don't see any test coverage that actually emits and snapshots the output of any of these new errors. Bruh!

We might reasonably choose to punt this to immediate follow-up, but I don't think this should wait longer than that. I'll file the issue, if you want.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/one_bits_iter.rs
issue: Unit tests would go a _long_ way towards ensuring `OneBitsIter` code behaves correctly long-term. Let's not leave this untested.

We could reasonably punt this to immediate follow-up, but I don't think we should wait longer than that.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/rule.rs
> +/// in the builtin function database.
nitpick: This feels like it could be more brief, but with the same information and no loss to readability.

suggestion: It would also be helpful here to link to the function database. I suppose this would be a link to the `overloads` module?

Combined suggestions:

```suggestion
/// A return type produced by a Naga IR builtin function,
/// generally queried from the [builtin function
/// database](crate::proc::overloads).
```

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/typifier.rs
> +                log::debug!("{:#?}", overloads.as_debug(types));
nitpick: You can coalesce these `log::debug!(…)` calls:

```suggestion
                log::debug!("initial overloads for {fun:?}\n{:#?}", overloads.as_debug(types));
```

In general, it's preferable to coalesce content that is intended to be emitted as a unit to a single call, because `log` backends might not necessarily be a simple line-separated output.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/typifier.rs
> +                log::debug!("{:#?}", overloads.as_debug(types));
This feedback also applies to other places where `log` is called in series.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/valid/expression.rs
> +                        */
question: Why leave this here and uncommented? This doesn't look like just debugging, since it mutates `overloads`.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/tests/validation.rs
> +                arg3: (arity >= 4).then_some(ex_zero),
Sounds like this might have been a helpful commit to separate out, then, but I don't see a problem with keeping it here right now. I don't see enough benefit in going to the effort right this second.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/regular.rs
> +/// - `regular!(2, SCALAR|VECN<FLOAT>)`: An overload set whose rules take two
nitpick: RE: syntax for the `regular!(…)` macro: TBH, my Rust- and C++-shaped brain cannot help but interpret the precedence of operations as "a scalar type (of any type?) _or_ a vector of floats of any length".

suggestion: Could we instead try something that's not confusable, like `$constr of $scalar` or `($constr)<$scalar>` instead? I have a patch locally ready to go for the former, if you'd like to take a look.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/valid/expression.rs
> +                        &[resolve(arg0), resolve(arg1), resolve(arg2), resolve(arg3)]
nitpick(if-minor): If the cases with non-contiguous `Some`s truly are `unreachable!(…)`, I think we can write somewhat less bewildering code with a `Iterator`, i.e., like this diff:

```diff
diff --git a/naga/src/valid/expression.rs b/naga/src/valid/expression.rs
index 238f947da4..bfd8c6f08a 100644
--- a/naga/src/valid/expression.rs
+++ b/naga/src/valid/expression.rs
@@ -1017,24 +1017,10 @@
                 arg2,
                 arg3,
             } => {
-                let actuals: &[_] = match (arg1, arg2, arg3) {
-                    (None, None, None) => &[arg],
-                    (Some(arg1), None, None) => &[arg, arg1],
-                    (Some(arg1), Some(arg2), None) => &[arg, arg1, arg2],
-                    (Some(arg1), Some(arg2), Some(arg3)) => &[arg, arg1, arg2, arg3],
-                    _ => unreachable!(),
-                };
-
-                let resolve = |arg| &resolver[arg];
-                let actual_types: &[_] = match *actuals {
-                    [arg0] => &[resolve(arg0)],
-                    [arg0, arg1] => &[resolve(arg0), resolve(arg1)],
-                    [arg0, arg1, arg2] => &[resolve(arg0), resolve(arg1), resolve(arg2)],
-                    [arg0, arg1, arg2, arg3] => {
-                        &[resolve(arg0), resolve(arg1), resolve(arg2), resolve(arg3)]
-                    }
-                    _ => unreachable!(),
-                };
+                let actuals = [Some(arg), arg1, arg2, arg3]
+                    .into_iter()
+                    .flatten()
+                    .map(|val| (val, &resolver[val]));
 
                 // Start with the set of all overloads available for `fun`.
                 let mut overloads = fun.overloads();
@@ -1048,7 +1034,9 @@
                 // abstract and concrete arguments, so we don't need to worry
                 // about that here.
 
-                for (i, (&expr, &ty)) in actuals.iter().zip(actual_types).enumerate() {
+                let mut actuals_len = 0;
+                for ((expr, ty), i) in actuals.zip(1..) {
+                    actuals_len = i;
                     // Remove overloads that cannot accept an `i`'th
                     // argument arguments of type `ty`.
                     overloads = overloads.arg(i, ty, &module.types);
@@ -1066,7 +1054,7 @@
                     }
                 }
 
-                if actuals.len() < overloads.min_arguments() {
+                if actuals_len < overloads.min_arguments() {
                     return Err(ExpressionError::WrongArgumentCount(fun));
                 }
 
```

If the assertions are important, though, then 🤷🏻‍♂️ whatevs.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/valid/expression.rs
question: I fully expected these changes to only be a part of the WGSL front end, as a pass before the validation in `naga::valid`. I see that the type rules for overloads are being exposed in `naga::valid`, though, which means that this would apply to _all_ front ends. Doesn't this expose WGSL's automatic type conversion to other front ends? Isn't that…undesirable? 🤔

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/mod.rs
> +///   make them implement [`Copy`] if we can sort out some details), so it is
nitpick: This note about `Copy` should move to an issue, and not remain an aspiration in documentation.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/mod.rs
> +///   non-empty, you can call its `most_preferred` method to find out which
nitpick: You've linked the other methods, so let's link this one, too!

```suggestion
///   non-empty, you can call its [`most_preferred`] method to find out which
```

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/mod.rs
> +#[allow(rustdoc::private_intra_doc_links)]
nitpick: Friendly reminder that `expect` is better than `allow` for stuff like this. 🙂

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/mod.rs
> +#[macro_use]
nitpick: You should not need to use `macro_use` with Rust 2018 or later; these should be easy to import as with other kinds of items.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +        /// The type of the `prior_arg_span` argument.
typo: s/prior_arg_span/prior_span

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/any_overload_set.rs
> +        pub enum AnyOverloadSet {
question: Why does `AnyOverloadSet`, `List`, or `Regular` need to be `pub`? Their actual usage is hidden, AFAICT. Can't these be `pub(crate)`?

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/list.rs
> +    pub(super) fn from_rules(rules: Vec<Rule>) -> List {
nitpick: In our [2025-03-19](https://docs.google.com/document/d/1Z3qjy3m7eAYaTsh2n-iKxLV4Hjc6wZxgukzdQOgVH1c/edit?tab=t.0#heading=h.314bf4w4elsy) maintainers' meeting, we decided that `pub(in …)` was generally preferable to `pub(super)`. The same also applies for `use super::…` Let's use `crate::…`-qualified paths for both instead.

This feedback applies to other places where `super` is being used, too.

2025-03-28 10:58 UTC, ErichDonGubler commented on naga/src/proc/overloads/list.rs
> +    pub(super) fn from_rules(rules: Vec<Rule>) -> List {
I have a commit ready to go for this, and will plan on pushing once touching base with @jimblandy.

2025-03-28 18:10 UTC, jimblandy commented
> My single big concern is about how we're imposing WGSL's builtin signatures in other langauges, but maybe this isn't new.

Right, this is sort of the background history of the whole approach, and I agree it is a little surprising.

The first thing to notice is that the validator *has always imposed* a single set of typing rules on the IR it sees, and these Naga IR typing rules have always been driven by what is best for WGSL. It's up to the other front ends to cope with that somehow if it's not what they want. For example, SPIR-V and Naga IR have incompatible approaches to atomics, and the SPIR-V front end [engages in strategic fibbing](https://github.com/gfx-rs/wgpu/blob/c7c79a0dc9356081a884b5518d1c08ce7a09c7c5/naga/src/front/atomic_upgrade.rs#L1-L19) to make the rest of Naga accept the code it sees.

In general I think this is workable. As we encounter specific problems, we can decide whether to introduce more detail into the IR, handle things in the front ends, or perhaps make other choices. (Explicitly making the behavior depend on the language seems like it will age poorly, so approaches like the [`Behavior`](https://github.com/gfx-rs/wgpu/blob/c7c79a0dc9356081a884b5518d1c08ce7a09c7c5/naga/src/proc/constant_evaluator.rs#L272-L275) enum are not what we should emulate - although in that specific situation I don't understand the problem well enough yet to propose an alternative.)

It may help to say that I don't think you should bother cross-checking the behavior of the old hand-written Rust type checking code against the new code. I didn't. (I ran the tests, but our validation tests are weak.) All that's actually needed is to verify is that the new code matches what's in the WGSL specification (with the exceptions noted for #7405).

2025-03-29 00:10 UTC, jimblandy commented on naga/src/common/wgsl/types.rs
> +
Right - originally all the comments in the `overloads` module used terminology more closely aligned to the WebGPU spec, talking about "subexpressions" instead of "arguments", for example.

But in the end I changed it to be more function-specific because I couldn't forsee us using this for (say) binary operators or statements in the near future, or ever, really; and in that case, calling them "subexpressions" would make the comments harder to understand for readers of Naga code who only ever saw them being applied to functions.

Ultimately, these are Naga rules that happen to be constructed to match the WGSL rules, not WGSL rules, so I felt the terminology should match what it was being used for in Naga.

2025-03-29 00:32 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                    (call_span, "The function is called here".into()),
I agree about this - although as I think you point out elsewhere it's hard to actually get that message out of Naga at this point. I changed the code to use `TooManyArguments` in the earlier arity check, and I get this message:

```
Could not parse WGSL:
error: Too many arguments passed to `sin`
  ┌─ too-many-args.wgsl:2:7
  │
2 │   _ = sin(10, 20);
  │       ^^^     ^^ This is the first excess argument
  │
  = note: The `sin` function accepts at most 1 argument(s)
```

That seems fine.

2025-03-29 00:35 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                    (call_span, "The function is called here".into()),
I changed this on the other errors as well.

2025-03-29 00:43 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                    (arg_span, "This is the first excess argument".into())
I've added the argument number to the label. I didn't add the type because that information wasn't immediately available at some sites where we use `TooManyArguments`, and it didn't seem relevant.

2025-03-29 00:47 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                ],
I see that rustc suggests deleting the argument, and we certainly could do this. We could definitely make the type-checking work out.

However, do you really think that's a great bit of help from rustc? When people have excess arguments, how often is the fix really "just delete this"? Isn't there usually something else going on - perhaps they misunderstood the function's parameters, say? Ultimately, it's not something that I'm sure is helpful enough to be worth emulating.

2025-03-29 00:50 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                    format!("Because argument #{} has type `{prior_ty}`,", prior_index + 1),
Oh, 'prior' doesn't mean 'immediately prior'. If you look at the code in `naga::front::wgsl::lower`, we actually re-scan the arguments from the first and check which prior argument it was that made this argument's type unacceptable. When we extend this code to handle texture sampling operations, these will often identify the texture argument as the culprit, which is exactly what we want.

If you think most readers will assume that 'prior' means 'immediately prior', then we should rename those fields. Do you have suggestions?

2025-03-29 01:00 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                    "Inconsistent type passed as argument #{} to `{function}`",
I've fixed this.

2025-03-29 01:02 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                    "Inconsistent type passed as argument #{} to `{function}`",
It seems like we usually do capitalize for notes, though? That feels right, since those are complete sentences. So I left those there.

2025-03-29 01:07 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                    "Wrong type passed as argument #{} to `{function}`",
I can see the case that the labels should be self-sufficient. It's harder to see the argument that the lead message should not include details like the one cited here.

If this is something you'd like to discuss in the maintainers' meeting, the agenda is open!

2025-03-29 01:10 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                    if arguments.len() < min_arguments || max_arguments < arguments.len() {
Agreed that `Range` would be a nicer API.

However, in responding to earlier comments I changed this code to return `TooManyArguments` for that case, which gave us separate `if` statements for the too-few and too-many cases, meaning that `contains` isn't the right thing any more.

2025-03-29 01:12 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                    if arguments.len() < min_arguments || max_arguments < arguments.len() {
I think you mean `Range::contains`, not `RangeFull::contains`, right?

2025-03-29 01:15 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                    if arguments.len() < min_arguments || max_arguments < arguments.len() {
(Does returning a `Range<usize>` imply that every arity within the range is accepted?)

2025-03-29 01:30 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                    if arguments.len() < min_arguments || max_arguments < arguments.len() {
Having tried this out, I'm not sure it's actually an improvement. Look at this:

```rust
                    let argument_counts = remaining_overloads.argument_counts();
                    if arguments.len() < argument_counts.start {
                        return Err(Box::new(Error::WrongArgumentCount {
                            span,
                            expected: argument_counts.start as u32..argument_counts.end as u32 + 1,
                            found: arguments.len() as u32,
                        }));
                    }
                    if arguments.len() >= argument_counts.end {
                        return Err(Box::new(Error::TooManyArguments {
                            function: fun.to_wgsl_for_diagnostics(),
                            call_span: span,
                            arg_span: ctx.ast_expressions.get_span(arguments[argument_counts.end - 1]),
                            max_arguments: (argument_counts.end - 1) as _,
                        }));
                    }
```

This seems worse:

- We're now talking about `counts.start` and `counts.end`, which are less legible than `min_arguments` and `max_arguments`.
- Since we want to use `Range`, not `RangeInclusive` with its distracting and irrelevant `Option`, the `end` needs to be one greater than the value we always actually want, so we get little fixups everywhere.

At first I thought it would be good, but having tried it out, I'm not fond of this change.

2025-03-29 02:20 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                                // would ever be allowed there.
The only way this code can be reached is if some overloads of the function have more arguments than others. In this situation, the types of the preceding arguments determine whether an additional argument is acceptable. Since `MathFunction` contains only functions whose overloads all have the same arity, this code is unreachable.

However, in #7442 I pull this code out into its own function, in hopes of reusing it for addressing bugs like #7427, regarding `textureSampleLevel` calls. That function's overloads do have varying arities, so this code will become reachable.

I think the earlier code that simply checks the call arity against `max_arguments` could be removed, which would make this code reachable.

Further, the code that checks `min_arguments` is insufficient for functions whose overloads have varying arities: even if the call supplies as many arguments as needed by the shortest overload, that doesn't mean that it supplies as many arguments as needed by the shortest overload *that accepts the types it's passing*. For example, `textureSampleLevel`'s shortest overload takes four arguments; but if the first argument is a `texture_2d_array`, then at least five arguments are required.

So:

- If you would like this code to be as simple as possible given its current uses, then the code you're commenting on here should be replaced with an `unreachable`.

- If you would like this code to be as general as possible given what `OverloadSet` can express, then the code commented on here should stay, the earlier `min_arguments`/`max_arguments`-driven checks should go, and we need to add a check that a sufficient number of arguments was passed.

- If you're willing to just let this stand because you are sure it's all going to change anyway so the incoherence isn't worth fixing, then we can let it be. I agree this is sloppy.

2025-03-29 02:25 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                        "`fn`, `diagnostic`, `enable`, `requires`, `;`) ",
Sorry. I totally do not remember fixing this. It's not relevant to the rest of the commit and should have been separated out.

2025-03-29 02:28 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                notes.extend(allowed.iter().map(|ty| format!("allowed type: {ty}")));
Huh, TIL about `lazy_format`. But on the error paths the allocation probably doesn't matter.

2025-03-29 19:40 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +            Error::WrongArgumentType {
I will write tests. I'm sorry I skipped this.

2025-03-29 20:00 UTC, jimblandy commented
I took a look through your [branch of feedback fixes](https://github.com/erichdongubler-mozilla/wgpu/tree/erichdongubler/push-xqszqmlsmvyk). The simplification to arg enumeration is beautiful, but I don't think it's right; [I commented](https://github.com/erichdongubler-mozilla/wgpu/commit/8cdbe25e1cb21cc0a2f371ceb1f4d4f35bc26975#r154594216). 

There should be a way to salvage this, though.

2025-03-29 20:15 UTC, ErichDonGubler commented
> I took a look through your [branch of feedback fixes](https://github.com/erichdongubler-mozilla/wgpu/tree/erichdongubler/push-xqszqmlsmvyk?rgh-link-date=2025-03-29T20%3A00%3A14Z). The simplification to arg enumeration is beautiful, but I don't think it's right; [I commented](https://github.com/erichdongubler-mozilla/wgpu/commit/8cdbe25e1cb21cc0a2f371ceb1f4d4f35bc26975#r154594216).
> 
> There should be a way to salvage this, though.

I have commented back. 😊

2025-03-30 20:29 UTC, jimblandy commented
> I have commented back. 😊

@ErichDonGubler Here's what I think is needed to actually make this work: https://github.com/jimblandy/wgpu/commit/6e955e7907fa509e96489dc0365f4219cd6a7cc5

That includes a test which the old code passes, if the `unreachable!` is changed to return an error instead.

The cleanest thing I could come up with was to replace the `flatten` with a `map_while`, and then use `by_ref` to let us pick up where `map_while` left off and check that everything is `None`. In the end, by the time we've made it work, I'm not really sure it's easier to understand the effect. At least that ugly stack of `match` arms is pretty obvious about what it's doing.

2025-03-31 00:07 UTC, ErichDonGubler commented
> > I have commented back. 😊
> 
> @ErichDonGubler Here's what I think is needed to actually make this work: [jimblandy@6e955e7](https://github.com/jimblandy/wgpu/commit/6e955e7907fa509e96489dc0365f4219cd6a7cc5)
> 
> That includes a test which the old code passes, if the `unreachable!` is changed to return an error instead.
> 
> The cleanest thing I could come up with was to replace the `flatten` with a `map_while`, and then use `by_ref` to let us pick up where `map_while` left off and check that everything is `None`. In the end, by the time we've made it work, I'm not really sure it's easier to understand the effect. At least that ugly stack of `match` arms is pretty obvious about what it's doing.

I actually ended up suggesting today using `std::iter::successors`; I feel like that's sufficiently small and clear, but maybe not. 🤷🏻‍♂️

2025-03-31 19:35 UTC, jimblandy commented
I pushed some commits that address some review comments, but there are still more to go.

2025-03-31 19:38 UTC, jimblandy commented on naga/src/proc/overloads/list.rs
> +    pub(super) fn from_rules(rules: Vec<Rule>) -> List {
Erich's commit is now in this PR: https://github.com/gfx-rs/wgpu/pull/6833/commits/1f3d37c24b61fc7f0c3e7c62f7f6ae289876ff16

2025-03-31 19:56 UTC, jimblandy commented on naga/src/proc/overloads/any_overload_set.rs
> +        pub enum AnyOverloadSet {
I tightened these to `pub(in crate::proc::overloads)`. I don't think there's any reason for them to be visible outside this module.

2025-03-31 20:25 UTC, jimblandy commented on naga/src/proc/overloads/mod.rs
> +#[macro_use]
I tried using path-based scope first, but I couldn't get it to work. I'll try again.

2025-03-31 20:35 UTC, jimblandy commented on naga/src/proc/overloads/mod.rs
> +#[macro_use]
So, if I'm understanding correctly, in order to use path-based scoping, I need to put `#[macro_export]` on them, which not only makes them visible throughout Naga (which we don't want), but also makes them part of the Naga crate's public interface (which we definitely don't want).

2025-03-31 20:42 UTC, jimblandy commented on naga/src/proc/overloads/mod.rs
> +///   make them implement [`Copy`] if we can sort out some details), so it is
I added a note about `Copy` to #7401 and removed it from the comment.

2025-03-31 20:42 UTC, jimblandy commented on naga/src/valid/expression.rs
This question is answered [here](https://github.com/gfx-rs/wgpu/pull/6833#issuecomment-2762092100).

2025-03-31 20:45 UTC, jimblandy commented on naga/src/valid/expression.rs
> +                        &[resolve(arg0), resolve(arg1), resolve(arg2), resolve(arg3)]
The first `unreachable!` was bogus; removed in 353bc777f.

The rest, I would like to leave as-is. As we discussed later in this PR, using `flatten` is beautiful but makes error cases indistinguishable from correct cases, and by the time we've fixed it the code doesn't look beautiful any more. I think the existing ugly match is actually the more quickly legible option.

2025-03-31 20:46 UTC, jimblandy commented on naga/src/proc/overloads/regular.rs
> +/// - `regular!(2, SCALAR|VECN<FLOAT>)`: An overload set whose rules take two
I agree about the weird implied precedence of `|` and `<>`. I incorporated your fix.

2025-03-31 20:53 UTC, jimblandy commented on naga/src/valid/expression.rs
> +                        */
This was an oversight; it should have been deleted after the earlier comment was added.

2025-03-31 21:14 UTC, jimblandy commented on naga/src/proc/overloads/rule.rs
> +/// in the builtin function database.
I 100% agree. I must have written this while tired.

2025-03-31 21:21 UTC, jimblandy commented on naga/src/proc/overloads/one_bits_iter.rs
I've added tests.

2025-04-01 00:03 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                                // would ever be allowed there.
> The comment makes it sound like allowed should be computed from fun_overloads, instead of remaining_overloads. 

The comment was misleading. I've changed it to properly describe what we're doing:

```rust
// No overload of `fun` accepts this type as the
// arg_index'th argument. Determine the set of types that
// were still possibilities, given the prior arguments.
```

2025-04-01 00:08 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                                // would ever be allowed there.
I've decided to use `unreachable!` where appropriate, and simply re-introduce these cases once they're possible.

2025-04-01 17:10 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                ],
That's an interesting question. I think it's helpful for folks in Rust specifically, because the strength of types makes it significantly less likely to be a bad suggestion, and there are no overloads. But...in WGSL, I have serious doubts. Overloads and automatic conversion make the suggestion seem significantly less useful.

As an example, for `textureSampleLevel`, we have overloads for all forms of texture being sampled that effectively offer an optional `offset` argument. _Sure_, the user could match the overload with `offset` omitted entirely, but choosing that different overload changes _behavior_. I think it's more likely that the user might have goofed up the argument, but they _definitely_ don't want to remove it.

So, I guess I can retract my suggestion for now. 😅 Confronting them with the problem and explaining clearly with the available overloads is a good enough diagnostic in this case.

2025-04-01 17:26 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    format!("Because argument #{} has type `{prior_ty}`,", prior_index + 1),
I think we could likely come up with a better descriptor than `prior`, in that case. If it's minor, awesome, let's get it in. Otherwise, I consider this conversation resolved on my end.

2025-04-01 17:27 UTC, ErichDonGubler commented on naga/src/front/wgsl/lower/mod.rs
> +                    if arguments.len() < min_arguments || max_arguments < arguments.len() {
If we're going to have separate errors be returned for each end of the bounds check, then I don't think the suggestion to use `RangeInclusive` (and yes, I meant to refer to that one, rather than `RangeFull` or even `Range 😅) is useful anymore.

2025-04-01 17:28 UTC, ErichDonGubler commented on naga/src/front/wgsl/lower/mod.rs
> +                    if arguments.len() < min_arguments || max_arguments < arguments.len() {
Closing, since the basis of this suggestion seems invalidated.

2025-04-01 17:29 UTC, ErichDonGubler commented on naga/src/front/wgsl/lower/mod.rs
> +                                // would ever be allowed there.
This seems resolved now?

2025-04-02 01:25 UTC, jimblandy commented on naga/src/front/wgsl/lower/mod.rs
> +                                // would ever be allowed there.
The current version of the PR has tests for all error cases. `WrongArgumentCountForOverloads` and `AmbiguousCall` cannot arise in Naga IR today, so they've been deleted.

2025-04-02 01:27 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +            Error::WrongArgumentType {
All errors are now tested. Because all the functions in `MathFunctions` take the same number of arguments, it's not currently possible to elicit the `TooManyArgumentsForOverloads` error. I've removed that error, and used `unreachable!` in the spots that used to raise it.

2025-04-02 02:03 UTC, jimblandy commented on naga/src/proc/overloads/mod.rs
> +            Mf::InsertBits => lists::insert_bits().into(),
Okay, I've pushed 537c0c57a which rearranges things a bit. Now all the rules for `MathFunction` are in one file. I think it's good.

2025-04-02 02:11 UTC, jimblandy commented on naga/src/front/wgsl/error.rs
> +                    format!("Because argument #{} has type `{prior_ty}`,", prior_index + 1),
I renamed them from `prior_foo` to `inconsistent_foo`.

2025-04-02 02:13 UTC, jimblandy commented
@ErichDonGubler @andyleiserson Okay, I believe I've addressed all comments with the current text of this PR. I've left some comments unresolved where I pushed back on the suggestion; please mark them resolved if you're okay with that.

2025-04-02 17:42 UTC, ErichDonGubler commented on naga/src/proc/overloads/mod.rs
> +#[macro_use]
This should be possible in Rust 2018, and it should not be necessary to use `macro_export` or `macro_use`. Example:

```rust
mod asdf {
    macro_rules! asdf {
        () => {};
    }
    pub(crate) use asdf;
}

fn main() {
    asdf::asdf!();
}
```

2025-04-02 17:57 UTC, jimblandy commented on naga/src/proc/overloads/mod.rs
> +#[macro_use]
Okay, I have this working with path-based scoping now. There was a trick to it.

2025-04-02 19:09 UTC, jimblandy commented
> Maybe it would be worth adding some tests from [the bugs we're expecting this to fix](https://bugzilla.mozilla.org/buglist.cgi?query_format=advanced&o1=substring&f1=see_also&v1=https%3A%2F%2Fgithub.com%2Fgfx-rs%2Fwgpu%2Fissues%2F6443&component=Graphics%3A%20WebGPU&list_id=17488908)? I think `pow`, `min`/`max`, and `clamp` with a mix of abstract and concrete arguments are common offenders.

I've added these tests now.

2025-04-02 20:42 UTC, ErichDonGubler commented on naga/src/common/diagnostic_display.rs
> +        ))?;
> (This is the kind of feedback I was expecting to get on #7344, I was sure you were going to ding me for the `ToWgsl` / `TryToWgsl` / `Formatter` chaos!)

I don't remember that review super well (😅), but I think the problem is a bit more obvious in usages like this where a `Formatter`-ish API is being implemented using a `String`-returning API. 🙂

2025-04-02 20:43 UTC, ErichDonGubler commented on naga/src/common/wgsl/types.rs
> +
🤷🏻‍♂️ I will not hold up a merge on account of this conversation, mostly just curious if thinking had been applied in this direction. It is; I'll `Resolve` now. 🫡

2025-04-02 20:45 UTC, ErichDonGubler commented on naga/src/front/wgsl/error.rs
> +                    "Wrong type passed as argument #{} to `{function}`",
I'll pass on the suggestion to discuss in a meeting for now; I think the time in which we'll use the consensus is so far away from when I'd be building it, I'm not super interested, ATM.

2025-04-02 20:51 UTC, ErichDonGubler approved these changes
AFTER MANY EXHAUSTING HOURS OF EPIC WORK BY THE JIM

Here's yer green checkmark. ✨✅😀👍🏻✨

2025-04-02 20:51 UTC, ErichDonGubler commented
@andyleiserson, I presume your feedback is satisfied. If so, could you please indicate, and optionally rebase-and-merge?

2025-04-02 21:12 UTC, jimblandy commented
I've squashed all the changes that should have been squashed, so this can be landed with a rebase.

If you want to see the last few revisions as separate commits, they're at https://github.com/jimblandy/wgpu/commits/naga-function-database-final-revisions/

2025-04-02 22:26 UTC, andyleiserson approved these changes
LGTM as well, excited to see this land!

2025-04-02 22:27 UTC, merged